### ISSUE TITLE
postgres check, Broken pipe, doesn't reestablish connection

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#1003]
```console
 postgres
    --------
      - instance #0 [ERROR]: error(32, 'Broken pipe')
      - Collected 0 metrics, 0 events & 0 service checks
```

This occurs after a pg-related blip, like a pg service restart. The connection was broken, but it has recovered. It will remain in this state until the Agent is restarted.

I would expect a connection retry at some point.

**Comment by LeoCavaille** [comment]
Reopening this issue as it was reported to still occur with agent 5.3.

**Comment by yannmh** [comment]
@LeoCavaille do we have more details on this new case ? I am pushing back the issue to 5.5.0 for lack of time.

**Comment by talwai** [comment]
Bumping to `5.6.0` in the absence of more definition on this

**Comment by remh** [comment]
Closing for lack of details.
