### ISSUE TITLE
Directory check pattern should handle directories better

### ISSUE THREAD

**Issue by Osterjour** [DataDog/dd-agent#1040]
Right now the pattern isn't a pattern for filenames but for the whole path (including the filename).
This isn't a problem if the user uses a pattern like "\*.txt" (like in the example). But if the pattern is something like "fileprefix_*" it is unintuitive we need to prefix the whole path to match.
I would have done the change by myself and add a pull request, but I'm not sure how this should be changed:
* just match the pattern against the filename (without the directory) could break already existing installations
* add ".*" at the beginning of the pattern changes the behavior also
* add the directory to the pattern is hard if recursing is true

Maybe this should be only documented better?

**Comment by remh** [comment]
Adding this to our triage section for our 5.3.0 release.

**Comment by remh** [comment]
Documentation was actually made clearer with this commit: https://github.com/DataDog/dd-agent/commit/df832bab90059753e8becfbdb30df4b6ceff6586 
Closing.
