### ISSUE TITLE
If jenkins builds appear in the future, agent should assume the builds timestamp are in UTC

### ISSUE THREAD

**Issue by alq666** [DataDog/dd-agent#108]
https://gist.github.com/3137587#comments

Notice that the build directory name is in UTC (2012-07-12-17:31:00 was run at 12:31pm on that day with a CDT timezone).

If the builds are the future, test whether considering that they are actually in UTC would make more sense (i.e. utc(build) <= now).

**Comment by remh** [comment]
Won't fix, the jenkins plugin https://github.com/DataDog/jenkins-datadog-plugin pushes events directly.
