### ISSUE TITLE
override proxies for localhost?

### ISSUE THREAD

**Issue by jmoiron** [DataDog/dd-agent#1112]
We received [a report](https://datadog.desk.com/agent/case/14226) that when the `http_proxy` env var was set, `urllib.getproxies()` was bypassing local localhost resolution and getting the wrong thing, something like `localhost.resolv.conf.search`.  The reporter had discovered a [similar issue](https://github.com/kennethreitz/requests/issues/879) that requests dealt with.

I'm wondering if it might be a good idea to disable proxies for localhost resolution across the board to avoid this:

```python
import os
if 'no_proxy' not in os.environ:
    os.environ['no_proxy'] = '127.0.0.1,localhost'
```

Or even something smarter which always attempts to add `127.0.0.1,localhost` to the env `no_proxy`, even if it's already set to something else.

**Comment by LeoCavaille** [comment]
Will be fixed in 5.2 according to the commit above

**Comment by remh** [comment]
This commit is not merged on master yet. It needs to be properly tested. Opening a PR for it.

**Comment by remh** [comment]
See https://github.com/DataDog/dd-agent/pull/1290
