### ISSUE TITLE
mysql localhost

### ISSUE THREAD

**Issue by celenechang** [DataDog/dd-agent#1120]
setting "localhost" in the mysql.yaml file may produce this error:

```
mysql
-----
- instance #0 [ERROR]: OperationalError(2003, 'Can\'t connect to
MySQL server on \'localhost\' ((1045, u"Access denied for user
\'datadog\'@\'127.0.0.1\' (using password: YES)"))')
```

the workaround is to grant permissions to datadog@127.0.0.1 , rather than datadog@localhost

desk cases 14501 and 14502

**Comment by mikkokotila** [comment]
Does it make sense to change this in the docs?
