### ISSUE TITLE
Should not be using netstat to gather socket connections in network.py

### ISSUE THREAD

**Issue by tliakos** [DataDog/dd-agent#1156]
Should be using 'ss' as opposed to netstat. I have instances that are running with socket connections > 20000 - Netstat will either timeout or topple over before the metric is sent. Can we discuss changing this to ss since it gets its metrics directly from the kernel space as opposed to /proc (netstat) which is heavy.

(line 141) netstat = subprocess.Popen(["netstat", "-n", "-u", "-t", "-a"],
stdout=subprocess.PIPE,
close_fds=True).communicate()[0]

**Comment by joelvanvelden** [comment]
:+1: Netstat is evil - it will throw out information to ensure output is formatted nicely - surely the worst design goal ever. Aparantly this is not considered a bug!

https://bugzilla.redhat.com/show_bug.cgi?id=755905

>this is expected behavior.
>Netstat produces output formatted to approx. 80 characters wide.
>To achieve this width, columns are truncated.

**Comment by yannmh** [comment]
Fixed with #1859.
