### ISSUE TITLE
"INFO gave up: dogstatsd entered FATAL state, too many start retries too quickly"

### ISSUE THREAD

**Issue by Vergnais** [DataDog/dd-agent#1159]
Hi,
I've just setup a coreOS cluster (3 nodes) and launched a global service with fleet on all members.
(following the doc :https://coreos.com/docs/launching-containers/launching/launching-containers-fleet/)

Service is ok for fleet but nothing is collected. Here are the logs i got. I did not found any tricks on the net...sorry if i missed something

core@coreos_62 ~ $ journalctl -b -u datadog.global.service
-- Logs begin at Wed 2014-10-15 13:02:50 UTC, end at Wed 2014-10-15 20:11:52 UTC. --
Oct 15 20:00:04 coreos_62 systemd[1]: Starting Monitoring Service...
Oct 15 20:00:04 coreos_62 docker[1615]: Error response from daemon: No such container: dd-agent
Oct 15 20:00:04 coreos_62 docker[1615]: 2014/10/15 20:00:04 Error: failed to kill one or more containers
Oct 15 20:00:04 coreos_62 docker[1627]: Error response from daemon: No such container: dd-agent
Oct 15 20:00:04 coreos_62 docker[1627]: 2014/10/15 20:00:04 Error: failed to remove one or more containers
Oct 15 20:00:04 coreos_62 docker[1641]: Pulling repository datadog/docker-dd-agent
Oct 15 20:00:26 coreos_62 systemd[1]: Started Monitoring Service.
Oct 15 20:00:26 coreos_62 bash[1681]: 2014-10-15 20:00:26,695 CRIT Supervisor running as root (no user in config file)
Oct 15 20:00:26 coreos_62 bash[1681]: 2014-10-15 20:00:26,716 INFO RPC interface 'supervisor' initialized
Oct 15 20:00:26 coreos_62 bash[1681]: 2014-10-15 20:00:26,717 CRIT Server 'unix_http_server' running without any HTTP authentication checking
Oct 15 20:00:26 coreos_62 bash[1681]: 2014-10-15 20:00:26,717 INFO supervisord started with pid 1
Oct 15 20:00:27 coreos_62 bash[1681]: 2014-10-15 20:00:27,719 INFO spawned: 'dogstatsd' with pid 13
Oct 15 20:00:27 coreos_62 bash[1681]: 2014-10-15 20:00:27,720 INFO spawned: 'forwarder' with pid 14
Oct 15 20:00:27 coreos_62 bash[1681]: 2014-10-15 20:00:27,722 INFO spawned: 'collector' with pid 15
Oct 15 20:00:27 coreos_62 bash[1681]: 2014-10-15 20:00:27,723 INFO spawned: 'pup' with pid 16
Oct 15 20:00:28 coreos_62 bash[1681]: 2014-10-15 20:00:28,489 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:00:28 coreos_62 bash[1681]: 2014-10-15 20:00:28,582 INFO exited: collector (exit status 1; not expected)
Oct 15 20:00:29 coreos_62 bash[1681]: 2014-10-15 20:00:29,584 INFO spawned: 'dogstatsd' with pid 27
Oct 15 20:00:29 coreos_62 bash[1681]: 2014-10-15 20:00:29,585 INFO spawned: 'collector' with pid 28
Oct 15 20:00:29 coreos_62 bash[1681]: 2014-10-15 20:00:29,586 INFO success: pup entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Oct 15 20:00:29 coreos_62 bash[1681]: 2014-10-15 20:00:29,915 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:00:29 coreos_62 bash[1681]: 2014-10-15 20:00:29,950 INFO exited: collector (exit status 1; not expected)
Oct 15 20:00:31 coreos_62 bash[1681]: 2014-10-15 20:00:31,953 INFO spawned: 'dogstatsd' with pid 35
Oct 15 20:00:31 coreos_62 bash[1681]: 2014-10-15 20:00:31,955 INFO spawned: 'collector' with pid 36
Oct 15 20:00:32 coreos_62 bash[1681]: 2014-10-15 20:00:32,287 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:00:32 coreos_62 bash[1681]: 2014-10-15 20:00:32,320 INFO exited: collector (exit status 1; not expected)
Oct 15 20:00:32 coreos_62 bash[1681]: 2014-10-15 20:00:32,430 INFO exited: pup (exit status 0; expected)
Oct 15 20:00:33 coreos_62 bash[1681]: 2014-10-15 20:00:33,431 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
Oct 15 20:00:35 coreos_62 bash[1681]: 2014-10-15 20:00:35,456 INFO spawned: 'dogstatsd' with pid 43
Oct 15 20:00:35 coreos_62 bash[1681]: 2014-10-15 20:00:35,456 INFO spawned: 'collector' with pid 44
Oct 15 20:00:35 coreos_62 bash[1681]: 2014-10-15 20:00:35,791 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:00:35 coreos_62 bash[1681]: 2014-10-15 20:00:35,812 INFO gave up: dogstatsd entered FATAL state, too many start retries too quickly
Oct 15 20:00:35 coreos_62 bash[1681]: 2014-10-15 20:00:35,826 INFO exited: collector (exit status 1; not expected)
Oct 15 20:00:36 coreos_62 bash[1681]: 2014-10-15 20:00:36,832 INFO gave up: collector entered FATAL state, too many start retries too quickly
Oct 15 20:05:31 coreos_62 systemd[1]: Stopping Monitoring Service...
Oct 15 20:05:31 coreos_62 bash[1681]: 2014-10-15 20:05:31,049 WARN received SIGTERM indicating exit request
Oct 15 20:05:31 coreos_62 bash[1681]: 2014-10-15 20:05:31,057 INFO waiting for forwarder to die
Oct 15 20:05:31 coreos_62 bash[1681]: 2014-10-15 20:05:31,086 INFO stopped: forwarder (exit status 0)
Oct 15 20:05:31 coreos_62 systemd[1]: Stopped Monitoring Service.
Oct 15 20:05:51 coreos_62 systemd[1]: Starting Monitoring Service...
Oct 15 20:05:51 coreos_62 docker[2137]: dd-agent
Oct 15 20:05:51 coreos_62 docker[2146]: dd-agent
Oct 15 20:05:51 coreos_62 docker[2157]: Pulling repository datadog/docker-dd-agent
Oct 15 20:06:11 coreos_62 systemd[1]: Started Monitoring Service.
Oct 15 20:06:13 coreos_62 bash[2193]: 2014-10-15 20:06:13,217 CRIT Supervisor running as root (no user in config file)
Oct 15 20:06:13 coreos_62 bash[2193]: 2014-10-15 20:06:13,227 INFO RPC interface 'supervisor' initialized
Oct 15 20:06:13 coreos_62 bash[2193]: 2014-10-15 20:06:13,227 CRIT Server 'unix_http_server' running without any HTTP authentication checking
Oct 15 20:06:13 coreos_62 bash[2193]: 2014-10-15 20:06:13,228 INFO supervisord started with pid 1
Oct 15 20:06:14 coreos_62 bash[2193]: 2014-10-15 20:06:14,230 INFO spawned: 'dogstatsd' with pid 13
Oct 15 20:06:14 coreos_62 bash[2193]: 2014-10-15 20:06:14,231 INFO spawned: 'forwarder' with pid 14
Oct 15 20:06:14 coreos_62 bash[2193]: 2014-10-15 20:06:14,232 INFO spawned: 'collector' with pid 15
Oct 15 20:06:14 coreos_62 bash[2193]: 2014-10-15 20:06:14,234 INFO spawned: 'pup' with pid 16
Oct 15 20:06:15 coreos_62 bash[2193]: 2014-10-15 20:06:15,022 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:06:15 coreos_62 bash[2193]: 2014-10-15 20:06:15,119 INFO exited: collector (exit status 1; not expected)
Oct 15 20:06:16 coreos_62 bash[2193]: 2014-10-15 20:06:16,120 INFO spawned: 'dogstatsd' with pid 27
Oct 15 20:06:16 coreos_62 bash[2193]: 2014-10-15 20:06:16,121 INFO spawned: 'collector' with pid 28
Oct 15 20:06:16 coreos_62 bash[2193]: 2014-10-15 20:06:16,122 INFO success: pup entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Oct 15 20:06:16 coreos_62 bash[2193]: 2014-10-15 20:06:16,454 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:06:16 coreos_62 bash[2193]: 2014-10-15 20:06:16,488 INFO exited: collector (exit status 1; not expected)
Oct 15 20:06:18 coreos_62 bash[2193]: 2014-10-15 20:06:18,492 INFO spawned: 'dogstatsd' with pid 35
Oct 15 20:06:18 coreos_62 bash[2193]: 2014-10-15 20:06:18,494 INFO spawned: 'collector' with pid 36
Oct 15 20:06:18 coreos_62 bash[2193]: 2014-10-15 20:06:18,831 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:06:18 coreos_62 bash[2193]: 2014-10-15 20:06:18,859 INFO exited: collector (exit status 1; not expected)
Oct 15 20:06:18 coreos_62 bash[2193]: 2014-10-15 20:06:18,961 INFO exited: pup (exit status 0; expected)
Oct 15 20:06:19 coreos_62 bash[2193]: 2014-10-15 20:06:19,963 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
Oct 15 20:06:21 coreos_62 bash[2193]: 2014-10-15 20:06:21,989 INFO spawned: 'dogstatsd' with pid 43
Oct 15 20:06:21 coreos_62 bash[2193]: 2014-10-15 20:06:21,990 INFO spawned: 'collector' with pid 44
Oct 15 20:06:22 coreos_62 bash[2193]: 2014-10-15 20:06:22,320 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:06:22 coreos_62 bash[2193]: 2014-10-15 20:06:22,338 INFO gave up: dogstatsd entered FATAL state, too many start retries too quickly
Oct 15 20:06:22 coreos_62 bash[2193]: 2014-10-15 20:06:22,351 INFO exited: collector (exit status 1; not expected)
Oct 15 20:06:23 coreos_62 bash[2193]: 2014-10-15 20:06:23,351 INFO gave up: collector entered FATAL state, too many start retries too quickly
Oct 15 20:09:06 coreos_62 systemd[1]: Stopping Monitoring Service...
Oct 15 20:09:06 coreos_62 bash[2193]: 2014-10-15 20:09:06,141 WARN received SIGTERM indicating exit request
Oct 15 20:09:06 coreos_62 bash[2193]: 2014-10-15 20:09:06,147 INFO waiting for forwarder to die
Oct 15 20:09:06 coreos_62 bash[2193]: 2014-10-15 20:09:06,160 INFO stopped: forwarder (exit status 0)
Oct 15 20:09:06 coreos_62 systemd[1]: Stopped Monitoring Service.
Oct 15 20:09:26 coreos_62 systemd[1]: Stopped Monitoring Service.
Oct 15 20:09:31 coreos_62 systemd[1]: Starting Monitoring Service...
Oct 15 20:09:31 coreos_62 docker[2536]: dd-agent
Oct 15 20:09:31 coreos_62 docker[2550]: dd-agent
Oct 15 20:09:31 coreos_62 docker[2562]: Pulling repository datadog/docker-dd-agent
Oct 15 20:09:59 coreos_62 systemd[1]: Started Monitoring Service.
Oct 15 20:09:59 coreos_62 bash[2608]: 2014-10-15 20:09:59,716 CRIT Supervisor running as root (no user in config file)
Oct 15 20:09:59 coreos_62 bash[2608]: 2014-10-15 20:09:59,724 INFO RPC interface 'supervisor' initialized
Oct 15 20:09:59 coreos_62 bash[2608]: 2014-10-15 20:09:59,724 CRIT Server 'unix_http_server' running without any HTTP authentication checking
Oct 15 20:09:59 coreos_62 bash[2608]: 2014-10-15 20:09:59,725 INFO supervisord started with pid 1
Oct 15 20:10:00 coreos_62 bash[2608]: 2014-10-15 20:10:00,727 INFO spawned: 'dogstatsd' with pid 11
Oct 15 20:10:00 coreos_62 bash[2608]: 2014-10-15 20:10:00,729 INFO spawned: 'forwarder' with pid 12
Oct 15 20:10:00 coreos_62 bash[2608]: 2014-10-15 20:10:00,732 INFO spawned: 'collector' with pid 13
Oct 15 20:10:00 coreos_62 bash[2608]: 2014-10-15 20:10:00,737 INFO spawned: 'pup' with pid 14
Oct 15 20:10:01 coreos_62 bash[2608]: 2014-10-15 20:10:01,529 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:10:01 coreos_62 bash[2608]: 2014-10-15 20:10:01,608 INFO exited: collector (exit status 1; not expected)
Oct 15 20:10:02 coreos_62 bash[2608]: 2014-10-15 20:10:02,610 INFO spawned: 'dogstatsd' with pid 25
Oct 15 20:10:02 coreos_62 bash[2608]: 2014-10-15 20:10:02,610 INFO spawned: 'collector' with pid 26
Oct 15 20:10:02 coreos_62 bash[2608]: 2014-10-15 20:10:02,611 INFO success: pup entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Oct 15 20:10:02 coreos_62 bash[2608]: 2014-10-15 20:10:02,965 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:10:02 coreos_62 bash[2608]: 2014-10-15 20:10:02,998 INFO exited: collector (exit status 1; not expected)
Oct 15 20:10:05 coreos_62 bash[2608]: 2014-10-15 20:10:05,001 INFO spawned: 'dogstatsd' with pid 33
Oct 15 20:10:05 coreos_62 bash[2608]: 2014-10-15 20:10:05,002 INFO spawned: 'collector' with pid 34
Oct 15 20:10:05 coreos_62 bash[2608]: 2014-10-15 20:10:05,351 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:10:05 coreos_62 bash[2608]: 2014-10-15 20:10:05,380 INFO exited: collector (exit status 1; not expected)
Oct 15 20:10:05 coreos_62 bash[2608]: 2014-10-15 20:10:05,459 INFO exited: pup (exit status 0; expected)
Oct 15 20:10:06 coreos_62 bash[2608]: 2014-10-15 20:10:06,461 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
Oct 15 20:10:08 coreos_62 bash[2608]: 2014-10-15 20:10:08,481 INFO spawned: 'dogstatsd' with pid 41
Oct 15 20:10:08 coreos_62 bash[2608]: 2014-10-15 20:10:08,482 INFO spawned: 'collector' with pid 42
Oct 15 20:10:08 coreos_62 bash[2608]: 2014-10-15 20:10:08,812 INFO exited: dogstatsd (exit status 1; not expected)
Oct 15 20:10:08 coreos_62 bash[2608]: 2014-10-15 20:10:08,833 INFO gave up: dogstatsd entered FATAL state, too many start retries too quickly
Oct 15 20:10:08 coreos_62 bash[2608]: 2014-10-15 20:10:08,850 INFO exited: collector (exit status 1; not expected)
Oct 15 20:10:09 coreos_62 bash[2608]: 2014-10-15 20:10:09,851 INFO gave up: collector entered FATAL state, too many start retries too quickly

**Comment by remh** [comment]
Closing as we didn't get enough information to investigate.

**Comment by ineu** [comment]
Just a quick note to everyone who finds this: I've had the very same issue. Problem was in incorrect systemd unit. I've just copied docker run line from README and didn't remove `-d` flag, so docker went into background, appearing to systemd as terminated.
Here's my working unit file, should anyone face the same problem:
```
[Unit]
Description=Datadog client

[Service]
TimeoutStartSec=180

ExecStartPre=-/usr/bin/docker kill %p
ExecStartPre=-/usr/bin/docker rm %p

ExecStart=/bin/bash -c '\
  /usr/bin/docker run --privileged --name %p -h `hostname` \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /proc/mounts:/host/proc/mounts:ro \
    -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
    -e API_KEY=SECRETKEY \
    datadog/docker-dd-agent'

ExecStop=/usr/bin/docker stop %p

[X-Fleet]
Global=true
```

**Comment by alq666** [comment]
@ineu this is the unit file we use: https://github.com/DataDog/docker-dd-agent/blob/master/dd-agent.service

Slightly different in that it uses `etcd` instead of the environment.

**Comment by lfittl** [comment]
Anyone else encountering this, another cause for this, apart from `-d` being used (which you shouldn't in a systemd service), is that ``hostname`` doesn't work without having a shell in the ExecStart line.

Since its systemd you can actually use `%H` for this, so it becomes:

```
ExecStart=/usr/bin/docker run --privileged --name dd-agent -h %H -v /var/run/docker.sock:/var/run/docker.sock -v /proc/mounts:/host/proc/mounts:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro -e API_KEY=SECRET datadog/docker-dd-agent
```

**Comment by ineu** [comment]
@lfittl nice tip, thanks.

**Comment by saidakkas** [comment]
@lfittl Thanks. %H made the difference.
