### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/proc/net/dev'

### ISSUE THREAD

**Issue by remh** [DataDog/dd-agent#1175]
On some kernel it looks like /proc/net/dev is unavailable and it's filling up the collector log with that error

```
2014-10-24 18:33:24 CEST | ERROR | dd.collector | checks.network(__init__.py:552) | Check 'network' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 543, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/network.py", line 78, in check
    self._check_linux(instance)
  File "/opt/datadog-agent/agent/checks.d/network.py", line 175, in _check_linux
    proc = open('/proc/net/dev', 'r')
IOError: [Errno 2] No such file or directory: '/proc/net/dev'
```

Last seen on an ubuntu 13.10 x64 that might be running a custom kernel.

**Comment by remh** [comment]
Adding this to triage for 5.3.0 release.

**Comment by elafarge** [comment]
By any chance, does anyone have the Kernel version number. I tried on a stock ubuntu 13.10 x64 VM but I couldn't reproduce the issue there.

**Comment by yannmh** [comment]
The issue occurs, notably, with Grsecurity kernels.

Let's see how it ends when [moving from `netstats` to `ss`](https://github.com/DataDog/dd-agent/issues/1156). cc @olivielpeau

**Comment by remh** [comment]
This is a won't fix for now. Let's reopen if needed.

**Comment by alexbarnsley** [comment]
I know this is closed for now, but thought I would place a workaround here in case anyone needs it. This is based on the workaround in #604 as it has changed slightly:

in `/opt/datadog-agent/agent/checks.d/network.py` replace:
```
        proc = open('/proc/net/dev', 'r')
        lines = proc.readlines()
        proc.close()
```
with:
```
        proc_net_dev, _, _ = get_subprocess_output(["cat", "/proc/net/dev"], self.log)
        lines = proc_net_dev.splitlines()
```
