### ISSUE TITLE
[couchdb] Having a lot of databases results in 500 errors

### ISSUE THREAD

**Issue by MartinDatadog** [DataDog/dd-agent#1188]
When the agent retrieves data from a large number of databases it results in error 500 by CouchDB.
See this customer case: https://datadog.desk.com/agent/case/16222

The agent iterates over all databases: https://github.com/DataDog/dd-agent/blob/master/checks.d/couch.py#L78-L86

A solution to this issue would be a small patch to allow a timeout or allowing the possibility of setting a whitelist.

**Comment by remh** [comment]
Adding this to triage for 5.3.0 release.

**Comment by remh** [comment]
Assigning you this one @hkaj !
Also can you take the opportunity to switch from urllib2 to requests please ?

**Comment by remh** [comment]
Related PR https://github.com/DataDog/dd-agent/pull/1360

**Comment by remh** [comment]
Fixed by https://github.com/DataDog/dd-agent/pull/1360
