### ISSUE TITLE
Integrations should allow interchangeable `server` and `host` directives

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#1223]
Since these are not consistently used across all integrations, I propose that we select one or the other.

Here's a short table on the semantic differences between a host and a server: 
http://en.wikipedia.org/wiki/Host_(network)#Server_and_Host

If we standardize on `server`, there's a bunch of directives already released that documentation show to use `host`. We should fix as many of these as we can, but should also allow the use of `host` for now when we actually mean `server`.

**Comment by remh** [comment]
This is a won't fix. That would break too many things. It's not worth it.
