### ISSUE TITLE
[snmp] config option for non-increasing OID support

### ISSUE THREAD

**Issue by sethrosenblum** [DataDog/dd-agent#1231]
If the snmp library we use encounters non-increasing oids it fails.  This is to prevent from infinite loops during snmp walks.

http://pysnmp.sourceforge.net/faq.html#10

We could add a flag to the snmp config that would allow increasing oids for a given instance:

```
cls.cmd_generator = cmdgen.CommandGenerator()
cls.cmd_generator.ignoreNonIncreasingOid = True
```

**Comment by LeoCavaille** [comment]
@sethrosenblum any reason why not to merge your patch? Could you submit a PR if no :wink: !
