### ISSUE TITLE
[debian-installer] daemon not enabled to start on boot

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#1233]
After installing the agent daemon, if you reboot the machine the agent will not start again. Probably the same problem on Ubuntu.

Also the documentation page does not say a thing about the on boot start of the service.

http://docs.datadoghq.com/guides/basic_agent_usage/deb/

**Comment by Suvitruf** [comment]
Have same problem on ubuntu 14.04

Version 5.6.2

Daemon not enabled to start on boot =/

**Comment by olivielpeau** [comment]
This should be fixed (at least) in the new major version of the Agent (v6, see [repo](https://github.com/DataDog/datadog-agent/)), closing
