### ISSUE TITLE
Agent info doesn't work in latest container image.

### ISSUE THREAD

**Issue by 2bethere** [DataDog/dd-agent#1254]
From customer: agent info command did not work with the latest container image (missing dd-agent entry in /etc/passwd).  I manually entered the dd-agent into /etc/passwd and the info/configcheck/configtest commands worked as expected.

**Comment by LeoCavaille** [comment]
@2bethere could you give more context and info on how to repro ?

**Comment by 2bethere** [comment]
@LeoCavaille @remh Sent e-mail to customer asking for repro steps, cc'ed both of you on thread.

**Comment by remh** [comment]
Closing without more info.
