### ISSUE TITLE
[dogstatsd] events payload does not support utf-8 properly

### ISSUE THREAD

**Issue by oderwat** [DataDog/dd-agent#1256]
I try to extend my own datadog php interface with async events over dd-agent. It works very nice but I can't use utf-8 encoding?

```
2014-12-22 00:03:53 CET | ERROR | dd.dogstatsd | dogstatsd(dogstatsd.py:306) | Error receiving datagram
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/dogstatsd.py", line 294, in start
    aggregator_submit(message)
  File "/home/opt-extra/datadog-agent/agent/aggregator.py", line 508, in submit_packets
    event = self.parse_event_packet(packet)
  File "/home/opt-extra/datadog-agent/agent/aggregator.py", line 498, in parse_event_packet
    raise Exception(u'Unparseable event packet: %s' % packet)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 40: ordinal not in range(128)
```
As far as I can see the related python code is in aggregator.py line 471 (https://github.com/DataDog/dd-agent/blob/master/aggregator.py#L471) which uses "unicode(str)". Looking up the python documentation it says this converts something to unicode and because it has no second parameter it just understands "ascii" as source. I also see that there was a change of this line while implementing the alert functionality. Why?

I think if there is no utf-8 by default one should be able to add an encoding to the metadata part of the message.

**Comment by LeoCavaille** [comment]
Confirmed, thanks for the report @oderwat. Handling utf8 should be the default, we should `decode` the string instead of using `unicode()` or make it an unicode more upstream in that code.
