### ISSUE TITLE
HAProxy count_per_status counting backend/frontend aggregates

### ISSUE THREAD

**Issue by chendo** [DataDog/dd-agent#1261]
With v5.1.1 and `collect_aggregates_only` and `collect_status_metrics` enabled, the agent is including `BACKEND` and `FRONTEND` for the `status:available` count and the `BACKEND` for `status:up` count.

e.g. for the CSV:

```
.backend.10003,FRONTEND,,,0,0,40000,0,0,0,0,0,0,,,,,OPEN,,,,,,,,,1,6,0,,,,0,0,0,0,,,,,,,,,,,0,0,0,,,0,0,0,0,,,,,,,,
.backend.10003,backend-1,0,0,0,0,,0,0,0,,0,,0,0,0,0,UP,1,1,0,0,0,710,0,,1,6,1,,0,,2,0,,0,L4OK,,0,,,,,,,0,,,,0,0,,,,,-1,,,0,0,0,0,
.backend.10003,BACKEND,0,0,0,0,4000,0,0,0,0,0,,0,0,0,0,UP,1,1,0,,0,710,0,,1,6,0,,0,,1,0,,0,,,,,,,,,,,,,,0,0,0,0,0,0,-1,,,0,0,0,0,
```

It's reporting 3 for `status:available` for that service, and 2 for `status:up`.

Is this intended or a bug? I was trying to create a monitor that alerts when the number of `up` backends for a service drops below 1.

**Comment by remh** [comment]
Thanks for the feedback @chendo !

I'm closing this issue as this is the expected behavior.
We report each status as seen from the status page, the available tag is just a convenience we added.

We will reopen if it's too confusing.
Thanks again!
