### ISSUE TITLE
How do I verify dogstatsd is running?

### ISSUE THREAD

**Issue by DBLaw** [DataDog/dd-agent#1268]
The dogstatsd 'status' appears to always claim it is not running, however, info (undocumented for dogstatsd) does not, as far as I can tell, explicitly indicate whether dogstatsd is running.

**Comment by LeoCavaille** [comment]
Merging with #941

**Comment by VynceMontgomery** [comment]
For what it's worth, the documentation referred to is only this (from dogstatsd --help):

Usage: dogstatsd [start|stop|restart|status]

Options:
  -h, --help            show this help message and exit
  -u, --use-local-forwarder

there is also a dogstatsd info not mentioned here.
