### ISSUE TITLE
[system] OpenShift agent pulls host metrics rather than gear

### ISSUE THREAD

**Issue by handigarde** [DataDog/dd-agent#1271]
When running the agent, metrics pulled in by the system check relate to the host, rather than specific to the gear itself. Red Hat has a tool that may help check gear information: https://forums.openshift.com/how-to-check-actual-physical-parameters-of-your-gear

**Comment by LeoCavaille** [comment]
One customer pointed to us https://github.com/kaypro4/openshift-origin-cartridge-monit/tree/master/bin/scripts
Looks like they're using openshift specific commands at gear level.

**Comment by remh** [comment]
Closing this issue as we are going to focus on OpenShift v3 based on the feedback we received from RedHat.
