### ISSUE TITLE
[source] detect python headers installation

### ISSUE THREAD

**Issue by LeoCavaille** [DataDog/dd-agent#1277]
The non-optional source requirements depends on python headers to be installed, otherwise it will fail on those packages and none of the requirements will be installed silently (shown in the install log though).
We should do something along those lines to detect that http://stackoverflow.com/a/4850603

**Comment by olivielpeau** [comment]
The non-optional requirements don't need the python headers (all pure python modules). The optional requirements may need python headers (among other things), the current logic is sufficient for them. Closing
