### ISSUE TITLE
[marathon] 404 when the configured URL has a trailing slash

### ISSUE THREAD

**Issue by bspaans** [DataDog/dd-agent#1278]
The web server powering Marathon apparently doesn't like double slashes, so dd-agent is getting a 404 back when trying to hit the /v2/apps endpoint.

e.g., with this configuration:

```
instances:
- url: "http://10.0.10.1:8080/"
```

The agent reports this error:

```
instance #0 [ERROR]: Exception('Got 404 when hitting http://10.0.10.1:8080/',)
```

This works fine if you leave off the trailing slash.

**Comment by LeoCavaille** [comment]
Thanks for reporting this. Queuing it next, we should add least add something in the YAML comments or ensure that no double slashes are present in the check.
