### ISSUE TITLE
[marathon] KeyError('taskRateLimit',)

### ISSUE THREAD

**Issue by bspaans** [DataDog/dd-agent#1280]
Marathon 0.7 no longer supports the taskRateLimit field, which is causing a problem for the agent:

```
    marathon
    --------
      - instance #0 [ERROR]: KeyError('taskRateLimit',)
      - Collected 1 metric, 0 events & 1 service check
```

Looking at the code for the marathon check, it's not immediately obvious to me why it's trying to access this field, because it seems to be protected by a hasattr check on the requests object. I'm using the default agent on Ubuntu though, so maybe there's a discrepancy there. For reference, here's the Marathon response for one application:

```
{"apps": [
  {"id":"/docker-repo",
  "cmd":null,
  "args":[],
  "user":"root",
  "instances":1,
  "cpus":0.5,
  "mem":2000.0,
  "disk":0.0,
  "executor":"",
  "constraints":[],
  "uris":[],
  "storeUrls":[],
  "ports":[10000],
  "requirePorts":false,
  "backoffFactor":1.15,
  "container":{"type":"DOCKER",
  "volumes":[],
  "docker":{
  "image":"google/docker-registry",
  "network":"BRIDGE",
  "portMappings":[{"containerPort":5000,"hostPort":0,"servicePort":10000,"protocol":"tcp"}]}},
  "healthChecks":[],
  "dependencies":[],
  "upgradeStrategy":{"minimumHealthCapacity":0.5},
  "version":"2015-01-05T09:36:32.989Z",
  "deployments":[],
  "tasksStaged":0,
  "tasksRunning":1,
  "backoffSeconds":1}
]}
```

**Comment by LeoCavaille** [comment]
This one is similar to #1240 (it's fixed & queued for the imminent next release 5.2), feel free to reopen if your problem is actually different.
