### ISSUE TITLE
With performance_schema available in MySQL 5.6 a number of key MySQL metrics can be captured

### ISSUE THREAD

**Issue by ovaistariq** [DataDog/dd-agent#1283]
Performance_schema in MySQL 5.6 provides a number of performance related data points that can be used to add key metrics to Datadog. 
One of the most important metric missing in Datadog is the 95th percentile query response time. This can be computed by querying performance_schema tables.

**Comment by remh** [comment]
Thanks @ovaistariq 
@garnermccloud could you have a look please ?

**Comment by ovaistariq** [comment]
Thanks @remh for adding it to the 5.4.0 milestone.

**Comment by irabinovitch** [comment]
@truthbk  @garnermccloud @ovaistariq  should we close this in favor of #1284? I believe that may supersede this PR based on comments/title.

**Comment by ovaistariq** [comment]
I agree - I think we can close it in favor of #1284

On Fri, Nov 20, 2015 at 12:59 PM, Ilan Rabinovitch <notifications@github.com
> wrote:

> @truthbk <https://github.com/truthbk> @garnermccloud
> <https://github.com/garnermccloud> @ovaistariq
> <https://github.com/ovaistariq> should we close this in favor of #1284
> <https://github.com/DataDog/dd-agent/pull/1284>? I believe that may
> supersede this PR based on comments/title.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DataDog/dd-agent/issues/1283#issuecomment-158522193>.
>



-- 



Ovais Tariq, Lead Reliability Engineer, Lithium
Web: http://www.ovaistariq.net/
Email: me@ovaistariq.net
Skype: ovaistariq

**Comment by truthbk** [comment]
closing in favor of #2116 thanks @ovaistariq !
