### ISSUE TITLE
Port Redis checks from Percona Redis Monitoring Template for Cacti

### ISSUE THREAD

**Issue by ovaistariq** [DataDog/dd-agent#1287]

**Comment by remh** [comment]
Thanks @ovaistariq . Could you provide more info about this please ?
What would be the benefits ?

Are there any metrics that are missing in the current Redis check and that you'd like to see ?

**Comment by ovaistariq** [comment]
My bad I didn't properly look at the list here: http://docs.datadoghq.com/integrations/redis/
I will close this out as all of the ones that percona cacti template provides are provided by dd too.
