### ISSUE TITLE
Invalid metric type GAUGE for postgresql.deadlocks

### ISSUE THREAD

**Issue by tomas-edwardsson** [DataDog/dd-agent#1289]
Looking at graphs from my postgresql servers, I can see that the graphs for postgresql.deadlocks shows the total number of deadlocks since startup. Wouldn't it make more sense to use RATE instead?

https://github.com/DataDog/dd-agent/blob/2bd69dc0ee50eb1d246ad0b958efb415d6ec5c7e/checks.d/postgres.py#L54

**Comment by nate** [comment]
Agreed. This should be RATE instead.
