### ISSUE TITLE
[ssh] Multiple instances not differentiated

### ISSUE THREAD

**Issue by handigarde** [DataDog/dd-agent#1291]
Any metrics sent through the ssh_check.py are not differentiated by instance. If multiple instances are running, the sftp.response_time metric will only be tagged with the host sending the metric: https://github.com/DataDog/dd-agent/blob/master/checks.d/ssh_check.py#L84

**Comment by remh** [comment]
Thanks @handigarde .

Going to work on a fix right now.
It will go out with our 5.2.0 release that is planned for release in the next couple of weeks.

Thanks a lot for the feedback!

**Comment by LeoCavaille** [comment]
@remh update on this one?
