### ISSUE TITLE
[docker] TLS support in docker connection / docker-py

### ISSUE THREAD

**Issue by coulix** [DataDog/dd-agent#1299]
The recommended way of running docker is with TLS support:

    export DOCKER_HOST=tcp://foobar.com:2376
    export DOCKER_TLS_VERIFY=1
    export DOCKER_CERT_PATH=/etc/tls/docker

It seems that there is no way for dd-agent to pick up those env variables, the urllib call therefore fails to establish a connection.

**Comment by coulix** [comment]
Bonus: I can connect to my docker daemon using docker-py:

    from docker import Client, tls

    tls_config = tls.TLSConfig(
        client_cert=('/home/foo/docker/cert.pem',    '/home/foo/docker/key.pem'),
        verify=False
    )
    c = Client(base_url='https://localhost:2376', tls=tls_config)
    print c.containers()


Could `dd-agent` use urllib vs docker-py?

**Comment by LotharSee** [comment]
Thanks @coulix for this detailed explanation!

The main problem is that the current check doesn't support TLS. It shouldn't be hard to add its support to our current code (by using `httplib.HTTPSConnection`) but it's certainly the good moment to switch to `docker-py`.

Concerning the env. variables, it's a wider issue (the Agent doesn't use env. variables in its checks) which should be addressed more globally.

So initially we will have these TCP_VERIFY and CERT_PATH options in the configuration `docker.yaml`.

**Comment by coulix** [comment]
*News*

With the 1.5 release from today Docker exposes a stats endpoint that could maybe be used by data-dog to collect containers metrics.

https://blog.docker.com/2015/02/docker-1-5-ipv6-support-read-only-containers-stats-named-dockerfiles-and-more/

https://github.com/docker/docker/pull/9984

**Comment by remh** [comment]
@LotharSee Changing milestone to 5.4.0
