### ISSUE TITLE
Dogstream aggregator function merging points with the same timestamp despite tags distinction

### ISSUE THREAD

**Issue by yannmh** [DataDog/dd-agent#1304]
```
my.metric 140000 10  mytag=mytag1
my.metric 140000 10  mytag=mytag2
my.metric 140000 10  mytag=mytag3
```
Dogstream parser aggregator would merge these points into one median value point associated with the last tag. We don't consider the tags difference so other tags are lost.
I don't think we should aggregate points with the same timestamp but different tags.

**Comment by remh** [comment]
yeah it's a known issue. Closing in favor of https://github.com/DataDog/dd-agent/issues/807
