### ISSUE TITLE
[snmp] Add support for integer32

### ISSUE THREAD

**Issue by DBLaw** [DataDog/dd-agent#1310]
Working with integer32 types currently throws:

"Unsupported metric type Integer32"

For reference, the MIB being worked with (for Riverbed Stingray) can be seen here - http://issues.opennms.org/secure/attachment/14398/ZXTM-MIB-SMIv2.txt

**Comment by LeoCavaille** [comment]
Fixed for 5.2 release in c89f2d28145ba9f1e4ef5bf59e846099bf13f7c3
