### ISSUE TITLE
Put "skip_event: true" in in the network config example

### ISSUE THREAD

**Issue by LotharSee** [DataDog/dd-agent#1317]
Now that we promote service checks over events for HTTP check, we should keep the default value of skip_event to false (not to break existing systems), but put `skip_event: true` in the example file (but also in https://app.datadoghq.com/monitors#create/network) so that new users won't use the legacy feature.

https://github.com/DataDog/dd-agent/blob/5.1.1/conf.d/http_check.yaml.example#L66-L71
https://github.com/DataDog/dd-agent/blob/5.1.1/conf.d/tcp_check.yaml.example#L29

**Comment by LeoCavaille** [comment]
Definitely, cross-referencing:
https://github.com/DataDog/dd-agent/blob/dda00a72f14112d0e7bdde0f04c80463e5ad639f/checks/network_checks.py#L162-L165

We have to wait for another point release (5.2) with the deprecation. In theory, this is part of a public API, so we would have to release a 6.0 to remove it.
