### ISSUE TITLE
RabbitMQ is missing "consumer_utilization" per queue

### ISSUE THREAD

**Issue by jippi** [DataDog/dd-agent#1323]
In RabbitMQ API for each queue, there is a `consumer_utilization` key, with "percentage" (0...1) of the queue being utilized

Would be nice to get it exposed to DataDog

Please see http://www.rabbitmq.com/blog/2014/04/14/finding-bottlenecks-with-rabbitmq-3-3/

**Comment by remh** [comment]
This was fixed by https://github.com/DataDog/dd-agent/pull/1327 and went out with 5.2.0.
Thanks again @jippi !
