### ISSUE TITLE
[memcached] Can't connect to a memcached server that requires SASL authentication

### ISSUE THREAD

**Issue by fredrik** [DataDog/dd-agent#1333]
There is no option to supply a username and password to authenticate against memcached servers that require authentication. As far I can tell this is because `python-memcached` does not support authentication.

A possible option could be using [python-binary-memcached](https://github.com/jaysonsantos/python-binary-memcached). I have not checked whether the output of its stats call is compatible with `python-memcached`.

**Comment by remh** [comment]
Thanks a lot for the feedback ! It seems that you are right and python-memcached does not support authentication.

We'll try to find a solution but feel free to contribute with a pull request if you feel like it!

**Comment by remh** [comment]
pylibmc might be a better fit https://github.com/lericson/pylibmc

**Comment by dirk** [comment]
Just opened PR #2570 to implement connecting with SASL username/password authentication.

**Comment by masci** [comment]
Let's track this issue on `integrations-core`: https://github.com/DataDog/integrations-core/issues/819
