### ISSUE TITLE
High CPU Load  and intermediate image count failure

### ISSUE THREAD

**Issue by sukrit007** [DataDog/dd-agent#1342]
When there are lot of intermediate docker images, the following line leads to high cpu utilization by docker daemon:

https://github.com/DataDog/dd-agent/blob/5.1.x/checks.d/docker.py#L150

Also the call fails due to timeout .

Can we make intermediate image counter configurable (and turn it off by default ?).  

```
Feb 03 06:32:23 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:23Z" level="info" msg="GET /containers/json?all=False&size=False"
Feb 03 06:32:23 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:23Z" level="info" msg="+job containers()"
Feb 03 06:32:23 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:23Z" level="info" msg="-job containers() = OK (0)"
Feb 03 06:32:23 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:23Z" level="info" msg="GET /containers/json?all=True&size=False"
Feb 03 06:32:23 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:23Z" level="info" msg="+job containers()"
Feb 03 06:32:23 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:23Z" level="info" msg="-job containers() = OK (0)"
Feb 03 06:32:23 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:23Z" level="info" msg="GET /events?since=1422945112&until=1422945143"
Feb 03 06:32:23 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:23Z" level="info" msg="+job events()"
Feb 03 06:32:23 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:23Z" level="info" msg="-job events() = OK (0)"
Feb 03 06:32:26 ip-10-102-169-13.ec2.internal dockerd[21250]: write unix @: broken pipe
Feb 03 06:32:26 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:26Z" level="info" msg="-job images() = ERR (1)"
Feb 03 06:32:26 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:26Z" level="error" msg="Handler for GET /images/json returned error: write unix @: broken pipe"
Feb 03 06:32:26 ip-10-102-169-13.ec2.internal dockerd[21250]: time="2015-02-03T06:32:26Z" level="error" msg="HTTP Error: statusCode=500 write unix @: broken pipe"
```

**Env Info**:
Docker version: ```Docker version 1.4.1, build 5bc2ff8-dirty```
Agent Image: ``datadog/docker-dd-agent:latest  image-id: 8f65aeca1481``

**Comment by LotharSee** [comment]
Hi @sukrit007 ,

Can you try to use the `socket_timeout` option and increase it?
https://github.com/DataDog/dd-agent/blob/5.1.x/conf.d/docker.yaml.example#L14

A big list of images may take longer than the default timeout (5 seconds).
If it doesn't help, please share your collector logs with the `log_level: DEBUG`.

**Comment by sukrit007** [comment]
In theory I think that should get rid of timeouts. However,  this call seems a bit expensive  when used with all parameter. (results in CPU spikes).  Wondering if this can be made configurable. 

 Ideally I would have hoped docker to provide api to publish the counts. But intermediate image layers might not have much relevance. So would prefer to turn it off.

**Comment by sukrit007** [comment]
Is there easy way to install from latest source ? 
I was looking at https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent/source/setup_agent.sh , but it seems to be installing from 5.1.1 tag  or when will this be published to datadog/docker-dd-agent ?

**Comment by LotharSee** [comment]
This will be part of the Agent 5.2, which will be release this month. But the packages and the container will be upgraded together.

But if you can't wait, you can put a modified version of the docker check into `/etc/dd-agent/checks.d`. This will override the default one.

You can copy the check and remove this line https://github.com/DataDog/dd-agent/blob/5.1.x/checks.d/docker.py#L130
This way it will no longer collect images metrics.

**Comment by sukrit007** [comment]
Thanks.  for now I have created a customized docker image and commented the line you mentioned:

https://github.com/totem/dd-agent/blob/master/Dockerfile#L4

Note: I had to modify file:
```
/opt/datadog-agent/agent/checks.d/docker.py
```

CPU load is much better as compared to before. I will investigate to see if i run into anything else. Thanks for quick turnaround.
