### ISSUE TITLE
jvm memory monitoring does not record max and pct_used values

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#1359]
I am monitoring several Tomcat instances and I observed that DataDog does import: 
```
jvm.heap_memory
jvm.non_heap_memory
```
Which is good BUT it does not record the max available values for this, which are essential in order to prevent running out of memory on the JVMS.

Also, it does not record the how much JVM memory is free (percent user or free), which is very important for setting alerts when it goes over 80% or so.

It seems that even if the beam names are identified correctly, it does read only the “commited” value from them, when it should also read the ‘max’ value. Obviously it should compute the usage ratio by using these two values.
```
 Matching: 5/350. Bean name: java.lang:type=Memory - Attribute name: NonHeapMemoryUsage  - Attribute type: javax.management.openmbean.CompositeData
       Matching: 6/350. Bean name: java.lang:type=Memory - Attribute name: HeapMemoryUsage  - Attribute type: javax.management.openmbean.CompositeData
```
Here is some docs:
http://osos.akdenizedas.com.tr/jmx-console/HtmlAdaptor?action=inspectMBean&name=java.lang%3Atype%3DMemory

Based on the please release a fix that also records:
```
jvm.pct_usable_heap_memory
jvm.max_heap_memory
jvm.pct_usable_non_heap_memory
jvm.max_non_heap_memory
```

**Comment by ssbarnea** [comment]
I case it was not clear, these values are supposed to be part of the default JVM beans that are monitored. In fact they are included in the collected list, but because the collection looks only for the committed value, the other values are missing and they are all crucial.

**Comment by remh** [comment]
This was fixed with Agent 5.2.0 it collect all the heap and non heap memory metrics exposed. 
Thanks for the feedback @ssbarnea !

**Comment by ssbarnea** [comment]
Thank you guys! Really glad to head that.

**Comment by ssbarnea** [comment]
It seems that the percent values are not imported, please reopen this bug.

**Comment by yannmh** [comment]
Hi @ssbarnea,

We are actually collecting all JMX metrics related to `HeapMemoryUsage ` and `NonHeapMemoryUsage ` ([here](https://github.com/DataDog/jmxfetch/blob/master/src/main/resources/jmx-2.yaml)). 
Percent values are not exposed on JMX, but it can still be graphed and monitor, querying its definition:
`avg:jvm.heap_memory{*} / avg:jvm.heap_memory_max{*}`

![screenshot 2015-04-16 13 22 03](https://cloud.githubusercontent.com/assets/5708089/7187028/e38467c0-e43b-11e4-9650-73dd701b6e26.png)

Please let me know if this help.

**Comment by ssbarnea** [comment]
Thank you guys! Here is the complete solution
```
avg:jvm.heap_memory{*} by {instance}	 / avg:jvm.heap_memory_max{*} by {instance}
```
This tricks the monitor the percent of memory usage for each JVM instance. If you do not include this it will SUM all the instances, and you will get something that is not very useful.

**Comment by MartinDatadog** [comment]
Hi @ssbarnea 
Thank you for providing the full solution in your last message.
Your request for a KB article has been logged.

Thank you!
Martin
