### ISSUE TITLE
No way to force SNMPv1

### ISSUE THREAD

**Issue by slushpupie** [DataDog/dd-agent#1374]
I have a device that only speaks SNMPv1, if you attempt SNMPv2 it simply ignores it.   pysnmp supports this by setting mpModel=0 with the community, but the agent does not have a way to set this.

**Comment by remh** [comment]
Thanks a lot for the feedback @slushpupie ! 
We'll try to add this by 5.3.0 but would you like to open a pull request to implement this feature ?
