### ISSUE TITLE
varnish4 stats broken since 1:5.2.0-1

### ISSUE THREAD

**Issue by arosenhagen** [DataDog/dd-agent#1382]
I just upgraded datadog and varnish stats stopped working. I guess its something with ```use_xml``` and broken xml syntax.

dd.collector | checks.varnish(__init__.py:556) | Check 'varnish' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 547, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/varnish.py", line 95, in check
    self._parse_varnishstat(varnishstat_path, use_xml, tags)
  File "/opt/datadog-agent/agent/checks.d/varnish.py", line 181, in _parse_varnishstat
    p.Parse(output, True)
ExpatError: not well-formed (invalid token): line 1, column 0

**Comment by LeoCavaille** [comment]
Hi @arosenhagen, thanks for reporting this.
This is fixed by #1384, and will be released as part of a bugfix release 5.2.1 very soon. Sorry for the trouble.

**Comment by remh** [comment]
Fixed by https://github.com/DataDog/dd-agent/pull/1384
