### ISSUE TITLE
[zookeeper] bytes_outstanding metric returns number of requests served by zk node

### ISSUE THREAD

**Issue by handigarde** [DataDog/dd-agent#1383]
User checking through the ZooKeeper check noticed that the bytes_outsanding metric the DD agent is scrapping is not bytes, but rather the number of inflight requests currently being serviced by the ZK node.

https://github.com/apache/zookeeper/blob/ca480231e1bdcbe6beda9142766fc3caa2031cd8/src/java/main/org/apache/zookeeper/server/ServerStats.java#L104

https://github.com/apache/zookeeper/blob/ca480231e1bdcbe6beda9142766fc3caa2031cd8/src/java/main/org/apache/zookeeper/server/ZooKeeperServer.java#L740

**Comment by remh** [comment]
Thanks a lot @handigarde looks like you're right.
