### ISSUE TITLE
Updating Jenkins integration to have it work with newer Jenkins integration

### ISSUE THREAD

**Issue by MartinDatadog** [DataDog/dd-agent#1385]
The dd-agent jenkins.py expects the build folder to have timestamp format.
And is looking for all folders that match job_dir + builds + *_*
So it would find all builds where the build folder looks like :

2014-07-09_20-26-08

2014-07-09_20-41-05

2014-07-09_20-56-05

2014-07-09_21-11-06

2014-07-14_17-11-08

However, the 1.598 version of jenkins has builds as
integers, and not timestamps. So the build folder looks like:

drwxr-xr-x 2 jenkins jenkins 4096 Jul 9 2014 *1*/

drwxr-xr-x 2 jenkins jenkins 4096 Jul 21 2014 *10*/

drwxr-xr-x 2 jenkins jenkins 4096 Nov 6 20:31 *100*/

drwxr-xr-x 2 jenkins jenkins 4096 Nov 7 20:21 *101*/

drwxr-xr-x 2 jenkins jenkins 4096 Nov 17 13:46 *102*/

And as a result, the jenkins.py doesn't find anything to report.

There was a change in how jenkins stored their builds
(from date format to integer format), and have included a "legacyids" file
in the builds directory, which does the mapping between the two formats,
and looks like:

2014-07-09_20-26-08 1

2014-07-09_20-41-05 2

2014-07-09_20-56-05 3

2014-07-09_21-11-06 4

2014-07-14_17-11-08 5

The dd-agent jenkins.py needs to be updated to work with
the change in the jenkins build number storage.

**Comment by LeoCavaille** [comment]
Why was this closed @MartinDatadog ?
Referencing this gist https://gist.github.com/anonymous/118ad5c133d7387c69f9

**Comment by MartinDatadog** [comment]
Opened a card in our trackboard as per requested, but keeping this open could help customers!

**Comment by biyanisuraj** [comment]
Is this integration fixed ?

**Comment by remh** [comment]
@biyanisuraj this is fixed by https://github.com/DataDog/dd-agent/pull/1442

This will go out with Agent 5.3.0 which is due in around 3 weeks from now.

You can replace your /opt/datadog-agent/agent/checks.d/jenkins.py file by this one if you want to try it before it gets released

https://raw.githubusercontent.com/DataDog/dd-agent/master/checks.d/jenkins.py
