### ISSUE TITLE
http check only shows one certificate check - I can't select the other one.

### ISSUE THREAD

**Issue by darron** [DataDog/dd-agent#1386]
I have 2 certificates to check in my config:

https://gist.github.com/darron/7342c52299c4641a1c02

Both show up as being checked in the dd-agent info:

```
    http_check
    ----------
      - instance #0 [OK]
      - instance #1 [OK]
      - Collected 2 metrics, 0 events & 5 service checks
```

But I can only set up a monitor for one of them - I can never be alerted on the second one. Selecting ssl cert only ever returns the octohost_new cert:

http://shared.froese.org/2015/dvziy-14-30.jpg
http://shared.froese.org/2015/4n960-14-30.jpg

Should I be able to monitor any of them?

Sorry - this may need to actually be in dogweb - I may have misfiled.

**Comment by wickett** [comment]
I am having a similar experience.
