### ISSUE TITLE
[docker] container metrics support from stats endpoint

### ISSUE THREAD

**Issue by adzuci** [DataDog/dd-agent#1392]
@coulix mentioned docker stats in a previous issue: https://github.com/DataDog/dd-agent/issues/1299#issuecomment-74011728, but I thought I would open a new issue.

It looks like we could access resource stats in a similar way to how we access SizeRw from /containers/json here: [docker.py#L242](https://github.com/DataDog/dd-agent/blob/master/checks.d/docker.py#L242)

From the [API docs](https://docs.docker.com/v1.5/reference/api/docker_remote_api_v1.17/#get-container-stats-based-on-resource-usage), at least network is now available from the api when it wasn't easily available elsewhere before.

I'm not sure if this warrants changing what's currently taken from cgroups or just adding an api call similar to `_get_cgroup_file` except for `/containers/(id)/stats` from `_get_json`

**Comment by remh** [comment]
Thanks for the feedback @adzuci !
@LotharSee Can you have a look please ?

**Comment by LotharSee** [comment]
Sure I will!

**Comment by ssanderson** [comment]
The thing that will make this trickier than it might otherwise be is that the stats API is streaming-only in v1.17 (corresponding to docker version 1.5).  You can hack around that fact by just getting a single message and then severing the connection though.

https://github.com/docker/docker/pull/10766 will provide what's likely to be the right way to do this if it lands.

**Comment by adzuci** [comment]
@LotharSee Any thoughts on whether doing this is easy enough or when it makes sense to do it?

**Comment by coulix** [comment]
Docker #10766 was merged, any news on when we can we expect proper docker monitoring in Datadog?

**Comment by remh** [comment]
This won't happen.
Using the statsd endpoint is slow and not scalable.

All the metrics can be collected from the cgroups and agent 5.5.0 is adding most of them, including network metrics, memory limit metrics and sizeRw
