### ISSUE TITLE
http_check - define success

### ISSUE THREAD

**Issue by rmoriz** [DataDog/dd-agent#1403]
Sometimes you need to check the negativity of a request, e.g. to see if a login form appears using HTTP 403 - this currently fails because the check uses `requests.exceptions.HTTPError` and there is no configuration option to customize it.

I wish there was an option to specify the explicit HTTP return code per http_check.

**Comment by remh** [comment]
Thanks for the feedback @rmoriz this is an interesting use case.

@yannmh could you try to see what would be required to implement this ?
