### ISSUE TITLE
Cannot start dd-agent

### ISSUE THREAD

**Issue by gavinengel** [DataDog/dd-agent#1405]
I'm having trouble with the dd-agent.  It is failing to start on my Fedora release 21.  Here is what I see when I try to start:  http://pastebin.com/j95KST3K

Any thoughts?

**Comment by remh** [comment]
Sorry @gavinengel . This message got lost. Can you reach out our support team (support _at_ datadoghq.com ) please ?

It looks like it's related to the fact that the agent is unable to determine a valid hostname on your machine
```
Mar 01 10:37:37 localhost.localdomain dd.collector[3536]: CRITICAL (util.py:219): Unable to reliably determine host name. You can define one in datadog.conf or in your hosts file
```

You should make sure that your Operating System has a valid hostname.

Thanks!

**Comment by JasonGhent** [comment]
I, too, ran into this. I was using the hostname `localhost`, but it seems that does not qualify as "valid".

**Comment by remh** [comment]
@JasonGhent Thanks for the feedback.
We do not consider localhost as valid because you could have multiple hosts with that hostname.
As a result their metrics would be blended together randomly in the backend as we use the hostname to uniquely identify a host.

**Comment by gavinengel** [comment]
Hi again :-)  I think what would have satisfied me is a simple error message "Cannot use 'localhost' for hostname' directly from dd-agent.  I would have simply changed my hostname, no big deal.  Digging through the logs was frustrating though.
