### ISSUE TITLE
[kafka] JMX config is obsolete for 0.8.2 

### ISSUE THREAD

**Issue by garnermccloud** [DataDog/dd-agent#1420]
It looks like Kafka 0.8.2 changed the Mbean names so the default kafka.yaml doesn't work:
https://archive.apache.org/dist/kafka/0.8.2.0/RELEASE_NOTES.html
https://issues.apache.org/jira/browse/KAFKA-1723

**Comment by LeoCavaille** [comment]
Cross-referencing #1424

**Comment by remh** [comment]
Fixed by https://github.com/DataDog/dd-agent/pull/1438
