### ISSUE TITLE
[docker] support tagging for events

### ISSUE THREAD

**Issue by robparrott** [DataDog/dd-agent#1421]
Despite the documentation, the docker agent module does not include tags when creating events:

    https://github.com/DataDog/dd-agent/blob/master/checks.d/docker.py#L321-L328

**Comment by LeoCavaille** [comment]
Hey @robparrott, thanks for opening this issue.
Can you:
* indicate what you're referring to by _the documentation_?
* tell us what kind of tags you'd like to see in docker events?

**Comment by ejholmes** [comment]
:+1: for this.

Events pertaining to a container should be tagged with the same tags that metrics include. This would probably require keeping an internal mapping of `container id -> tags` for every container and pruning list when containers die.
