### ISSUE TITLE
Sign our RPMs

### ISSUE THREAD

**Issue by alq666** [DataDog/dd-agent#144]
Our DEBs are signed with http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x226AE980C7A7DA52. Do the same for RPMs.

**Comment by yannmh** [comment]
@elafarge do you know what's the status ? Is it still maintained for the 5.5.0 agent release ?

**Comment by elafarge** [comment]
@yannmh Yep, signing is currently enabled. We just need to put the "real" key on CircleCI and we're done.

**Comment by elafarge** [comment]
Oh and I don't have that key.

**Comment by remh** [comment]
Going out with our 5.5.0 release.
