### ISSUE TITLE
[tests] review of all our integration tests

### ISSUE THREAD

**Issue by degemer** [DataDog/dd-agent#1458]
@hkaj :
- [ ] `btrfs.py`
- [x] `fluentd.py` - https://github.com/DataDog/dd-agent/pull/1574
- [x] ~~`lighttpd.py` - https://github.com/DataDog/dd-agent/pull/1473~~
- [ ] `mesos_slave.py`
- [ ] `network.py`
- [ ] `nginx.py`
- [ ] `redisdb.py`
- [ ] `sqlserver.py`
- [ ] `tcp_check.py`

@LeoCavaille :
- [ ] `cacti.py`
- [ ] `couchbase.py`
- [ ] `jenkins.py`
- [ ] `kafka_consumer.py`
- [ ] `mesos.py`
- [ ] `mongo.py`
- [ ] `ntp.py`
- [ ] `postfix.py`
- [x] ~~`rabbitmq.py` - https://github.com/DataDog/dd-agent/pull/1472~~
- [ ] `riakcs.py`
- [ ] `varnish.py`

@degemer :
- [x] ~~`couch.py` - https://github.com/DataDog/dd-agent/pull/1462~~
- [x] `go_expvar.py` - https://github.com/DataDog/dd-agent/pull/1491
- [x] ~~`haproxy.py` - https://github.com/DataDog/dd-agent/pull/1466~~
- [x] ~~`http_check.py` - https://github.com/DataDog/dd-agent/pull/1467~~
- [x] `postgres.py` - https://github.com/DataDog/dd-agent/pull/1415 (thanks @LeoCavaille)
- [x] ~~`process.py` - https://github.com/DataDog/dd-agent/pull/1470~~
- [x] `riak.py` - https://github.com/DataDog/dd-agent/pull/1499
- [x] ~~`system_core.py` - https://github.com/DataDog/dd-agent/pull/1485~~
- [ ] `vsphere.py` - it's a WON'T FIX for now
- [ ] `win32_event_log.py`

@remh :
- [x] `elastic.py` - https://github.com/DataDog/dd-agent/pull/1487
- [ ] `etcd.py`
- [x] ~~`gearmand.py`\- https://github.com/DataDog/dd-agent/pull/1476~~
- [ ] `gunicorn.py`
- [ ] `hdfs.py`
- [ ] `kyototycoon.py`
- [x] `mcache.py` - https://github.com/DataDog/dd-agent/pull/1490
- [ ] `ssh_check.py`
- [ ] `teamcity.py`
- [ ] `tokumx.py`

@yannmh :
- [ ] `docker.py`
- [ ] `marathon.py`
- [x] ~~`activemq_xml.py` - https://github.com/DataDog/dd-agent/pull/1606~~
- [x] ~~`apache.py` - https://github.com/DataDog/dd-agent/pull/1474~~
- [x] ~~`directory.py` - https://github.com/DataDog/dd-agent/pull/1463~~
- [x] ~~`iis.py` - https://github.com/DataDog/dd-agent/pull/1484~~
- [x] ~~`mysql.py` - https://github.com/DataDog/dd-agent/pull/1471~~
- [x]  ~~`nagios.py` - https://github.com/DataDog/dd-agent/pull/1493~~
- [x]  ~~`snmp.py` - https://github.com/DataDog/dd-agent/pull/1477~~
- [x]  `supervisord.py` - https://github.com/DataDog/dd-agent/pull/1747
- [x]  ~~`windows_service.py`\- https://github.com/DataDog/dd-agent/pull/1481~~
- [x]  ~~`wmi_check.py` - https://github.com/DataDog/dd-agent/pull/1502~~
- [x]  ~~`zk.py` - https://github.com/DataDog/dd-agent/pull/1488~~

**Comment by remh** [comment]
Won't be completed by 5.3.0 let's finish this for 5.4.0

**Comment by yannmh** [comment]
Moving to 5.5.0

**Comment by degemer** [comment]
Not finished, but the initial goal is attained: way more checks have integration tests than before.
Closing, checks are now in https://github.com/DataDog/integrations-core.
