### ISSUE TITLE
unable to retrieve iostat

### ISSUE THREAD

**Issue by hephaistos75** [DataDog/dd-agent#1460]
Hello,

I'm so sorry for my bad english. I will try to explain you my issue.
I can't see Disk I/O on datadog. 
I have try to execute the following command: "iostat -d 1 2 -x -k" with root privilege and I can see detail.
However when I try to execute this one with dd-agent privilege i can't see information.

OS: -debian-7.8
Python Version: 2.7.9

**Comment by yannmh** [comment]
Hey @hephaistos75. 

I'm sorry for the inconvenience. Can you contact our Support Team via email at support@datadoghq.com with your logs and some additional information about what you are trying to achieve please ?

Thanks

**Comment by remh** [comment]
Closing as we don't have enough data to investigate this issue.
