### ISSUE TITLE
[postgres] make the relation metrics aware of schemas

### ISSUE THREAD

**Issue by clofresh** [DataDog/dd-agent#1496]
Currently the postgres check can collect relation metrics from pg_stat_user_tables and pg_stat_user_indexes, but they don't specify the schema, so it could mixing up be metrics from tables with the same name in different schemas. I'd like to update the check to tag the relation metrics by schema as well as support specifying the schema in config.

So if you have the following db:

```
create schema prod;
create table prod.foo(id int);

create schema staging;
create table staging.foo(id int);
```

And you're running the old check:

```
    relations:
        - foo
```

You'd submit two rows of data, but the same set of tags, so one of the metrics would win.

In the new version, you'd get two rows of data, but one tagged with `schema:prod` and `schema:staging`.

You'd also be able to specify the schema:
```
    relations:
        - prod.foo
```
Which would only query for the prod schema's foo table.

**Comment by yannmh** [comment]
Thanks for the detailed explanations @clofresh.

We didn't have time to do it for the 5.4.0 agent release. I am pushing back to 5.5.0.

**Comment by yannmh** [comment]
Fixed with https://github.com/DataDog/dd-agent/pull/1771.

Thanks @kostas0
