### ISSUE TITLE
(Much) better mysql metrics

### ISSUE THREAD

**Issue by alq666** [DataDog/dd-agent#152]
Pre-baked from http://www.percona.com/doc/percona-monitoring-plugins/cacti/mysql-templates.html

@conorbranagan came up during a conversation with a customer today. There's plenty of work to do on the collection side, but for rev2 of the mysql prebaked dash, this is an excellent source.

**Comment by remh** [comment]
Not on track for 5.2, moving milestone to 5.3.0

**Comment by remh** [comment]
Changing milestone to 5.4.0 @garnermccloud

**Comment by truthbk** [comment]
Should be addressed by #2116

**Comment by truthbk** [comment]
As mentioned earlier, we have vastly expanded the metrics catalog in #2116. Closing for now, if other features are required we can open them in due time. Thanks everyone for your input.
