### ISSUE TITLE
Apache integration instructions out of date

### ISSUE THREAD

**Issue by rubymorillo** [DataDog/dd-agent#1531]
Step 2 of the configuration instructions [in the documentation](http://docs.datadoghq.com/integrations/apache/), which say to edit the `/etc/dd-agent/datadog.conf`, is out of date. Doing so spits out an error when you run the 'info' command that says edits shouldn't be made to the datadog.conf file. 

The correct integration instructions are given below (which I was only able to access in a pop-up window at Integrations>Apache, as it was showing me the log wasn't receiving any data): 

-  Configure the Agent to connect to Apache
-  Edit `conf.d/apache.yaml`
```
init_config:

instances:
    -   apache_status_url: http://example.com/server-status?auto
        # apache_user: example_user
        # apache_password: example_password
        tags:
            -   instance:foo
```
Etc etc.

It might also be helpful to specify that `apache.yaml.example` should be renamed `apache.yaml` in order for it to work.

**Comment by remh** [comment]
Thanks a lot for the feedback @rubymorillo !
You are totally right, I'm going to open a ticket in our documentation repo.

**Comment by remh** [comment]
See https://github.com/DataDog/documentation/pull/372
