### ISSUE TITLE
latest datadog installer gives "setup wizard ended prematurely"

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#1551]
I tried to use the latest datadog installer to upgrade datadog agent on a windows machine and at the end it does finish with "setup wizard ended prematurely" error.

I did run the installer by double clicking it because being an upgrade I assumed that there is no need to provide the command line parameters.

https://www.dropbox.com/s/snokoaq5suitppp/Screenshot%202015-04-17%2019.26.10.png?dl=0

Windows 2008 Server SP1 x86

**Comment by ssbarnea** [comment]
Just to make it clear: now I lost the agent on the Windows machine and I cannot get it back. Any hints on where to look for the log regarding the failed installer?

**Comment by yannmh** [comment]
Hi @ssbarnea,

I've tried to reproduce the issue from a Windows 2008 R2 SP1 machine, with no success. Could you please check the md5sum of your installer ? It should be `312be61277ddb0ab13385dc99ea58fda`.

Installation logs are available via Windows Event Viewer tool (`eventvwr` from a Windows command prompt), in `Windows Logs` -> `Application` section. 

In the meantime, you may want to reinstall the [5.2](http://ddagent-windows-stable.s3.amazonaws.com/ddagent-cli-5.2.0.msi) agent release.

We are sorry for the inconvenience being caused.

**Comment by remh** [comment]
Closing as we didn't get more info.
