### ISSUE TITLE
[osx] mknod error during installation

### ISSUE THREAD

**Issue by mkb** [DataDog/dd-agent#1584]
Running the most recent installation script on OSX gives the following error...

    mknod: node type must be 'b' or 'c' or 'w'.

This appears to be caused by line 16: https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent/source/install_agent.sh#L16

`p` is not a valid device type on MacOS Yosemite

**Comment by remh** [comment]
Hi @mkb , thanks for the feedback !

This script is not the installation script for MacOS, it's only intendend for Debian/Ubuntu/RHEL/Centos/Fedora/Amazon Linux.

On Mac OS you want to run this script instead:
```
DD_API_KEY=YOUR_API_KEY bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh)"
```

You'll find more details here:
https://app.datadoghq.com/account/settings#agent/mac

I'm closing this issue, feel free to reopen or to contact our support team if you have any other issue using the agent.

Thanks again!

**Comment by ArashMehraban** [comment]
Is there  a way to download the AWS package in Mac to upload it somewhere else where potentially that place does not allow outside of network access? Why is it not letting me download what I want?
