### ISSUE TITLE
External DogStatsD

### ISSUE THREAD

**Issue by sschepens** [DataDog/dd-agent#1591]
I'm trying to make a setup where multiple instances report to a single DogStatsD server, is this possible?
I found configurations `statsd_forward_host` and `statsd_forward_port` but they suggest that the server should be a StatsD not a DogStatsD, and this options make DogStatsD start all the same but forward all requests, wouldn't it be better to allow configuration of DogStatsD server? After all there's also a docker image to lift only a DogStatsD server.

**Comment by LeoCavaille** [comment]
Hey @sschepens. I am not sure to get exactly what is your setup.
What are the _instances_ you're talking about? agent instances? dogstatsd instances?

dogstatsd aggregates the data and then flushes it to [this URL](https://github.com/DataDog/dd-agent/blob/5.3.2/datadog.conf.example#L95-L98), which is by default the local forwarder. You could target a unique forwarder for the whole cluster if that the case.
Another possibility is to keep the local flushing to the forwarder but set up one agent as a proxy for all the other forwarder, see [those instructions](https://github.com/Datadog/dd-agent/wiki/Proxy-Configuration).
Last, you can allow non-local traffic on a dogstatsd instance, that is receiving payloads from other hosts than localhost, this can be setup [here](https://github.com/DataDog/dd-agent/blob/5.3.2/datadog.conf.example#L57-L62).

Let me know if that answers your question.

**Comment by LeoCavaille** [comment]
Closing, feel free to add more details and reopen.
