### ISSUE TITLE
[Core] Hardcoded no_proxy setting causes problems for EC2 metadata

### ISSUE THREAD

**Issue by mikael-lindstrom** [DataDog/dd-agent#1594]
Following this pull request: https://github.com/DataDog/dd-agent/pull/1518
`no_proxy` is now hardcoded to `127.0.0.1,localhost` in `dogstatsd.py` and `emitter.py`

Since this is set in the environment it affects fetching of EC2 metadata on AWS as that is fetched from `169.254.169.254`. If `http_proxy` is set, these requests will be sent through the proxy and return incorrect metadata.

This should be changed to respect addresses set in `no_proxy` and only append `127.0.0.1,localhost` if they are missing.

**Comment by LeoCavaille** [comment]
:+1: thanks for reporting.
