### ISSUE TITLE
No data from mysql and php-fpm integrations

### ISSUE THREAD

**Issue by peeyush81** [DataDog/dd-agent#1598]
Hello,

I installed mysql and php-fpm integration but I am not getting any graphs/data on dd dashboard.

I did dd-agent info and I am getting this error: 

  Checks
  ======

   php_fpm
    -------
      - initialize check class [ERROR]: 'while parsing a block mapping\n  in "<byte string>", line 5, column 5\ndid not find expected key\n  in "<byte string>", line 24, column 7'
    mysql
    -----
      - initialize check class [ERROR]: 'while parsing a block mapping\n  in "<byte string>", line 4, column 5\ndid not find expected key\n  in "<byte string>", line 11, column 7'

Can you please let us know how to fix it ?

Thanks

**Comment by vincentcox** [comment]
how did you fix it?
