### ISSUE TITLE
Agent won't start on Ubuntu 14.04

### ISSUE THREAD

**Issue by chriskinsman** [DataDog/dd-agent#1601]
I have it running on other boxes but on this one I get:
- Stopping Datadog Agent (stopping supervisord) datadog-agent                                     [ OK ] 
- Starting Datadog Agent (using supervisord) datadog-agent                                        [fail] 
  datadog-agent:collector          RUNNING   pid 868, uptime 0:00:11
  datadog-agent:dogstatsd          RUNNING   pid 866, uptime 0:00:11
  datadog-agent:forwarder          FATAL     Exited too quickly (process log may have details)
  datadog-agent:jmxfetch           EXITED    May 07 01:01 AM
  Datadog Agent (supervisor) is NOT running all child processes
- Stopping Datadog Agent (stopping supervisord) datadog-agent                                     [ OK ] 

Doing an info I get:
# 
# Collector (v 5.3.2)

  Collector is not running.
  You can get more details in the logs:
    <stderr>, /var/log/datadog/collector.log, syslog:/dev/log
# 
# Dogstatsd (v 5.3.2)

  Dogstatsd is not running.
  You can get more details in the logs:
    <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

Traceback (most recent call last):
  File "/usr/bin/dd-forwarder", line 567, in <module>
    sys.exit(main())
  File "/usr/bin/dd-forwarder", line 557, in main
    return ForwarderStatus.print_latest_status()
  File "/opt/datadog-agent/agent/checks/check_status.py", line 238, in print_latest_status
    message = module_status.render()
  File "/opt/datadog-agent/agent/checks/check_status.py", line 140, in render
    ] + ["", ""]
  File "/opt/datadog-agent/agent/checks/check_status.py", line 647, in body_lines
    if self.proxy_data:
AttributeError: 'ForwarderStatus' object has no attribute 'proxy_data'

Trying to track down that last error not finding anything in searches...

Looking at the forwarder.log I see:

2015-05-07 01:09:39 UTC | INFO | dd.forwarder | root(ddagent.py:121) | Done with custom emitters
2015-05-07 01:09:39 UTC | WARNING | dd.forwarder | forwarder(ddagent.py:166) | You are a Datadog user so we will send data to https://app.datadoghq.com
2015-05-07 01:09:39 UTC | ERROR | dd.forwarder | forwarder(ddagent.py:462) | Socket error [Errno 98] Address already in use. Is another application listening on the same port ? Exiting
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/ddagent.py", line 451, in run
    http_server.listen(self._port, address = self._agentConfig['bind_host'])
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/tornado/tcpserver.py", line 117, in listen
    sockets = bind_sockets(port, address=address)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/tornado/netutil.py", line 104, in bind_sockets
    sock.bind(sockaddr)
  File "/opt/datadog-agent/embedded/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Running sockstat -l on the box I don't see any sockets listening on any port so not sure what the issue is...

**Comment by chriskinsman** [comment]
Found a process that wasn't shutting down when I did a datadog-agent stop.  Killed it and then it started fine

**Comment by aioue** [comment]
had to delete `/opt/datadog-agent/run/dogstatsd.pid` and kill another dd process.

**Comment by noushi** [comment]
Same here, happened on 3 different servers, a little hand holding got things back on track.

```shell
root@xxxx:~# ps aux |grep datado[g]
dd-agent  9810  0.0  0.0 104252 16624 ?        Ss    2015  12:10 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/bin/supervisord -c /etc/dd-agent/supervisor.conf --pidfile /opt/datadog-agent/run/datadog-supervisord.pid
dd-agent  9814  0.1  0.0 210528 26344 ?        Sl    2015 103:30 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/dogstatsd.py --use-local-forwarder
dd-agent  9815  0.1  0.0 150832 28228 ?        S     2015  94:43 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/ddagent.py

root@xxxx:~# cat /opt/datadog-agent/run/datadog-supervisord.pid
cat: /opt/datadog-agent/run/datadog-supervisord.pid: No such file or directory

root@xxxx:~# echo 9810 >/opt/datadog-agent/run/datadog-supervisord.pid

root@tiefighter25:~# service datadog-agent stop
 * Stopping Datadog Agent (stopping supervisord) datadog-agent                                                                                          [ OK ] 

root@xxxx:~# ps aux |grep datado[g]

root@xxxx:~# service datadog-agent start
 * Starting Datadog Agent (using supervisord) datadog-agent                                                                                             [ OK ] 
```

**Comment by antonbabenko** [comment]
I had same issue before I found out that `sd-agent` (serverdensity agent) was using same port.

**Comment by sopitz** [comment]
yeah, the sd-agent was the problem for me too! Thanks for the tipp @antonbabenko!

**Comment by scipilot** [comment]
I just had this same problem, and it turned out to be dd-agent.py itself which I had to kill. I'm not sure how it got into the state of having a duplicate dog. The agent has been working fine on a Centos box for about two years, then suddenly stopped reporting, and failed to reboot. The forwarder logs was saying the port was in use, but it was a dd-agent using the port. After killing the process and doing an agent restart, it's working again.

**Comment by masci** [comment]
thanks for the feedback everyone, closing this as it seems solved
