### ISSUE TITLE
Lots of MySQL connection errors in syslog

### ISSUE THREAD

**Issue by Ornitier** [DataDog/dd-agent#1604]
Hi all,

Looking at my syslog, found a lot of MySQL errors like this one, one every 20 seconds:

    May  7 19:32:20 mysqld [Warning] Aborted connection 42000 to db: 'unconnected' user: 'datadog' host: 'localhost' (Unknow error)

I found that this error can pop if your connection to MySQL is not well closed ([here](https://dev.mysql.com/doc/refman/5.0/en/communication-errors.html)) and it looks like it is the case in checks.d/mysql.py.

Can you add a close to the script?

Thank you!

**Comment by remh** [comment]
Thanks a lot @Ornitier !

@garnermccloud can you have a look on this one please

**Comment by truthbk** [comment]
This should be addressed or at least mitigated by the changes to #2116
