### ISSUE TITLE
[Flake8] list of errors

### ISSUE THREAD

**Issue by degemer** [DataDog/dd-agent#1608]
Number of occurrences - error code
- [x]   2 - F403 - @degemer
- [x]   3 - E211 - @remh
- [x]   3 - E711 - @remh
- [x]   3 - F811 - @remh
- [x]   3 - W292 - @remh
- [x]   4 - E112 - @LeoCavaille
- [x]   4 - E271 - @degemer
- [x]   4 - E272 - @degemer
- [x]   4 - E301 - @degemer
- [x]   7 - E111 - @LeoCavaille
- [x]   7 - E125 - @remh
- [x]   7 - E702 - @degemer
- [x]   9 - E121 - @remh
- [x]   9 - E262 - @degemer
- [x]  10 - W391 - @degemer
- [x]  11 - E222 - @degemer
- [x]  12 - W291 - @degemer
- [x]  16 - E202 - @degemer
- [x]  19 - E123 - @LeoCavaille
- [x]  19 - E721 - @degemer
- [x]  20 - E201 - @degemer
- [x]  20 - W293 - @degemer
- [x]  23 - E122 - @degemer
- [x]  23 - E225 - @degemer
- [x]  25 - E124 - @degemer
- [x]  26 - E502 - @degemer
- [x]  30 - E126 - @degemer
- [x]  31 - F841 - local variable name is assigned to but never used @remh
- [x]  36 - E701 - multiple statements on one line (colon) @hkaj
- [x]  43 - E221 - multiple spaces before operator @hkaj
- [x]  59 - E127 - continuation line over-indented for visual indent - @degemer
- [ ]  59 - E265 - block comment should start with ‘# ‘
- [x]  66 - F401 - module imported but unused - @degemer
- [ ] 101 - E303 - too many blank lines (3)
- [ ] 103 - E241 - multiple spaces after ‘,’
- [ ] 107 - E226 - missing whitespace around arithmetic operator
- [ ] 121 - E261 - at least two spaces before inline comment
- [ ] 139 - E251 - unexpected spaces around keyword / parameter equals
- [ ] 153 - E302 - expected 2 blank lines, found 0
- [ ] 170 - E203 - whitespace before ‘:’
- [ ] 209 - E231 - missing whitespace after ‘,’, ‘;’, or ‘:’
- [ ] 245 - E128 - continuation line under-indented for visual indent

**Comment by remh** [comment]
Closing this. The remaining errors are purely stylistic and would put too many constraints. Great job @degemer @hkaj @LeoCavaille
