### ISSUE TITLE
[core] [ganglia] Move Ganglia integration to separate agent check

### ISSUE THREAD

**Issue by talwai** [DataDog/dd-agent#1632]
Ganglia integration logic should be moved out of [the core](https://github.com/DataDog/dd-agent/blob/62a8f6ef0ce7fccd9432e0f6b03ad4963ee6529a/checks/ganglia.py) and into a new-style `AgentCheck` under `checks.d`.

 Ref: [Writing an Agent Check](http://docs.datadoghq.com/guides/agent_checks/)

**Comment by remh** [comment]
This is a won't fix as the Ganglia integration is deprecated.
