### ISSUE TITLE
MySQL Max Connections

### ISSUE THREAD

**Issue by ProTip** [DataDog/dd-agent#1646]
Hello,

This was very confusing for me before I looked into the code:
https://github.com/DataDog/dd-agent/blob/master/checks.d/mysql.py#L20

MySQL has a system variable called max_connections AND a status variable called max_used_connections. This name change threw me off a bit.

**Comment by truthbk** [comment]
@ProTip thanks for pointing this out - we should definitely clear this up.

**Comment by truthbk** [comment]
Unfortunately, due to backward incompatibilities that would arise for our customers should we change the metric name, we will be leaving this untouched. We will make sure the code/documentation reflect the true nature of each metric name. Thanks again for the input @ProTip
