### ISSUE TITLE
Visibility lost under saturated connections scenario

### ISSUE THREAD

**Issue by ProTip** [DataDog/dd-agent#1647]
Hello,

It seems that the agent may be making a connection to the server during each check instead of re-using a connection.  Unfortunately this has a side effect of causing visibility loss if max connections is hit because the agent can't re-connect.  Not sure if it fits with the agent architecture, but I might recommend a checker that stays running and keeps the connection open.

**Comment by remh** [comment]
Hi @ProTip thanks for the feedback, can you give us more information about what's happening ? What check especifically are you talking about ? 

Also what version of the agent are you using ?

**Comment by remh** [comment]
Closing as we didn't get more info.
