### ISSUE TITLE
[Process check] CPU Times require an interval

### ISSUE THREAD

**Issue by remh** [DataDog/dd-agent#1660]
psutil lets the possibility to not specify an interval for the process cpu time:
http://pythonhosted.org/psutil/#psutil.Process.cpu_times

However there are a few issues:
- We assert that the cpu_check_interval so we can't set it to None: https://github.com/DataDog/dd-agent/blob/cc5a67bb47110ef145e58561ab4471b946354742/checks.d/process.py#L233

- The way psutil works, is that it will save the previous cpu times in the Process object, however, we recreate a new object at each iteration: https://github.com/DataDog/dd-agent/blob/cc5a67bb47110ef145e58561ab4471b946354742/checks.d/process.py#L174 which means that we lose these values

As a result the only way to get cpu metrics for a process is to set a valid cpu_interval, which will be blocking, and if it's too low, it will be pretty irrelevant.

We shouldn't recreate a Process object at every iteration if the pid of the process we want to monitor hasn't changed. It would be the simplest way to fix this issue.

**Comment by remh** [comment]
@olivielpeau

**Comment by olivielpeau** [comment]
Fixed by #1928
