### ISSUE TITLE
Process-type service check visibility for docker containers

### ISSUE THREAD

**Issue by devinrsmith** [DataDog/dd-agent#1684]
I'm creating monitors to notify when processes go down (via process.yaml + https://app.datadoghq.com/monitors#create/process). This is a nice workflow for traditional processes, but doesn't work very well when docker spawns the processes. I can create specialized strings that grep for the command that I know docker will run, but it would be much nicer to say "I know there is going to be this docker container with name=X, please create the appropriate service check for it"

I'm also using docker.yaml, but this doesn't provide the process-type service checks. It might be nice to similarly express expected containers in docker.yaml, or have it automatically create service checks from docker containers.

**Comment by remh** [comment]
@devinrsmith you can use the docker.containers.running metric which is tagged by image name to do that.

Would that work for you ?

**Comment by remh** [comment]
Closing, as this use case is covered by using the docker.containers.running metric.
