### ISSUE TITLE
Windows agent is installed per user not per machine?

### ISSUE THREAD

**Issue by rlaveycal** [DataDog/dd-agent#1689]
I'm trying to automate deployment of DD using Chef. I've got my Chef recipe running fine in dev. When I try in test I'm having issues with the user the DD agent is installed by.

Chef is running as the SYSTEM account. The DD agent was installed by a normal machine user (local admin). When Chef tries to uninstall the agent prior to installing a new version it fails running 
````
MsiExec.exe /X{69A7A622-DCC1-41F5-91E0-CBFFCA5981D9} /qn
````
with error code 1605. This indicates that the product is not installed (it is).

Running the command locally on the server using the same user who originally installed DD works.
Installing as SYSTEM and then upgrading as SYSTEM (via Chef) works fine, although DD doesn't appear in the installed programs control panel.

Is there some reason that the agent is installed per user? Any ideas how I can automate uninstalling from a different account?

Thanks

**Comment by bigbam505** [comment]
Hey saw your comment on DataDog/chef-datadog#142 and wanted to say this is not the case for us on Windows Server 2008R2 so some OS information here would be helpful.  Maybe it is because you are installing on a different platform.  We are currently running version 5.4.0 on our windows hosts, and recently upgraded from 5.3.1

**Comment by rlaveycal** [comment]
I'm also using Windows 2008R2, chef 12.0.3 and windows CB 1.36.1. What I've done is:
 - Install DD agent 5.3 using local admin account
 - Use Chef to deploy DD agent 5.4, running as SYSTEM. 

And it works! I've changed my recipe from doing a remove then an install to doing an install with version number so that it executes when updating. This is working, although the Add/remove program control panel still shows 5.3 installed (admin user). 

Looking in the registry, node ```` KEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall ```` has keys for both version 5.3.1.0 and 5.4.0.0. Whether by luck or judgement the key for 5.4 is after that for 5.3 so Chef doesn't try and install on the next run.

If I install manually as a local admin, then run Chef as SYSTEM and do an **uninstall**
````
windows_package 'Remove Datadog Agent' do
  action		:remove
  package_name	'Datadog Agent'
end
````
this fails with my original error:
````
[2015-06-18T14:16:25+01:00] INFO: Removing windows_package[Remove Datadog Agent] with uninstall command 'MsiExec.exe /X{67A802D8-4E70-4F19-9931-4F6014286930} /qn'

================================================================================
Error executing action `remove` on resource 'windows_package[Remove Datadog Agent]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0, 42, 127], but received '1605'
---- Begin output of MsiExec.exe /X{67A802D8-4E70-4F19-9931-4F6014286930} /qn ----
STDOUT: This action is only valid for products that are currently installed.
````

So, if you don't so an uninstall then everything will run but you'll get a slightly inconsistent registry.

**Comment by bigbam505** [comment]
So I believe this is actually a problem which will cause chef to have odd errors odd errors.  For example if you uninstall from one user chef will still think it is available and will not uninstall it.  For example:

```
[2015-11-02T18:58:29-05:00] INFO: Processing log[{:name=>"Datadog Agent", :version=>"5.5.1.0", :uninstall_string=>"MsiExec.exe /X{FCDFA5FE-8472-4444-AF1B-26DFA51522B9}"}] action write (windows-datadog::dd-agent line 11)
[2015-11-02T18:58:29-05:00] INFO: {:name=>"Datadog Agent", :version=>"5.5.1.0", :uninstall_string=>"MsiExec.exe /X{FCDFA5FE-8472-4444-AF1B-26DFA51522B9}"}
[2015-11-02T18:58:29-05:00] INFO: Processing template[C:\ProgramData\Datadog\datadog.conf] action create (windows-datadog::dd-agent line 45)
[2015-11-02T18:58:29-05:00] INFO: Processing windows_service[DatadogAgent] action enable (windows-datadog::dd-agent line 49)

================================================================================
Error executing action `enable` on resource 'windows_service[DatadogAgent]'
================================================================================

SystemCallError
---------------
The specified service does not exist as an installed service. - OpenService: The specified service does not exist as an installed service.
```

Looking at the wxs documentation [here](http://wixtoolset.org/documentation/manual/v3/xsd/wix/package.html)  I think this can be fixed by just changing the `InstallScope` to be `perMachine` instead of unspecified. If the datadog/chef-datadog repo is suppose to support windows then this should probably happen to guarantee chef doesnt put datadog in a weird state

**Comment by bigbam505** [comment]
You can also force the behavior on windows by passing in the `ALLUSERS=1` into the MSI command  you can see the chef change required [here](https://github.com/DataDog/chef-datadog/pull/252/files#diff-20dc29c066aaf94323f42dc1c53341f8R39)

**Comment by yannmh** [comment]
Thanks a lot @rlaveycal, @bigbam505. #252 should, indeed, fix the issue. 

We are also looking into the possibility to move Datadog Agent installation mode on Windows to `per machine` only for a future version. Discarding the potential resulting upgrade incompatibility issues, it would certainly be cleaner (more more homogeneous) solution.
