### ISSUE TITLE
Running a specific test with check_mocks

### ISSUE THREAD

**Issue by sebest** [DataDog/dd-agent#1694]
Hello,

Is it possible to run a specific test or specifi test suite for check_mocks?

I'm currently doing rake ci:run[checks_mock], but i'd like to be able to execute only the tests related to my plugin.

thanx

**Comment by LeoCavaille** [comment]
Hi @sebest, if you want something more precise you should be able to call `nosetests` directly on your file or on your class?

```
# whole file
$ nosetests tests/checks/mock/test_system_swap.py  
# whole class
$ nosetests tests/checks/mock/test_system_swap.py:SystemSwapTestCase
```

**Comment by sebest** [comment]
Thanx Leo,

I would advice to add these information on this wiki page:
https://github.com/DataDog/dd-agent/blob/master/tests/README.md
