### ISSUE TITLE
[Kafka] Indentation issue in the yaml for kafka.net.bytes_out

### ISSUE THREAD

**Issue by MartinDatadog** [DataDog/dd-agent#1701]
Reported by Zendesk, ticket 27606 (https://datadog.zendesk.com/agent/tickets/27606)

![screenshot 2015-06-16 12 40 45](https://cloud.githubusercontent.com/assets/9215976/8188615/f4160a9e-1424-11e5-87d2-1f75218b8799.png)

This prevented metric kafka.net.bytes_out to be reported for this customer, until they corrected the indentation.

**Comment by MartinDatadog** [comment]
https://github.com/DataDog/dd-agent/pull/1702

**Comment by yannmh** [comment]
Fix by #1702
