### ISSUE TITLE
[mesos] don't raise when no mesos name is set ?

### ISSUE THREAD

**Issue by yannmh** [DataDog/dd-agent#1714]
The Mesos master and slave can take a variety of configuration options through command-line arguments, or environment variables (c.f. http://mesos.apache.org/documentation/latest/configuration/). 
If no cluster name is set, the `/state.json` endpoint does not return any `cluster` field, thus the check fails and raise:
```
        Traceback (most recent call last):
          File "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
            self.check(copy.deepcopy(instance))
          File "/opt/datadog-agent/agent/checks.d/mesos_slave.py", line 153, in check
            state_metrics = self._get_constant_attributes(url, timeout)
          File "/opt/datadog-agent/agent/checks.d/mesos_slave.py", line 139, in _get_constant_attributes
            self.cluster_name = master_state['cluster']
        KeyError: 'cluster'
```
Is this cluster name needed ? If so, it should be said somewhere and the exception should be caught and reworded. If not, let's be more flexible on the code.

**Comment by yannmh** [comment]
@DorianZaccaria can you take a look at this one ?

**Comment by DorianZaccaria** [comment]
I think @LeoCavaille released a fix for that. Yes it is asked by mesosphere.

**Comment by yannmh** [comment]
Looks like it's still raising: https://github.com/DataDog/dd-agent/blob/master/checks.d/mesos_slave.py#L139

**Comment by yannmh** [comment]
Fixed by https://github.com/DataDog/dd-agent/pull/1843. Thanks @DorianZaccaria !
