### ISSUE TITLE
Incorrect conversion of system.io.bytes_per_s metric

### ISSUE THREAD

**Issue by domoench** [DataDog/dd-agent#1718]
Incorrect conversion between megabytes and bytes [HERE](https://github.com/DataDog/dd-agent/blob/09249df7a895c534e6150ca066f544ba72606354/checks/system/unix.py#L75).

Also in the test file: tests/checks/mock/test_sysstat.py

```
'system.io.bytes_per_s': mb_s * 10**6
```
Should be
```
'system.io.bytes_per_s': mb_s * 2**20
```

I'm assuming here that we always mean Mebibytes when we say Megabytes. When metrics metadata is fully implemented the plan is to completely shift to the unambiguous kibi, mebi, gibi byte prefixes and no longer refer to the ambiguous kilo, mega, giga scientific prefixes for byte units.

**Comment by remh** [comment]
Thanks Thanks for the feedback @domoench fixed in https://github.com/DataDog/dd-agent/pull/1912
