### ISSUE TITLE
[core] Gohai - No filesystem data if un-configured mounting points

### ISSUE THREAD

**Issue by MartinDatadog** [DataDog/dd-agent#1719]
Reported by Stratagem in https://datadog.zendesk.com/agent/tickets/28204

"There were some mounting points that I had previously used with cgroups which were un-configured. 
This caused the df -l command to print two extra lines before the real filesystem output and this cause the issue. You can find them below.

df: '/cgroups/cpu': No such file or directory 
df: '/cgroups/cpuacct': No such file or directory
"

**Comment by olivielpeau** [comment]
Closing the issue as it's been reported only once, for a very specific edge case.
