### ISSUE TITLE
[process] Correctly handle psutil.NoProcessFound when getting process state

### ISSUE THREAD

**Issue by talwai** [DataDog/dd-agent#1721]
In situations where a process disappears after we discover its PID, we should be skipping over the subsequent interrogation of the process [here](https://github.com/DataDog/dd-agent/blob/cc5a67bb47110ef145e58561ab4471b946354742/checks.d/process.py#L173-L181). Currently the check is throwing errors like:
```
  File "/opt/datadog-agent/agent/checks.d/process.py", line 181, in get_process_state
    meminfo = self.psutil_wrapper(p, 'memory_info', ['rss', 'vms'])
UnboundLocalError: local variable 'p' referenced before assignment
```

**Comment by DrTyrell** [comment]
We're seeing this too, thanks for attending to it.

**Comment by jsh2134** [comment]
+1 noticed this as well

**Comment by ssbarnea** [comment]
This calls for a minor release update ASAP, I do still get this with 5.3.4 which seems to be the latest version!

**Comment by remh** [comment]
5.4.6 is released.

**Comment by ctrlrsf** [comment]
Confirmed 5.4.6 fixed this for us. Thanks!
