### ISSUE TITLE
[zookeeper] metrics should be reported as counts not gauges

### ISSUE THREAD

**Issue by LeoCavaille** [DataDog/dd-agent#1729]
For instance:
* `zookeeper.bytes_received` is a monotonically increasing gauge since ZK start
* `zookeeper.bytes_sent`

**Comment by remh** [comment]
this is a compatibility breaking change, we should use new metrics instead

**Comment by LeoCavaille** [comment]
Yes, that's also a good candidate for the "What to do when we change metrics in a backwards incompatible way" convo.
