### ISSUE TITLE
Agent unable to start on Windows 8.1

### ISSUE THREAD

**Issue by sjenriquez** [DataDog/dd-agent#1731]
1. Downloaded Datadog agent installer
2. Running command in shell did not open installer:`msiexec /qn /i ddagent-cli.msi APIKEY="xxx" HOSTNAME="my_hostname" TAGS="mytag1,mytag2"`
3. Opened installer by double clicking in Windows Explorer window.
4. After successfully installing the agent, the agent is unable to start.
5. Windows Event Log reports:

```
Traceback (most recent call last): File "win32\agent.pyc", line 57, in __init__ File "util.pyc", line 228, in get_hostname Exception: Unable to reliably determine host name. You can define one in datadog.conf or in your hosts file
```

Hostname is commented out by default with fresh agent install:

```
# Force the hostname to whatever you want.
#hostname: mymachine.mydomain
```

After uncommenting `hostname` and setting a name, the agent would start and begin reporting to Datadog.

**Comment by remh** [comment]
This is expected, the agent shouldn't start if we can't get a valid hostname.
