### ISSUE TITLE
[docker] add memory usable

### ISSUE THREAD

**Issue by tj** [DataDog/dd-agent#1739]
And/or % in use.

With ECS specifically there's no way to configure swap at the moment so we need to have a good idea of when containers are about to cap out.

**Comment by dkastner** [comment]
It looks like we can get `hierarchical_memory_limit` and 
`hierarchical_memsw_limit1`  from `CGROUP_METRICS` https://github.com/DataDog/dd-agent/blob/master/checks.d/docker.py#L19

Can we just collect those raw values and calculate a percentage when graphing or monitoring from datadog, or does the custom check need to calculate a percentage of memory available and log it as a percentage metric?

**Comment by remh** [comment]
Implemented in https://github.com/DataDog/dd-agent/commit/96c0305c13fdc8dfa004e551466bb1638873f71e

**Comment by dkastner** [comment]
:beers:
