### ISSUE TITLE
[docker] add labels as tags

### ISSUE THREAD

**Issue by tj** [DataDog/dd-agent#1742]
Any interest in supporting a "tags" (or similar) label, or simply grabbing all labels for container metrics? For our case we'd love to have `LABEL program="program-name"` for example and filter that way, even when the `image_repository` tag is available we may have several instances of an image with different configurations so that one will be helpful but it would still be great to have per-container tagging.

cheers

**Comment by remh** [comment]
That's a reasonable idea, it should probably be opt-in though as labels may be containing sensitive data. What do you think @tj ?

**Comment by remh** [comment]
Implemented in https://github.com/DataDog/dd-agent/pull/1824

**Comment by jippi** [comment]
Hi,

I don't see this being resolved in #1824 - do datadog automatically extract all docker labels as tags now ?

**Comment by remh** [comment]
@jippi Hi, no it doesn't. You have to whitelist the labels that you want to be extracted:
https://github.com/DataDog/dd-agent/blob/master/conf.d/docker_daemon.yaml.example#L129-L132
