### ISSUE TITLE
[docker] cgroups not found on Kubernetes

### ISSUE THREAD

**Issue by degemer** [DataDog/dd-agent#1748]
We search for containers files in /sys/fs/cgroup/{memory,cpuacct}/{lxc,docker,system.slide}/{docker_id}. Otherwise it seems that Kubernetes (at least for this case https://datadog.zendesk.com/agent/tickets/28574) uses /sys/fs/cgroup/{memory,cpuacct}/{docker_id}.

A quick fix: https://gist.github.com/degemer/54ddc50e62cade7f3162#file-docker-py-L418-L420

What do you think @hkaj ?

**Comment by remh** [comment]
Don't think it's related to kubernetes but more likely to the distribution used.

**Comment by degemer** [comment]
According to the info, it's happening on `Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-8.1`.

**Comment by hkaj** [comment]
It seems to be a kubernetes thing. I run debian with the same kernel and don't have the issue.
Your fix looks good @degemer, wanna open a PR? :)
