### ISSUE TITLE
[couch] support _stats server-only check

### ISSUE THREAD

**Issue by ferrouswheel** [DataDog/dd-agent#1749]
In restrictive environments it may not be possible to let datadog agent access database statistics.

CouchDB's server `/_stats/` at the root is public, so it'd be nice if it was possible to retrieve these stats without returning an error when the databases themselves would return "401 Unauthorized".

There is `db_whitelist`, but that requires at least one db that can be accessed. Just specifying the key with no value isn't recognised by the integration check.

I have worked around this by creating an empty database that can be accessed, and adding that to the whitelist, but it's sub-optimal.

**Comment by remh** [comment]
Thanks @ferrouswheel , it's definitely a legitimate use case. We'll work on it.
Thanks for the feedback!

**Comment by irabinovitch** [comment]
@remh Added tests for whitelist and blacklist functionality.

**Comment by yannmh** [comment]
Fixed by #1760. Thanks @irabinovitch !
