### ISSUE TITLE
[pgbouncer] Counters are reset

### ISSUE THREAD

**Issue by remh** [DataDog/dd-agent#1765]
```python
2015-07-13 04:33:13 UTC | INFO | dd.collector | aggregator(aggregator.py:358) | Metric pgbouncer.stats.bytes_received_per_second has a rate < 0. Counter may have been Reset.
2015-07-13 04:33:13 UTC | INFO | dd.collector | aggregator(aggregator.py:358) | Metric pgbouncer.stats.requests_per_second has a rate < 0. Counter may have been Reset.
2015-07-13 04:33:13 UTC | INFO | dd.collector | aggregator(aggregator.py:358) | Metric pgbouncer.stats.bytes_sent_per_second has a rate < 0. Counter may have been Reset.
```

This metric is likely not being collected with the right type.

**Comment by yannmh** [comment]
@remh do you how how is this message being displayed ? In other words, is it transient or persistent ?

These 3 metrics are fetched, parsed and computed from the `SHOW STATS` command output, respectively from the `total_requests `, `total_received ` and `total_sent ` [fields](https://github.com/DataDog/dd-agent/blob/master/checks.d/pgbouncer.py#L29-L31).

pgbouncer documentation (c.f below) confirms that these values are 'raw' counts, hence, it should be suitable to submit them as *rates*.

Those metrics are also assesed in our **integration** tests.
https://github.com/DataDog/dd-agent/blob/master/tests/checks/integration/test_pgbouncer.py#L64-L66

From http://manpages.ubuntu.com/manpages/saucy/man1/pgbouncer.1.html
```
   SHOW COMMANDS
       The SHOW commands output information. Each command is described below.

       SHOW STATS;
           Shows statistics.

           database
               Statistics are presented per database.

           total_requests
               Total number of SQL requests pooled by pgbouncer.

           total_received
               Total volume in bytes of network traffic received by pgbouncer.

           total_sent
               Total volume in bytes of network traffic sent by pgbouncer.
```

**Comment by yannmh** [comment]
Considering my previous post and my inability to reproduce the issue, I am closing the issue. 

Let's re-open if it happens agains and/or we have more information about it.
