### ISSUE TITLE
[install] dd-agent user has no group

### ISSUE THREAD

**Issue by LeoCavaille** [DataDog/dd-agent#1794]
Someone noted on IRC, it could be useful to have a group for `dd-agent` to make simple giving access to Datadog files.
Likely easy to do, might or might not include a file permission migration for the existing installs.
Looks like we do it in the redhat case, but not on debian-based distros?

Refs:
* https://github.com/DataDog/dd-agent-omnibus/blob/4f1f0c38be5a405ec9576fe31c49f1a27cf9321b/package-scripts/datadog-agent/postinst#L42
* https://github.com/DataDog/dd-agent-omnibus/blob/4f1f0c38be5a405ec9576fe31c49f1a27cf9321b/package-scripts/datadog-agent/preinst#L38-L39

**Comment by remh** [comment]
Let's do it for 5.8.0

**Comment by acasademont** [comment]
yes please, that would be useful to give some sockets group permission and not the crazy 0777
