### ISSUE TITLE
Network check instance tag mismatch in 5.4

### ISSUE THREAD

**Issue by amankapur** [DataDog/dd-agent#1796]
Instance tags used to be a part of the check name and hence normalized on the agent before sending to DD. However, since the new change in 5.4 where instance is separated as tag it doesn't get normalized on the agent. The problem is that there is a difference between the agent's normalize and sobotka's tag normalize and hence there are cases when instance tag names don't match up. 

eg: `instance:tag-tag`  in 5.3 would get normalized to `instance:tag_tag` in 5.3 but remains `instance:tag-tag` in 5.4 

I've created a fix (https://github.com/DataDog/dogweb/pull/9031) in sobotka for now but this might be better fixed on the agent itself for tcp and http checks.

**Comment by yannmh** [comment]
Thanks for reporting @amankapur. Let's plan a fix for the 5.5.0 agent release.
