### ISSUE TITLE
postgres check should allow setting a statement timeout

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#1801]
The postgres check should enable me to continue to watch postgres metrics if they take longer than a pg server's global statement_timeout is set to something lower than it takes the Agent to retrieve all metrics.

Ref: http://www.postgresql.org/docs/9.3/static/runtime-config-client.html#GUC-STATEMENT-TIMEOUT

The regular [connect() takes a timeout parameter](http://pythonhosted.org/pg8000/dbapi.html?highlight=timeout#pg8000.connect), but that's only valid in Python 3, as well as not setting the correct timeout - this sets a connection timeout, not a statement timeout.

Setting a configurable `SET statement_timeout = $CONFIG_VALUE` at the start of the pg check should do the trick, but I couldn't see where it would be simplest to add.

**Comment by olivielpeau** [comment]
Moving back to Triage as the 5.8 merge window is closing soon

**Comment by masci** [comment]
I'm closing this provided that it wouldn't be an easy change and this is the only request we got in 3 years.

**Comment by miketheman** [comment]
Was looking for this today, and found that it was finally implemented! https://github.com/DataDog/integrations-core/pull/6498/files#diff-67d19fe2ac4fe94607597c0e3b9a1a14a311898e6666c48b000e926900511c6dR55-R60
