### ISSUE TITLE
docker_root not behaving as expected

### ISSUE THREAD

**Issue by rahulpowar** [DataDog/dd-agent#1809]
I am running the agent in a container and have been trying to get to the bottom of an docker integration error, specifically [this exception](https://github.com/DataDog/dd-agent/blob/master/checks.d/docker.py#L429) is being triggered. 

Checking through the code, it looks like the `docker_root` variable will not have the desired effect [here]( https://github.com/DataDog/dd-agent/blob/master/checks.d/docker.py#L461) as `os.path.join` will see an absolute `mountpoint ` and skip prepending `docker_root `. As a result the mountpoints set and subsequently used do not expose the host's state and no docker data is available. Hacking around the code this does seem to be the case though a second issue is that [this check]( https://github.com/DataDog/dd-agent/blob/master/checks.d/docker.py#L460) does not validate for the mounted i.e. `docker_root ` sys/fs and also ends up failing to find the cpu metrics for the containers.

For the same `os.path.join` reason, the `/proc/mounts` filesystem the code is trying to parse is also not the mounted one but isn't material as at least my docker setup has them set to be identical.

**Comment by remh** [comment]
Thanks for the feedback @rahulpowar 

We released a new version of the agent check since (Agent 5.4.5)

Are you still seeing the issue with this version ?

Can you share with us mroe details about your configuration ?
OS / Version of docker etc..

Thanks a lot.

**Comment by remh** [comment]
We released a new docker check in Agent 5.5.0 This issue is not happening anymore closing.
Thanks for the feedback @rahulpowar !
