### ISSUE TITLE
[mesos] dd-agent needs to use metrics/snapshot endpoint for mesos 0.23.0

### ISSUE THREAD

**Issue by tdooner** [DataDog/dd-agent#1818]
Mesos 0.23.0 saw the removal of the `stats.json` endpoint in favor of a new `metrics/snapshot` endpoint, [according to the 0.23.0 upgrade notes](http://mesos.apache.org/documentation/latest/upgrades/).

The stats.json endpoint is hardcoded into the AgentCheck: https://github.com/DataDog/dd-agent/blob/master/checks.d/mesos.py#L66

Perhaps a good course of action would be to detect failure in accessing the new endpoint and fall back to the legacy stats.json.

**Comment by yannmh** [comment]
Thanks for reporting @tdooner.

This generic Mesosphere check is actualy being deprecated, in favor of the Mesosphere [master](https://github.com/DataDog/dd-agent/blob/master/checks.d/mesos_master.py) and [slave](https://github.com/DataDog/dd-agent/blob/master/checks.d/mesos_slave.py) specific checks introduced in the 5.4.0 release. We'll add a note about it in the 5.5.0, and it'll likely be removed in a future version of the Datadog Agent.

**Comment by tdooner** [comment]
Great, thanks! I'm glad that you were ahead of the curve on this :).
