### ISSUE TITLE
NginxPlus support

### ISSUE THREAD

**Issue by nodesocket** [DataDog/dd-agent#1836]
NginxPlus status returns lots of counters in JSON format. See the following example:

```
{
    "version": 5,
    "nginx_version": "1.7.11",
    "address": "10.0.7.162",
    "generation": 2,
    "load_timestamp": 1439254340135,
    "timestamp": 1439836905575,
    "processes": {
        "respawned": 0
    },
    "connections": {
        "accepted": 295947,
        "dropped": 0,
        "active": 1,
        "idle": 8
    },
    "requests": {
        "total": 297355,
        "current": 1
    },
    "server_zones": {
        "app.xxxxxxxx.com": {
            "processing": 0,
            "requests": 86,
            "responses": {
                "1xx": 0,
                "2xx": 32,
                "3xx": 0,
                "4xx": 38,
                "5xx": 0,
                "total": 70
            },
            "received": 16165,
            "sent": 523735
        },
        "xxxxxxxx.com": {
            "processing": 0,
            "requests": 252,
            "responses": {
                "1xx": 0,
                "2xx": 137,
                "3xx": 0,
                "4xx": 113,
                "5xx": 0,
                "total": 250
            },
            "received": 83908,
            "sent": 4211652
        },
        "health": {
            "processing": 0,
            "requests": 144124,
            "responses": {
                "1xx": 0,
                "2xx": 144057,
                "3xx": 0,
                "4xx": 67,
                "5xx": 0,
                "total": 144124
            },
            "received": 15425964,
            "sent": 27832389
        },
        "status": {
            "processing": 1,
            "requests": 4013,
            "responses": {
                "1xx": 0,
                "2xx": 4010,
                "3xx": 2,
                "4xx": 0,
                "5xx": 0,
                "total": 4012
            },
            "received": 549314,
            "sent": 6049220
        }
    },
    "upstreams": {
        "backend": [
            {
                "id": 0,
                "server": "10.0.0.38:80",
                "backup": false,
                "weight": 1,
                "state": "up",
                "active": 0,
                "requests": 313,
                "responses": {
                    "1xx": 0,
                    "2xx": 169,
                    "3xx": 0,
                    "4xx": 141,
                    "5xx": 0,
                    "total": 310
                },
                "sent": 120407,
                "received": 4589174,
                "fails": 0,
                "unavail": 0,
                "health_checks": {
                    "checks": 194056,
                    "fails": 0,
                    "unhealthy": 0,
                    "last_passed": true
                },
                "downtime": 0,
                "downstart": 0,
                "selected": 1439836411000
            }
        ]
    },
    "caches": {}
}
````

Should NginxPlus perhaps be a separate integration, or could the existing Nginx integration work for both?

**Comment by yannmh** [comment]
Sorry for the late answer @nodesocket.

We could probably enhance our current Nginx check to cover these additional metrics. Could you tell us more specifically which metrics, not already covered, you would be interested to see collected please ?

**Comment by nodesocket** [comment]
Regular nginx does not even return json. It does not include nearly as many counters and metrics.

Things I'd like:

     connections.dropped
     connections.active
     connections.idle
     requests.current
     
For each upstreams:

    active
     
For each zone:
    
     processing

**Comment by yannmh** [comment]
Hey @nodesocket,
I double-checked our Nginx check and we actually do already support Nginx Plus. Even more, the metrics you mentionned should be already covered.

This is for instance, a sample of metrics collected from a Nginx Plus instance: https://github.com/DataDog/dd-agent/blob/master/tests/checks/fixtures/nginx/nginx_plus_out.python

And the test where we assess the collection:
https://github.com/DataDog/dd-agent/blob/master/tests/checks/integration/test_nginx.py#L100-L108

Do you have an issue collecting these metrics ? if so, would you mind reaching out [with your logs and configs](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support)  to help us troubleshooting ? Thanks

**Comment by nodesocket** [comment]
Enabled the nginx plugin on our NginxPlus load balancers instances, and set:

    - nginx_status_url: http://localhost:8080/status

Doing a curl on `http://localhost:8080/status` confirms that the status json is coming back:

````
{"version":5,"nginx_version":"1.7.11","address":"127.0.0.1","generation":1,"load_timestamp":1441219137735,"timestamp":1441220105977,"processes":{"respawned":0},"connections":{"accepted":36,"dropped":0,"active":1,"idle":0},"requests":{"total":36,"current":1},"server_zones":{"app.brandcast.com":{"processing":0,"requests":0,"responses":{"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"total":0},"received":0,"sent":0},"brandcast.com":{"processing":0,"requests":0,"responses":{"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"total":0},"received":0,"sent":0},"health":{"processing":0,"requests":0,"responses":{"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"total":0},"received":0,"sent":0},"status":{"processing":1,"requests":36,"responses":{"1xx":0,"2xx":35,"3xx":0,"4xx":0,"5xx":0,"total":35},"received":7032,"sent":72038}},"upstreams":{"backend":[{"id":0,"server":"10.0.1.0:80","backup":false,"weight":1,"state":"up","active":0,"requests":0,"responses":{"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"total":0},"sent":0,"received":0,"fails":0,"unavail":0,"health_checks":{"checks":323,"fails":0,"unhealthy":0,"last_passed":true},"downtime":0,"downstart":0,"selected":0},{"id":1,"server":"10.0.1.1:80","backup":false,"weight":1,"state":"up","active":0,"requests":0,"responses":{"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"total":0},"sent":0,"received":0,"fails":0,"unavail":0,"health_checks":{"checks":323,"fails":0,"unhealthy":0,"last_passed":true},"downtime":0,"downstart":0,"selected":0},{"id":2,"server":"10.0.59.206:80","backup":false,"weight":1,"state":"up","active":0,"requests":0,"responses":{"1xx":0,"2xx":0,"3xx":0,"4xx":0,"5xx":0,"total":0},"sent":0,"received":0,"fails":0,"unavail":0,"health_checks":{"checks":323,"fails":0,"unhealthy":0,"last_passed":true},"downtime":0,"downstart":0,"selected":0}]},"caches":{}}
````

Yet we don't see anything in DataDog for the load balancers nginx. Also, the infrastructure list, does not show that the load balancers have the nginx integration (no tag).

**Comment by nodesocket** [comment]
Anything? Still not seeing our NginxPlus instances showing up with the nginx integration in DataDog?

**Comment by yannmh** [comment]
@nodesocket ,

> Yet we don't see anything in DataDog for the load balancers nginx. 

Could you send us [your logs and configs](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support), from one of these hosts, via the ticket you created with Datadog support team please ? That'd help to investigate why these metrics are not properly collected.

Thanks,

**Comment by nodesocket** [comment]
I actually don't have a ticket, only been using this issue. I just did a flare, and have a `.tar.bz2` for you. Where is the best place to send it?

**Comment by yannmh** [comment]
You can use the _flare_ command (`sudo service datadog-agent flare`) to send the archive to Datadog support team: a ticket is then, automatically created on our side.

**Comment by nodesocket** [comment]
Just did a flare, referencing ticket. Let me know what you find.

**Comment by remh** [comment]
Thanks for all the feedback you gave us @nodesocket . Looks like your issues were resolved through our support channels. Closing this ticket.
