### ISSUE TITLE
WARNING | dd.forwarder | forwarder(ddagent.py:175) | You are a Datadog user so we will send data to https://app.datadoghq.com

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#1856]
`WARNING | dd.forwarder | forwarder(ddagent.py:175) | You are a Datadog user so we will send data to https://app.datadoghq.com`

This line is clearly wrong:
https://github.com/DataDog/dd-agent/blame/master/ddagent.py#L107

I do not see any reason why this would be a warning, when that's the expected behaviour. This should be at INFO level OR even DEBUG one, but clearly not an warning.

**Comment by yannmh** [comment]
I agree with you. We'll change this message LOG level in the 5.5.0. 

Thanks again @ssbarnea !

**Comment by remh** [comment]
I'll write that here for posterity:

The reason was that older versions of the Agent that were bundling Pup (https://github.com/DataDog/dd-agent/tree/4.0.0/pup)  could be used without a Datadog account so we wanted to warn users when data was sent to Datadog.
