### ISSUE TITLE
The dogstatsd daemon may lose metrics when submitted in batches

### ISSUE THREAD

**Issue by jswoods** [DataDog/dd-agent#1862]
If I am submitting metrics in batches of more than one and at least one good metric falls after a bad metric, that good metric will be missed due to an exception thrown by the bad one. For example, here is a single packet send to the dogstatsd agent:

my.bad.metric:50|someunknowntype
my.good.metric:50|g

Even though the good metric is the correct format, since it was submitted in batch with a bad metric in front of it, the good metric will be lost. Ideally, the agent will log an error for the bad metric rather than throw an exception so it can continue processing other metrics in the batch.

I'm happy to include a pull request once someone can confirm this is a sane thing to do and isn't going to be a problem. The test that will need to be adjusted is: test_bad_packets_throw_errors (tests.core.test_dogstatsd.TestUnitDogStatsd)

**Comment by yannmh** [comment]
Thanks for reporting @jswoods. That's definitely an issue we need to fix.

> Ideally, the agent will log an error for the bad metric rather than throw an exception so it can continue processing other metrics in the batch.

I think this is a legit behavior. The challenge here, is to avoid introducing any slowdown in this code path, i.e. reducing the max throughput of the dogstatsd server.

We'll be happy to review your PR if you make one. Still, we'll make sure that it's fixed with _5.6.0_ release. Thanks again.

**Comment by olivielpeau** [comment]
Removing from the 5.8 milestone as the merge window for that release is closing

**Comment by yannmh** [comment]
This is a *WON'T FIX* for now as this cannot be done without introducing any slowness in the code.
See https://github.com/DataDog/dd-agent/pull/2511#issuecomment-224044083.

However this would be considered in the next major version of the Datadog Agent.

Thanks again.

**Comment by olivielpeau** [comment]
Fixed in Agent v6: https://github.com/DataDog/datadog-agent/
