### ISSUE TITLE
Update gohai.exe

### ISSUE THREAD

**Issue by xkrt** [DataDog/dd-agent#1879]
Hi,

Please update gohai.exe in windows ddagent distributive, in latest version has bugfix of network interfaces parsing.
I checked, gohai.exe from distributive fails on my ipconfig output, but latest version builded from source is fine.

**Comment by yannmh** [comment]
Hey @xkrt,

Sorry to hear you are experiencing issues with _gohai_ on Windows.
A new Datadog agent release -5.5.0- is on the track, and will ship, among other bug fixes, _gohai_ last updates. It'll be out by next week.

More information: https://github.com/DataDog/dd-agent/blob/master/CHANGELOG.md#550--unreleased

Thank you

**Comment by xkrt** [comment]
I have installed 5.5.0 ddagent and run `gohai.exe` in installation folder and error still here:
```
panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x514ae0, 0x5ddf5c)
        c:/go/src/pkg/runtime/panic.c:279 +0xe9
github.com/DataDog/gohai/network.getNetworkInfo(0x11f40040, 0x0, 0x0)
        C:/workspace/go/src/github.com/DataDog/gohai/network/network_windows.go:38 +0x566
github.com/DataDog/gohai/network.(*Network).Collect(0x5e07d8, 0x0, 0x0, 0x0, 0x0)
        C:/workspace/go/src/github.com/DataDog/gohai/network/network_common.go:17 +0x47
main.Collect(0x11f09780, 0x0, 0x0)
        C:/workspace/go/src/github.com/DataDog/gohai/gohai.go:32 +0xc6
main.main()
        C:/workspace/go/src/github.com/DataDog/gohai/gohai.go:44 +0x24

goroutine 19 [finalizer wait]:
runtime.park(0x412d30, 0x5e05f4, 0x5df969)
        c:/go/src/pkg/runtime/proc.c:1369 +0x94
runtime.parkunlock(0x5e05f4, 0x5df969)
        c:/go/src/pkg/runtime/proc.c:1385 +0x3f
runfinq()
        c:/go/src/pkg/runtime/mgc0.c:2644 +0xc5
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445
```

You forgot update `gohai.exe` in `.msi` bundle?

**Comment by yannmh** [comment]
Thanks for reporting @xkrt !

I just checked and you are right: something went wrong during the Windows agent build process, thus, it does not include the latest `gohai`.
We'll release a 5.5.1 bugfix release today: we'll make sure it ships `gohai` last updates as well as a few other bugfixes :bug:.

Sorry for the inconvenience caused.

**Comment by Aranjan21** [comment]
Hi All
I have a server in which Datadog is installed  which is failing to collect the data . I killed the process tree and tried to restart the datadog but still its not collecting the metrices .  I can see in Task Manager that several gohai.exe is running . I don't know whether that is causing the issuing . Please suggest .
