### ISSUE TITLE
CRIT Server 'unix_http_server' running without any HTTP authentication checking

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#1894]
I do this CRITICAL error in the logs of datadog and not information regarding why this happens. This should clearly not appear on clean installs, or it should reference a KB article that would specify how to fix it. 
```
CRIT Server 'unix_http_server' running without any HTTP authentication checking
```

Not to mention that CRIT is like FATAL, for errors that do stop execution. Based on the text I would say that is more likely to be at WARN level.

**Comment by yannmh** [comment]
Adding the issue to the 5.6.0 milestone. Thanks @ssbarnea

**Comment by olivielpeau** [comment]
This error is logged by supervisord, see https://github.com/Supervisor/supervisor/issues/694

We should assess whether we should add authentication to the `unix_http_server` in supervisord's config (`/etc/dd-agent/supervisor.conf`, https://github.com/DataDog/dd-agent/blob/6837c53f4a214fb6c7e6c312529edc0f457ee8cb/packaging/supervisor.conf#L4-L5).

Moving the issue to the 5.8.0 milestone.

**Comment by olivielpeau** [comment]
After having a closer look I think that this error can be safely ignored: the `unix_http_server` uses a local socket that is only usable by the `dd-agent` user.

@ssbarnea I'm closing this issue but feel free to update it if you have any comment. Thanks!
