### ISSUE TITLE
CRIT Supervisor running as root (no user in config file)

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#1895]
That's another critical error that I am seeing on DataDog which is not supposed to happen. Why does the default setup includes it? Can't you just create a user and assign to run as this one?

Even so, this error should include a link to a KB article that would explain how to fix it.

Out of curiosity, I tried to add user=datadog-agent inside the `[supervisord]` but this prevents the service from starting, so we need more help on fixing these bugs.

**Comment by yannmh** [comment]
Hello @ssbarnea,

You're right supervisor should be running as `dd-agent` user, not `root`.  We are currently working and testing the transition (c.f. https://github.com/DataDog/dd-agent/pull/1620): it should be out with Datadog agent 5.6.0. 

Thanks for your patience

**Comment by remh** [comment]
Duplicate of #1348
