### ISSUE TITLE
Initialization error no module named apibase when configuring sqlserver integration on windows

### ISSUE THREAD

**Issue by sandyplace** [DataDog/dd-agent#1907]
Encountered this when trying to enable sqlserver integration on windows using the latest downloaded version for dd-agent:

Initialization error: Traceback (most recent call last): File "config.pyc", line 804, in load_check_directory File "C:\Program Files (x86)\Datadog\Datadog Agent\files\..\checks.d\sqlserver.py", line 14, in <module> File "adodbapi\__init__.pyc", line 10, in <module> ImportError: No module named apibase

Is this an installation issue? The version of Python embedded into the agent?

**Comment by remh** [comment]
Thanks for reporting this issue @sandyplace we'll have a look very shortly.

**Comment by talwai** [comment]
@sandyplace Can you give us more details about your windows `systeminfo` and how exactly you downloaded the agent ? You are seeing this issue on `5.4.6` yes?

**Comment by sandyplace** [comment]
Running Windows Server 2012 and the agent was downloaded from the Integrations->Agent page on the dashboard and then selecting Windows. Which points to this link: https://s3.amazonaws.com/ddagent-windows-stable/ddagent-cli.msi

**Comment by talwai** [comment]
@sandyplace We had a dependency issue in our Windows installer, thanks for bringing it to our notice! We just rolled out a patch. Would you mind re-installing through the same process as before? Let us know if  you still have issues with the new version

**Comment by sandyplace** [comment]
Is the patch available through the same installation link: https://s3.amazonaws.com/ddagent-windows-stable/ddagent-cli.msi ?

**Comment by sandyplace** [comment]
looks to be working now. thx for the speedy fix

**Comment by remh** [comment]
Thanks again for the feedback @sandyplace
