### ISSUE TITLE
Response times in IIS

### ISSUE THREAD

**Issue by oliverjanik** [DataDog/dd-agent#1935]
Is there any way to capture response times for IIS? 

[Docs](http://docs.datadoghq.com/integrations/iis) don't mention anything.

**Comment by yannmh** [comment]
Hi @oliverjanik,

Datadog Agent's IIS check relies on Windows Management Instrumentation (WMI) to capture IIS related metrics, more specifically, `Win32_PerfFormattedData_W3SVC_WebService` formatted data class.

The full list of web service counters is available here: https://msdn.microsoft.com/en-us/library/aa394298(v=vs.85).aspx
And these are the ones that the check collects by default: https://github.com/DataDog/dd-agent/blob/master/checks.d/iis.py#L13-L43.

Unfortunately, there is no web service counter for IIS response time. 
An alternative to capture this metric would be to enable  'time-taken' entries in IIS logs, and parse it using `dogstream` for instance.
