### ISSUE TITLE
haproxy check missing ability to add custom tags

### ISSUE THREAD

**Issue by awasilyev** [DataDog/dd-agent#1954]
It will be very nice to have ability to set custom tags on haproxy checks

**Comment by yannmh** [comment]
Thanks for the feedback @awasilyev !

By 'custom tags', do you mean arbitrary set **constant** tags ?  

HAProxy service checks are currently tagged by `service` and `backend`. There is also an [optional] (https://github.com/DataDog/dd-agent/blob/master/conf.d/haproxy.yaml.example#L28-L31) to add a tagging per `host` which could be helpful to scope a service check with the same HAProxy configuration across multiple environements.

**Comment by awasilyev** [comment]
Yes, I talking about constant tags, like https://github.com/DataDog/dd-agent/blob/master/conf.d/activemq.yaml.example#L14 for example

**Comment by olivielpeau** [comment]
Resolved via #2649, will be released with `5.10.0`. Closing

Thanks @awasilyev for opening this issue!
