### ISSUE TITLE
/bin/bash might not exist for utils/pip-allow-failures.sh

### ISSUE THREAD

**Issue by zecke** [DataDog/dd-agent#1955]
Executing rake setup_env on a FreeBSD 10.1 machine will fail because #!/bin/bash will not lead to the script to execute. bash can be installed but then will be located in /usr/local/bin.

Can the script to be changed to not require bash or use env bash to start it?

**Comment by yannmh** [comment]
Thanks for reporting @zecke.

I am adding the issue to the 5.6.0 milestone (even though it's not release related) so it gets fixed soon :smile:

**Comment by olivielpeau** [comment]
`utils/pip-allow-failures` will be made compatible with `/bin/sh` with #1504, which will be merged for 5.7.0.

**Comment by olivielpeau** [comment]
Fixed by #2198. Closing.
