### ISSUE TITLE
Check for FreeBSD for syslog

### ISSUE THREAD

**Issue by zecke** [DataDog/dd-agent#1956]
https://github.com/DataDog/dd-agent/blob/master/config.py#L1027

* I check you want to use the Platform.is_darwin check here?
* For FreeBSD the file is /var/run/log

**Comment by yannmh** [comment]
Thanks for the feedback @zecke.

We'll work on a fix for the next release.

**Comment by olivielpeau** [comment]
Thanks again @zecke for reporting this issue. The fix will be part of the 5.7.0 release.
