### ISSUE TITLE
Test status is "ok" with command errors

### ISSUE THREAD

**Issue by xiaclo** [DataDog/dd-agent#1957]
From ```rake ci:run```:

```
...
tests.core.test_check_status.test_check_status_fail ... ok
tests.core.test_check_status.test_check_status_pass ... ok
tests.core.test_check_status.test_persistence ... ok
tests.core.test_check_status.test_persistence_fail ... ok
test_dupe_tags (tests.core.test_common.TestAggregator) ... ok
testEdgeCases (tests.core.test_common.TestCore) ... ok
Tests that the app tags are sent if specified so ... Usage: nosetests [options]

nosetests: error: no such option: -s
ok
test_collector (tests.core.test_common.TestCore) ... Usage: nosetests [options]

nosetests: error: no such option: -s
ok
test_counter (tests.core.test_common.TestCore) ... ok
test_gauge (tests.core.test_common.TestCore) ... ok
test_get_proxy (tests.core.test_common.TestCore) ... ok
test_min_collection_interval (tests.core.test_common.TestCore) ... ok
test_name (tests.core.test_common.TestCore) ... ok
Starting with Agent 5.0.0, there should always be a local forwarder ... ok
...
```

I doubt "no such option: -s" qualifies as the tests running "ok"

This is using nose==1.3.4

**Comment by remh** [comment]
@xiaclo Thanks for the feedback! the `-s` parameter is used to tell nose to get into pdb when a breakpoint is hit. This is not required for the test suite to be executed. So it looks like the tests are passing properly.

**Comment by LeoCavaille** [comment]
This isn't supposed to show up in the build logs, so I would be for investigating it a bit, maybe we are skipping/missing tests because of that?
example: https://travis-ci.org/DataDog/dd-agent/jobs/82912178#L263

The `-s` flag is passed here
https://github.com/DataDog/dd-agent/blob/master/ci/common.rb#L202
