### ISSUE TITLE
Tag Windows services or instances

### ISSUE THREAD

**Issue by msnelling** [DataDog/dd-agent#1963]
We should be able to tag individual monitored services, as well as tagging the instance in the case of multiple instances (are multiple instances for the same machine but different services even possible?).

**Comment by remh** [comment]
@msnelling Thanks for the feedback.
Yes multiple instances to monitor different services is definitely possible. The service checks should also already be tagged by service name. 
Are you looking to add extra custom tags ?

**Comment by msnelling** [comment]
We'd just want to tag our database instances with things like dev, prod.

**Comment by yannmh** [comment]
@msnelling were you able to find a solution to your problem ? 
If not, could you contact the support team detailing your use case please ? They are generally more reactive, and helpful on advises.

**Comment by msnelling** [comment]
@yannmh now we weren't. In fact we found a few things like this that have kind of turned us of the service TBH.

**Comment by yannmh** [comment]
Thanks for the reply. I'll close the issue.
