### ISSUE TITLE
SSL Connection Failure 

### ISSUE THREAD

**Issue by gphat** [DataDog/dd-agent#1964]
When trying to use SSL validation (a requirement for us) to an **internal HAProxy** as per [the documentation](https://github.com/DataDog/dd-agent/wiki/Proxy-Configuration#using-haproxy-as-a-proxy) I'm having trouble with the embedded SSL/cURL.

From `/opt/datadog-agent/embedded`:
```
bin/openssl s_client -connect datadog-proxy.local.corp.stripe.com:3834 -CAfile /opt/datadog-agent/agent/datadog-cert.pem -tls1_2
```
Verify return code: 27 (certificate not trusted)

I can try and use the cert required directly:
```
bin/openssl s_client -connect datadog-proxy.local.corp.stripe.com:3834 -CAfile /etc/ssl/certs/DigiCert_Global_Root_CA.pem -tls1_2
```

Everything works. Yay!

But I'd rather specify a CApath (which I can't seem to do) or have your included cert have this DigiCert CA cert. What am I missing?

**Comment by gphat** [comment]
Ping!

**Comment by remh** [comment]
Hi @gphat 
Can you share your haproxy.cfg please ?

HAProxy should just be a transparent TCP proxy to datadog so the certificate validation should work with /opt/datadog-agent/agent/datadog-cert.pem

Is that causing any issue in the agent itself ?

**Comment by gphat** [comment]
Hey @remh!

Here's our haproxy.conf:
```
backend datadog
        balance roundrobin
        mode http

        server haproxy-app.agent.datadoghq.com haproxy-app.agent.datadoghq.com:443  check inter 10000 rise 4 fall 2 check port 80 ssl verify required ca-file /etc/ssl/certs/ca-certificates.crt verifyhost haproxy-app.agent.datadoghq.com
```

The issue seems to be that your cert list doesn't have that specific DigiCert CA file in it? That's who issues our internal "corp" cert.  I don't _think_ that is anything special, but maybe we should just use our own?

Regardless of that, another solution is to expose the `CAPath` to the underlying SSL implementation through Tornado or whatever this is using?

**Comment by remh** [comment]
@gphat as per the docs https://github.com/DataDog/dd-agent/wiki/Proxy-Configuration#using-haproxy-as-a-proxy you should use tcp.

This way this way you don't have to decrypt and then reencrypt the payloads.

Is there a reason you set the mode to http ?

**Comment by gphat** [comment]
Because doing so would require disabling SSL validation, if I understand correctly. By using HTTP — and decrypting / reencrypting — we are assured certificate validation at each step. In TCP mode we'd have to disable validation at the agent level because the local hostname would not match the one presented in your certificate.

**Comment by remh** [comment]
@gphat sorry for the delayed response.

In your `/etc/dd-agent/datadog.conf` , can you add the following lines please ?
```
use_curl_http_client: yes
ca_certs: /etc/ssl/certs/DigiCert_Global_Root_CA.pem
```

Then restart the agent and it should work.

**Comment by gphat** [comment]
No worries, @remh. Your suggestion is precisely how I fixed it. I guess my surprise came from having to do this at all. I expected that the included CA certs would dwim here. Having to hunt the correct one down and specify it directly instead of a path seemed confusing. Is this the you'd propose I do it going forward? Why isn't the digicert in your CA list?

**Comment by gphat** [comment]
Cross ping that I'd love some eyes on [puppet-datadog-agent#123](https://github.com/DataDog/puppet-datadog-agent/pull/123), since it gives me the ability to override this without heavily vendoring the puppet module. :smile:

**Comment by irabinovitch** [comment]
Going to re-close this based on passed comments.
