### ISSUE TITLE
link to dogstatd api is outdated

### ISSUE THREAD

**Issue by simnyc** [DataDog/dd-agent#1967]
This link https://github.com/DataDog/dd-agent/blob/master/datadog.conf.example#L103-L104 is outdated

**Comment by LeoCavaille** [comment]
And your link in this issue could become outdated too :), try to use links
for files that either use a specific commit or tag and not the tip of a
branch (here master).
Should fix, I guess it should be replaced by
http://docs.datadoghq.com/guides/dogstatsd/, what do you think?

-- 
Léo

**Comment by irabinovitch** [comment]
@simnyc *ping*
