### ISSUE TITLE
Docker cgroup missing after Docker 1.8.2 update

### ISSUE THREAD

**Issue by satblip** [DataDog/dd-agent#1968]
We are running the Docker container version of the `dd-agent` to monitor our Docker applications.

It was perfectly running until we've updated to the last Docker version 

```shell
Docker version 1.8.2, build 0a8c2e3
```

It now returns this error :

```shell
Instance #0[ERROR]:'Cannot find Docker cgroup directory. Be sure your system is supported.'
```

The volumes are the following : 

```js
"Mounts": [
        {
            "Source": "/proc/mounts",
            "Destination": "/host/proc/mounts",
            "Mode": "ro",
            "RW": false
        },
        {
            "Source": "/etc/dd-agent/conf.d",
            "Destination": "/etc/dd-agent/conf.d",
            "Mode": "ro",
            "RW": false
        },
        {
            "Source": "/sys/fs/cgroup",
            "Destination": "/host/sys/fs/cgroup",
            "Mode": "ro",
            "RW": false
        },
        {
            "Source": "/var/run/docker.sock",
            "Destination": "/var/run/docker.sock",
            "Mode": "rw",
            "RW": true
        }
    ]
```

If I look to a cgroup into the container, I found Docker.

```shell
ls -al /host/sys/fs/cgroup/cpuacct/
```

```shell
-rw-r--r--  1 root root   0 Oct  2 12:19 cgroup.clone_children
--w--w--w-  1 root root   0 Oct  2 12:19 cgroup.event_control
-rw-r--r--  1 root root   0 Oct  2 12:19 cgroup.procs
-r--r--r--  1 root root   0 Oct  2 12:19 cgroup.sane_behavior
-r--r--r--  1 root root   0 Oct  2 12:19 cpuacct.stat
-rw-r--r--  1 root root   0 Oct  2 12:19 cpuacct.usage
-r--r--r--  1 root root   0 Oct  2 12:19 cpuacct.usage_percpu
drwxr-xr-x 29 root root   0 Oct  5 14:43 docker
-rw-r--r--  1 root root   0 Oct  2 12:19 notify_on_release
-rw-r--r--  1 root root   0 Oct  2 12:19 release_agent
-rw-r--r--  1 root root   0 Oct  2 12:19 tasks
```

Our docker conf.d : 

```yaml
init_config:
  docker_root: /host

instances:
  - url: "unix://var/run/docker.sock"
    new_tag_names: true
    collect_images_stats: false
```

**Comment by satblip** [comment]
Moving to `docker_daemon` check doesn't returns any error, but we only have two metrics :

```shell
docker.containers.running
docker.containers.stopped
```

and the check doesn't appear in the `info` result anymore :

```shell
Checks
  ======

    disk
    ----
      - instance #0 [OK]
      - Collected 80 metrics, 0 events & 1 service check

    elastic
    -------
      - instance #0 [OK]
      - instance #1 [OK]
      - instance #2 [OK]
      - Collected 303 metrics, 0 events & 7 service checks

```

**Comment by hkaj** [comment]
Hi @satblip, thank you for reporting this.
Can you paste here the command you use to create the container please (don't forget to edit out your API key)? It should be similar to the default one we show [here](https://github.com/DataDog/docker-dd-agent#quick-start).

Also the fact that `docker_daemon` doesn't appear in the `info` result suggests that the yaml config file is missing. Did you create a `docker_daemon.yaml` file in `conf.d` and restart your agent to replace the old config?

**Comment by satblip** [comment]
Hi @hkaj, thanks for your reply.

Here is the command:

```shell
sudo docker run -d --privileged --name datadog_watcher -p 17123:17123 -v /var/run/docker.sock:/var/run/docker.sock -v /proc/mounts:/host/proc/mounts:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro -v /etc/dd-agent/conf.d/:/etc/dd-agent/conf.d/:ro -v /etc/dd-agent/checks.d/docker.py:/etc/dd-agent/checks.d/docker.py:ro -e API_KEY=YESOFCOURSE datadog/docker-dd-agent
```

and the file exists:
```shell
root@7e0dd1a8ae58:/# ls -al /etc/dd-agent/conf.d/
total 20
drwxr-xr-x 2 root root 4096 Oct  6 11:55 .
drwxr-xr-x 4 root root 4096 Oct  6 11:55 ..
-rw-r--r-- 1 root root 1082 Oct  6 11:55 disk.yaml
-rw-r--r-- 1 root root 2403 Oct  6 11:55 docker_daemon.yaml
-rw-r--r-- 1 root root 2651 Oct  6 11:55 elastic.yaml
```

and contains:

```yaml
init_config:

  docker_root: /host

instances:

  - url: "unix://var/run/docker.sock"

    new_tag_names: true
    collect_images_stats: false

```

**Comment by hkaj** [comment]
Thanks for sending the info so quickly @satblip.
I'm not sure why you share `/etc/dd-agent/checks.d/docker.py` with the container. Maybe `/etc/dd-agent/checks.d/docker_daemon.py` would be better if you copied the `docker_daemon.py` check in `/etc/dd-agent/checks.d/` on the host.

If `docker_daemon.py` isn't there, that's the issue. To confirm that could you share the result of `ls -al /opt/datadog-agent/agent/checks.d` on the agent container here please? If you're running the latest version of the agent, `docker_daemon.py` should be here.

**Comment by hkaj** [comment]
Also for many container metrics, the agent needs to read files in `/proc/`, so instead of mounting `/proc/mounts:/host/proc/mounts:ro` you should mount `/proc:/host/proc:ro`. We updated that quite recently, and the `info` command will show you a warning about that once the check is running correctly.

**Comment by satblip** [comment]
Hi @hkaj,

Thanks to what you've pointed, we've figure out that we were still using an old `docker.py` custom script.

That script was sending data with “image_repository” tag which has now changed to “image_name” so we had to update our charts json.

So problem solved, thanks for the heads up ;)
