### ISSUE TITLE
Make directory check works on Windows

### ISSUE THREAD

**Issue by xkrt** [DataDog/dd-agent#1969]
http://docs.datadoghq.com/integrations/directory/ does not work on Windows now.

**Comment by xkrt** [comment]
I have just run shell.exe with:
```
>>> from checks import run_check
>>> run_check('directory')
```
and got proper metrics.

Why `directory.py` marked as not Windows-supported?

**Comment by irabinovitch** [comment]
@yannmh thoughts on this one?
