### ISSUE TITLE
Run only service checks, no host metrics collection

### ISSUE THREAD

**Issue by adrienkohlbecker** [DataDog/dd-agent#1970]
Hello,

Is there a way to launch an agent that collects only service checks, no host metrics ?
My use case is the following:
- I have dd-agent installed on my cluster nodes, every node is the same, and the agents collect metrics at the host level.
- I need to run a docker container on my cluster, that would collect postgres/redis metrics and some custom checks. Of course the cluster is already monitored so I don't need cpu/ram/etc metrics inside this container.

Any way to do that ?
Best

**Comment by hkaj** [comment]
Hi @adrienkohlbecker,

You can replace `.default` with `.example` for the config files that have the `default` extension (by default they're in `/etc/dd-agent/conf.d/`). This will prevent them from running (don't forget to restart the agent for the change to happen). Regarding CPU and RAM though there's currently no clean way to disable their collection as they are collected in a core check. I suggest you just ignore them, that's not a lot of data and we don't charge more for their collection.

Let me know if that helps.

**Comment by irabinovitch** [comment]
@adrienkohlbecker Hi Adrien, Did the above suggestion help resolve the issues you were experiencing?

**Comment by adrienkohlbecker** [comment]
Hello, thanks for getting back to me on this.
So we've deployed the container with the postgres/redis checks. The only issue we have is that this container is billed as a separate host.

**Comment by remh** [comment]
@adrienkohlbecker Can you reach out to our support team regarding the billing issue please ?
Meanwhile i'm closing this issue.
