### ISSUE TITLE
3.18 kernel detection breaks ansible service hooks

### ISSUE THREAD

**Issue by wyaeld** [DataDog/dd-agent#1976]
a5dda4a19a1a6c71d1ceecf7a665c1ea7d928a4d by @JohnLZeller appears to be solving a problem related to overlayfs and the kernel.

However not everyone on 3.18 is using overlayfs.  This check is creating a new problem.

The ansible-datadog role, https://github.com/DataDog/ansible-datadog uses the ansible core module for service management here https://github.com/DataDog/ansible-datadog/blob/master/tasks/main.yml#L20

This commit breaks it, since the service module expects an output it doesn't get on the `info` call.

I'm using 14.04.3 LTS Ubuntu, nothing to do with CoreOS and OverlayFS

**Comment by JohnLZeller** [comment]
@wyaeld thanks for reporting this! We will take a look.

**Comment by remh** [comment]
@olivielpeau can you take a look please ?

**Comment by aster1sk** [comment]
A temporary/hacky solution (I was tasked with a bulk-deployment today) is to modify line 20 [here](https://github.com/DataDog/ansible-datadog/blob/master/tasks/main.yml#L20)

EC2 AMI : 

`- shell: sudo chkconfig datadog-agent on`
`  sudo: yes`

Debian/Ubuntu :

`-shell: update-rc.d datadog-agent defaults`
`  sudo: yes`

Also add another block to start the agent : 

`- shell: service datadog-agent start`
`  sudo: yes`
`  when: datadog_enabled`

**Comment by remh** [comment]
Thanks for the workaround @aster1sk !

**Comment by olivielpeau** [comment]
Found the original cause of the issue (see #1988).

Until the fix is shipped another workaround could be to use the `pattern` option of the `service` module by changing https://github.com/DataDog/ansible-datadog/blob/a8398ab8b13069c6dfd91aa658cd06146309a0b7/tasks/main.yml#L20 to:
```
- service: name=datadog-agent state=started enabled=yes pattern=/opt/datadog-agent/bin/supervisord
```
