### ISSUE TITLE
[mcache] report `listen_disable_num`

### ISSUE THREAD

**Issue by alaz** [DataDog/dd-agent#1977]
I propose to report `listen_disable_num` value from Memcached statistics. It's of much value when diagnosing connection errors, etc. [memcached Wiki](https://code.google.com/p/memcached/wiki/Timeouts) recommends consulting this value at the first when troubleshooting timeouts. So it would make sense to monitor the increase of such events.

**Comment by hkaj** [comment]
Hi @alaz, thanks for your input! That seems to be something useful we could improve indeed, I add this to our backlog.
Stay tuned.
