### ISSUE TITLE
Latest RPM is missing commits

### ISSUE THREAD

**Issue by nsheridan** [DataDog/dd-agent#1981]
The latest datadog-agent RPM, 5.5.1, does not contain https://github.com/DataDog/dd-agent/commit/5abbb7d0b3fef3f5139e2603c05d65990343291d. Use of netstat is causing excessive cpu usage on machines with many connections when I enable `collect_connection_state` in the config.

**Comment by nsheridan** [comment]
That commit is not present when I browse the repo at the `5.5.x` tag: https://github.com/DataDog/dd-agent/blob/5.5.x/checks.d/network.py#L123
I wonder what else is missing.

**Comment by remh** [comment]
Thanks for the feedback @nsheridan 

The commit you are pointing was part of PR #1859 

This PR was merged after our 5.5.0 release and will go out with our 5.6.0 release as we tend to only include bug fixing commits in our minor releases.

In the mean time you can start using the new version of the check by downloading this file: https://raw.githubusercontent.com/DataDog/dd-agent/master/checks.d/network.py into your /etc/dd-agent/checks.d directory and restarting your agent.

As it's not a code issue as such, i'm closing it. 
Thanks again for the feedback!
