### ISSUE TITLE
Monitoring and Dual-Stack

### ISSUE THREAD

**Issue by rmoriz** [DataDog/dd-agent#1992]
Hi,

while we have several services exposed via IPv4 and IPv6, we're only seeing IPv6 monitoring requests by the dd-agent, e.g. http_check. This preference is probably caused by the Kernel/OS (Debian 8).

However it would be very nice to be able to:
- configure dd-agent to use IPv4 or IPv6 for each monitoring instance separately
- test both ways by default (if IPv6 is enabled and DNS returns IPv6 and IPv4)

**Comment by remh** [comment]
Thanks a lot for the feedback @rmoriz . It looks like the python requests library we use doesn't support this to be done. It could be done by monkey patching it as described here http://stackoverflow.com/questions/33046733/force-requests-to-use-ipv4-ipv6 . But that could break anytime unfortunately.


So i'm going to close this issue for now until a better implementation is proposed. 
Thanks again for the feedback!
