### ISSUE TITLE
[mongo] Configure to inspect collections

### ISSUE THREAD

**Issue by jmkgreen** [DataDog/dd-agent#2017]
We need to alarm based on the count of documents in particular collections. I am not seeing a way of doing this at present, although the [Mongo API] (https://docs.mongodb.org/manual/reference/command/collStats/) appears there.

Is this something that the supplied agent should be held responsible for? I imagine a company with a lot of collections may object if they have to maintain custom metrics covering these themselves given the limits of the service.

**Comment by yannmh** [comment]
Apologies for the late answer @jmkgreen,

I see two options to achieve this through Datadog Agent.

1. Instrument the MongoDB check with a new, optional, `collections` parameter.

  The `mongo.yaml` YAML configuration file would have a new section like
  ```
  # The optional `collections` parameter instructs the check to collect additional metrics 
  # for the given collections.
  collections:
    - my_first_collection
    - another_collection
  ```
  that instructs the check to collect `collStats` metrics (among which, the sizes), for the given list of   collections.


2. (Or) Discover the list of collections and collect `collStats` metrics on all of them.

  Preferable over 1, if this does not have any slow down impact on the check. We could potentially move   this behavior behind a new [`additional_metrics` flag](https://github.com/DataDog/dd-  agent/blob/master/conf.d/mongo.yaml.example#L23-L37)


What do you think @jmkgreen ?

Yann

**Comment by jmkgreen** [comment]
While the second option may be easier for end users, we would require control over which collections to scan for performance reasons.

This requirement comes from ISO-27000 which asks us to document how our auditing controls are planned to prevent business disruption. An automated scan of a collection which might be observed as a slow-down by other parties definitely falls into this category.

**Comment by yannmh** [comment]
Thanks for the further explanations @jmkgreen. 

I am moving this feature to triage for now, so it can considered/scheduled for an upcoming agent release. We'll keep you informed of any updates.

**Comment by yannmh** [comment]
Fixed with https://github.com/DataDog/dd-agent/pull/2739

**Comment by gmmeyer** [comment]
`mongodb.collection.count` is the metric that will be collected.

**Comment by eyumay** [comment]
Hi All,
I have an issue which a bit similar to the one being discussed here. Im trying to create a datadog monitor that should gather data (like name & id) from MySQLDB, which lives on a different box than the MongoDB, and (additional field from MongoDB based on id from mysqldb). Script should put these data together and send it over to datadog.

Any idea how this could be achieved?

**Comment by gmmeyer** [comment]
Hey @eyumay! Thanks for the question! You should contact support at support@datadoghq.com, they will be able to help you out. 😃
