### ISSUE TITLE
[docker_daemon] Log noise due to short-lived processes

### ISSUE THREAD

**Issue by oeuftete** [DataDog/dd-agent#2074]
The `_crawl_container_pids` method grabs a list of pid dirs, then iterates over them looking for docker container IDs.  However, if a process completes between the list grabbing and the `/proc/xxx/cgroup` read, a warning is generated:

```text
 WARNING (__init__.py:649): Cannot read /proc/123842/cgroup : [Errno 2] No such file or directory: '/proc/123842/cgroup'
```

We see a large number of these a day.  A little bit of detective work suggests these processes are `iostat` and `mpstat` executions by the agent which exit very quickly as these tools aren't installed on the hosts in question.  Edit: Even with all tools installed, this warning is frequently coming up, likely for these processes.

**Comment by olivielpeau** [comment]
Thanks again @oeuftete for fixing the issue, your fix will go out with the 5.7.0 release.

Closing the issue.
