### ISSUE TITLE
[core] Missing histogram support for log parser (dogstreams)

### ISSUE THREAD

**Issue by sserbin** [DataDog/dd-agent#2099]
It seems that only 'gauge' and 'counter' metrics types are supported at the moment:
https://github.com/DataDog/dd-agent/blob/dde38478c64e740e7a17a35d478152696927ef63/checks/datadog.py#L329

Documentation also lacks this information.

**Comment by remh** [comment]
Thanks for the feedback @sserbin 
We are currently evaluating new options to replace dogstream and we likely won't add new features to the current implementation unfortunately, so i'm going to close this issue. Feel free to reply or to reach out to our support team if you have more questions.

Thanks again for the feedback!

**Comment by roelvanduijnhoven** [comment]
What is the status of the replacement for dogstreams? I am also missing histograms; and can not find any way to do something with it.

**Comment by olivielpeau** [comment]
@roelvanduijnhoven We've recently introduced support of logs in Datadog, see the announcement here: https://www.datadoghq.com/blog/announcing-logs/ (currently in public beta)

See also https://docs.datadoghq.com/logs/ for the docs on the support of logs on the agent side.

**Comment by roelvanduijnhoven** [comment]
@olivielpeau thanks, I subscribed for the beta!

Am I correct that I can use this to generate graphs in DataDog regarding NginX request rate, average response times and such?

**Comment by olivielpeau** [comment]
@roelvanduijnhoven: not sure what your exact use case is, but if you're interested in pulling these metrics from nginx you should be able to use our existing nginx integration: see https://github.com/DataDog/integrations-core/tree/master/nginx

**Comment by roelvanduijnhoven** [comment]
These do not include average response times; and some other metrics that you can get from parsing the logs.

@olivielpeau Is there any way I can test the new Datadog program already? :)

**Comment by olivielpeau** [comment]
Oh I see, thanks for the explanation!

There's a link to a signup form at the end of the announcement at https://www.datadoghq.com/blog/announcing-logs/ (-> https://www.datadoghq.com/log-management/), feel free to apply to the public beta through that form!

**Comment by roelvanduijnhoven** [comment]
Thanks @olivielpeau. 

> There's a link to a signup form at the end of the announcement at 

Did that; but no response yet! Thanks anyway.
