### ISSUE TITLE
datadog agent is possible multi network interface?

### ISSUE THREAD

**Issue by leechunghwan** [DataDog/dd-agent#2105]
Hi,

when an instance has network issues, 
the agent forwarder can't submit multiple network interfaces to datadog's servers. 

Is it possible network multi- interface?
(It does not seem to support multiple interfaces.)

only total bytes received/sent through a network adapter.

**Comment by irabinovitch** [comment]
@leechunghwan apologies for the delay in reply. This sounds like a question our support team might be better able to help you answer. Have you had a chance to open a ticket?

**Comment by remh** [comment]
Closing this issue as we didn't hear back.
