### ISSUE TITLE
consul reports incorrect node count

### ISSUE THREAD

**Issue by wwalker** [DataDog/dd-agent#2113]
checks.d/consul.py reports the number of results that is returned by ```/v1/catalog/<service name>```.

catalog returns all the configured servers, whether they are functional or not.

Instead, it should use the endpoint ```/v1/health/checks/<service name>```; and verify the Status is passing.

**Comment by talwai** [comment]
Thanks for reporting @wwalker , we have a fix queued here that should make it to our next bugfix release: https://github.com/DataDog/dd-agent/pull/2018

**Comment by remh** [comment]
Was fixed in 5.6.3
