### ISSUE TITLE
Incorrect memory for centos 7

### ISSUE THREAD

**Issue by benpillet** [DataDog/dd-agent#2118]
[root@server.prod ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7566         261         212         248        7092        6784
[root@server.prod ~]$ sync && echo 3 > /proc/sys/vm/drop_caches
[root@server.prod ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7566         247        7016         248         302        6952

In the graph generated for this box, system.mem.used goes from 7.16 GiB to 0.67 GiB.  It looks like the calculation for used isn't getting created correctly.  Here is shows how system.mem.used is calculated: https://github.com/DataDog/dd-agent/wiki/Metricspedia  I think there should be an additional metric added for the available column as listed above. I ran into this with graphite and some other metrics systems before.  It's quite annoying to have to figure out how much memory is actually available on the box once the kernel releases buffers and caches.

**Comment by Surgo** [comment]
me too :cold_sweat:

**Comment by remh** [comment]
@benpillet @Surgo Thanks for the feedback!

This is already the case.
If you are running version 5.6.0 or higher 
`system.mem.usable` will show you the available column.

See https://github.com/DataDog/dd-agent/pull/1993/files for more details.

Closing.
