### ISSUE TITLE
[mongo] Add support for mongodb 3.2 metrics

### ISSUE THREAD

**Issue by benmccann** [DataDog/dd-agent#2125]
MongoDB 3.2 is just about to come out (it's currently at 3.2.0-rc6). It'd be worth installing that on a machine and adding any new metrics that mongo now exposes - it always adds new metrics with each new version. The MongoDB drivers have been enhanced with a new API that exposes query performance metrics to APM tools.

**Comment by yannmh** [comment]
Thanks for the information @benmccann. 

MongoDB 3.2 is now out since 8 December 2015. I am adding a card in our backlog so we can review the new changes and bring the new metrics to the check accordingly.

**Comment by yannmh** [comment]
Hi @benmccann,

We brought many updates to the MongoDB check over the last releases of the Datadog Agent, specifically in the `5.7.4` release. More details are available in the [CHANGELOG](https://github.com/DataDog/dd-agent/blob/master/CHANGELOG.md) 📝 .

Are there any other metrics you had in mind ? If not, I'll close this issue.

Yann

**Comment by benmccann** [comment]
The updates brought the DataDog agent up to feature parity with MongoDB 3.0. I have not upgraded to MongoDB 3.2 yet, so cannot check what metrics might be new in 3.2. I would guess that there are new metrics that the agent doesn't support yet, but can't name specific ones without installing MongoDB 3.2. That would be a nice thing for someone to check.

**Comment by yannmh** [comment]
Thanks @benmccann,

I am closing this issue for now: let's reopen it if any of those new metrics arouse interest.
