### ISSUE TITLE
tomcat.yaml.example formatted incorrectly 

### ISSUE THREAD

**Issue by gzysk8** [DataDog/dd-agent#2131]
Using the example file as it is currently will result in the following error:

```
ERROR | Instance | Error while trying to match attributeInfo configuration with the Attribute: 
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
```

It appears that this section (https://github.com/DataDog/dd-agent/blob/master/conf.d/tomcat.yaml.example#L67-#L82) is missing the `attribute` key and the `hitsCounts` attribute should be `hitsCount`

After making the changes, these lines should look like this:

    - include:
        type: Cache
        attribute:
          accessCount:
            alias: tomcat.cache.access_count
            metric_type: counter
          hitsCount:
            alias: tomcat.cache.hits_count
            metric_type: counter
    - include:
        type: JspMonitor
        attribute:
          jspCount:
            alias: tomcat.jsp.count
            metric_type: counter
          jspReloadCount:
            alias: tomcat.jsp.reload_count
            metric_type: counter

**Comment by remh** [comment]
Thanks @gzysk8
