### ISSUE TITLE
Cannot find Docker cgroup directory. Be sure your system is supported.

### ISSUE THREAD

**Issue by bakins** [DataDog/dd-agent#2137]
Running docker 1.8.3 on Ubuntu 14.04. Running dd-agent under Kubernetes.  Kept getting the error message in the subject until I made a patch to 5.6.2 https://gist.github.com/bakins/00cc12f26e2947af6679

I am not running the packaged version of docker (ie, the deb) - just the binary (issues with Kubernetes for me using packaged version).

**Comment by remh** [comment]
Thanks for the feedback and the patch @bakins
Going to add this new directory to the Agent.

**Comment by bakins** [comment]
Thanks!

**Comment by bakins** [comment]
Thanks!
