### ISSUE TITLE
Consul send_events config entry not in example

### ISSUE THREAD

**Issue by jhaals** [DataDog/dd-agent#2151]
Hi,

`send_events` config entry is missing from the example configuration(https://github.com/DataDog/dd-agent/blob/master/conf.d/consul.yaml.example
) 

```  consul
    ------
      - instance #0 [ERROR]: "'send_events'"
      - Collected 0 metrics, 0 events & 1 service check
```

```
  File "/etc/dd-agent/checks.d/consul.py", line 15, in check
    send_events = instance['send_events']
KeyError: 'send_events'
```

**Comment by remh** [comment]
@jhaals Thanks for the feedbac!

Looks like you are using a custom version of the consul check (if it's located in `/etc/dd-agent/check.d/`, it's a custom check. Official checks are located in `/opt/datadog-agent/agent/checks.d/`

The latest released version of the consul check doesn't have a `send_events` config entry:
https://github.com/DataDog/dd-agent/blob/5.6.x/checks.d/consul.py

Closing
