### ISSUE TITLE
[mysql] Unable to calculate query cache utilization percentage.

### ISSUE THREAD

**Issue by patricknelson** [DataDog/dd-agent#2173]
I'm fairly new to Datadog in general but I believe this is currently not possible with the built-in `mysql.py` check script. The query cache utilization percentage is calculated as *total* number of cache hits divided by the sum of both hits + inserts into the query cache. Or: 

```
Qcache_hits / (Qcache_hits + Qcache_inserts)
```

However, I think that currently [mysql.py](https://github.com/DataDog/dd-agent/blob/master/checks.d/mysql.py) doesn't allow you gather this information for the following reasons:

* It is gathering hits as a rate instead of as a gauge (`Qcache_hits` aliased as `mysql.performance.qcache_hits`)
* It is not collecting `Qcache_inserts` at all.

Proposed solution:

* Not sure if this is the best solution (or necessary), but: Since `mysql.performance.qcache_hits` is already being gathered and likely being used by many people, I'd suggest adding a new metric such as  `mysql.performance.qcache_hits_total` to prevent totally jacking up existing dashboards & etc.
* Start gathering total `Qcache_inserts` as `mysql.performance.qcache_inserts_total`.

What do you guys think? Is it possible to get the information needed out of `mysql.performance.qcache_hits` without adding a new metric to the mix? I think it is since frequently "hit" cache entries may have been inserted a long time ago (prior to the current window of time being viewed) meaning we need totals and not a rate, since the server could have restarted 1yr ago (etc).

**Comment by remh** [comment]
Thanks for the feedback @patricknelson 

Unfortunately this won't work, if we collect both `mysql.performance.qcache_hits_total` and `mysql.performance.qcache_inserts_total` and compute the query cache utilization based on them you'll actually graph the average query cache utilization since the server started (or the last reset).

I think what we should do:
- Add the Qcache_inserts as a rate (as it's an interesting metric)
- Manually compute in the agent the utilization by storing the previous iteration values. This way this would represent the "instant" query cache utilization

Does that seem reasonable to you ?

@truthbk could you add that to your rework of the mysql integration please ?

**Comment by patricknelson** [comment]
Hmm, it seems that it's popular to also include `Qcache_not_cached` as well when calculating this sort of rate. Google-fu tells me this percentage is then:

```
(Qcache_hits / (Qcache_hits + Qcache_inserts + Qcache_not_cached) ) * 100
```

Anyway, I'm not sure, since you're actually going to be logging these numbers (`mysql.performance.qcache_hits_total` and `mysql.performance.qcache_inserts_total`) every minute or so. If you setup a graph based on these numbers, yes -- you will just see a number climbing over time, however that isn't the end goal anyway. I figure these would be ultimately calculated in the graph pane under the "Graph these queries as" field in DataDog like `(a / (a + b + c) ) * 100`.  In this case, it will go up or down since `a` cancels out to 1 but will always grow, just like the inserts (`b`) and the idea is to measure these relative differences over time (so you're not **really** seeing the totals, once you drop in the simple formula).

The reason this is important is because of *how* inserts work. Inserts can expire over time. Hits *always* happen after an insert (i.e. the hits number will never increment until after an insert has occurred that it matches). Therefore, if I have an insert at time 0 (my server uptime is 0 minutes old) and then I have a hit on it immediately, great. Then say my cache is an LRU cache (least recently used) is configured to expire after say 10 minutes. Then, I have at least 1 hit within that 10min time span for 7 days in a row on that particular insert and I only ever had 2 inserts during that 7 day period, what is my cache utilization? It's 50%, but if I'm only looking at instant data (or say over past 10min window), it's "undefined" because I'm dividing by zero (i.e. zero inserts over the past 1min but 1 hit, that doesn't make any sense). However, using totals, over the 7 day period of my server being online I've had 2 inserts and 

Am I misinterpreting what you're saying? Anyway, that's why I think we need totals.

**Comment by patricknelson** [comment]
**Side note:** Interestingly from what I'm reading under MySQL docs, even though I see it's popular to factor the `Qcache_not_cached` status variable into the bottom part of that equation, even though I'm *really* not sure what the justification is. It appears to not have anything to do with hit ratio we're interested in:

http://dev.mysql.com/doc/refman/5.7/en/server-status-variables.html#statvar_Qcache_not_cached

I could be wrong, but why does it matter that a particular select wasn't cached if I'm only interested in hits? Hits will only ever be on cacheable statements and naturally only cacheable statements will be inserted. Ergo why involve non-cached queries???

**Comment by truthbk** [comment]
Hi @patricknelson,

I think we can do this and submit metrics to represent both the Qcache utilization over time, as you suggest, and the instantaneous value for it as I believe the overlay of both metrics could actually provide some valuable information as to how we're utilizing the cache at the present time in comparison to how it had been used through-out the entire server uptime. 

I'm going to try to read a bit more on whether or not we should include the `Qcache_not_cached` value in our `calcuations` for both these new metrics.

**Comment by patricknelson** [comment]
Ok cool. Personally I don't mind as long as I can get totals that have accumulated over time, because I can easily calculate what I need from that (graphed minute by minute).

**Comment by truthbk** [comment]
We have added these metrics as discussed in #2116. Closing! Thanks for the input @patricknelson
