### ISSUE TITLE
Kafka example config is non-sensical

### ISSUE THREAD

**Issue by thieman** [DataDog/dd-agent#2178]
The [example configuration for the Kafka integration](https://github.com/DataDog/dd-agent/blob/master/conf.d/kafka.yaml.example) proudly declares the following above its default metrics configuration:

```
# Metrics collected by this check. You should not have to modify this.
```

Most of the metrics defined below this then go on to capture the `MeanRate` attribute from each of the beans. This attribute reports the average value for that metric over **the lifetime of the process.** If you have a long-running process, which I imagine most Kafka installations will be, this number is completely meaningless. Every human on Earth could be hitting my cluster with requests right now and that metric would barely move because my Kafka instance has been running for months.

These `MeanRate` attributes should probably be changed to something more useful like `OneMinuteRate`, `FiveMinuteRate`, or `FifteenMinuteRate`.

![](http://25.media.tumblr.com/tumblr_lsxk1ndn7W1r2vs7so3_r3_500.gif)

**Comment by remh** [comment]
Hi @thieman . Thanks for the feedback!

There is already an open PR aiming at fixing the same issue #2079 

Can you weigh in this pull request please ?
I'm closing this pull request.

Thanks again for the feedback
