### ISSUE TITLE
[elasticsearch] Add / remove metrics for 2.x

### ISSUE THREAD

**Issue by bdharrington7** [DataDog/dd-agent#2186]
This would involve logic for *not* adding certain stats if the version of Elasticsearch is >= 2.x.x

A (probably not exhaustive) list of stats changes can be found here: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_stats_info_and_literal_cat_literal_changes.html

**Comment by olivielpeau** [comment]
Thanks for opening the issue @bdharrington7.

After a quick look it seems that the `fs.*.disk*` are the only affected metrics that are currently fetched by the check, i.e.:
```
elasticsearch.fs.total.disk_reads
elasticsearch.fs.total.disk_writes
elasticsearch.fs.total.disk_io_op
elasticsearch.fs.total.disk_read_size_in_bytes
elasticsearch.fs.total.disk_write_size_in_bytes
elasticsearch.fs.total.disk_io_size_in_bytes
```

Do you have info/experience on metrics that have been added in elasticsearch 2.0+ ?

**Comment by bdharrington7** [comment]
I haven't played with it, I just opened this issue as more of a bookmark / reminder :)

-Brian
