### ISSUE TITLE
checks.http_check(http_check.py:239) | Incorrect HTTP return code. Expected (1|2|3)\d\d, got 403

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#2190]
It seems that list INFO message is incomplete which makes it totally useless. We have more than 20 tests inside the http_check and if this like appears without telling which instance from the http_check caused this, it makes the entire message useless.
```
checks.http_check(http_check.py:239) | Incorrect HTTP return code. Expected (1|2|3)\d\d, got 403
```

**Comment by talwai** [comment]
Thanks for reporting @ssbarnea . Fair, that log message could certainly be more helpful. Queueing it up, should be a simple fix.
