### ISSUE TITLE
MongoDB: replset.health check not properly designed

### ISSUE THREAD

**Issue by JayJayM** [DataDog/dd-agent#2209]
For the [replSet.health] (https://github.com/DataDog/dd-agent/blob/master/checks.d/mongo.py#L127) gauge in MongoDB:

According to [MongoDB doc](https://docs.mongodb.org/manual/reference/command/replSetGetStatus/#replSetGetStatus.members[n].health), ```replSetGetStatus.members[n].health value is only present for the other members of the replica set (i.e. not the member that returns rs.status). This field conveys if the member is up (i.e. 1) or down (i.e. 0).```

It looks like it checks the health of the **other** hosts.
Moreover, maybe it should be a service check rather than a metric.

Also we might consider using [replSetGetStatus.members.state](https://docs.mongodb.org/manual/reference/command/replSetGetStatus/#replSetGetStatus.members.state) which looks like to be more relevant. here are [the different possible states] (https://docs.mongodb.org/manual/reference/replica-states/): 8 = down.

Is it already in the [replset.state](https://github.com/DataDog/dd-agent/blob/master/checks.d/mongo.py#L129) metric?

**Comment by yannmh** [comment]
Thanks for the inquiry @JayJayM.

1. I agree, a service check seems more appropriate than a metric in this case. 
2. :+1: for considering [replSetGetStatus.members.state](https://docs.mongodb.org/manual/reference/command/replSetGetStatus/#replSetGetStatus.members.state) over `replSetGetStatus.members[n].health`

Adding a card in our backlog so we can consider these changes in a future release.

**Comment by yannmh** [comment]
The `replSetGetStatus.members.state ` is currently sent via a `mongodb.replset.state` metric.

I am closing this issue.
