### ISSUE TITLE
PIP install in source setup script borked

### ISSUE THREAD

**Issue by mooney6023** [DataDog/dd-agent#2217]
$dl_cmd $dd_base/get-pip.py https://raw.github.com/pypa/pip/master/contrib/get-pip.py >> $logfile 2>&1

that URL now outputs:

#!/usr/bin/env python
import sys

def main():
    sys.exit(
        "You're using an outdated location for the get-pip.py script, please "
        "use the one available from https://bootstrap.pypa.io/get-pip.py"
    )

if __name__ == "__main__":
    main()

**Comment by olivielpeau** [comment]
Hi @mooney6023, thanks for opening this issue!

I've reproduced the error, a fix is on its way.

**Comment by mooney6023** [comment]
I blame the pip guys :)

**Comment by mooney6023** [comment]
fix verified functional on my end
