### ISSUE TITLE
Allow custom delay between two http checks

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#2221]
It seems that dd-agent will perform all the http_checks every minutes but this may not be desired as it may hammer the servers with requests and we would like to be able to specify a custom time interval for performing these, like 120 seconds, or even 300.

**Comment by irabinovitch** [comment]
@ssbarnea Thanks for the note and feedback. Have you tried altering min_collection_interval in your configuration file?  More details are available over in our [knowledge base](http://help.datadoghq.com/hc/en-us/articles/203557899-How-do-I-change-the-frequency-of-an-agent-check-)

**Comment by olivielpeau** [comment]
@ssbarnea: As mentioned by @irabinovitch using `min_collection_interval` should allow you to customize how often each check/instance of a check is run.

Closing this issue, but feel free to add a comment if you're still experiencing issues.

**Comment by tklo** [comment]
@olivielpeau , how that solves the issue? If I have to checks and set min_collection_interval of one to the odd number of seconds, and second to the even number of seconds. What, however, if I have 20 checks? How can I execute 20 http checks one by one and ensure that they're won't be executed in the same time?
