### ISSUE TITLE
[gunicorn] Add more metrics for versions of gunicorn 19.1 and higher

### ISSUE THREAD

**Issue by danielrmeyer** [DataDog/dd-agent#2222]
Currently the gunicorn integration only collects metrics on the number of workers.  In gunicorn 19.1 more instrumentation has been added per the following docs:
http://docs.gunicorn.org/en/stable/instrumentation.html

It would be be very helpful if the gunicorn integration reported on those metrics for gunicorn 19.1 and beyond.

**Comment by alq666** [comment]
Hi @danielrmeyer, I'm the one behind that instrumentation in 19.1. Back then I wanted to make it easy to instrument gunicorn with 2 requirements:

1. using the `--statsd-host=localhost:8125` option on the command line for gunicorn
1. using a statsD client

As such, you can get the best of both worlds by running gunicorn with that extra command line option, and running our check.

The native statsD instrumentation of gunicorn does not collect % of time spent servicing requests, which our gunicorn check tracks so in a sense, running both gives you maximum coverage. I have plans to revisit the `gunicorn.instrumentation.statsd` to add that at some point but no firm dates yet.

I hope this makes sense.

**Comment by danielrmeyer** [comment]
@alq666 Thanks for the information.  I am still having some trouble getting this going.  It appears I have everything running right but these metrics are not getting logged (still just seeing the number of worker metric from the check but nothing from statsd)

I have my gunicorn server running with the --statsd-host=localhost:8125

I verified that dogstatd is running and that it is listening on port 8125 from the logs.

Output from ```sudo service datadog-agent info```:
```
===================
Dogstatsd (v 5.6.3)
===================

  Status date: 2016-01-22 18:28:12 (1s ago)
  Pid: 21553
  Platform: Linux-3.13.0-61-generic-x86_64-with-debian-jessie-sid
  Python Version: 2.7.10
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 18
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0```

From /var/log/datadog/dogstatsd.log:
```2016-01-22 17:50:52 UTC | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:279) | Listening on host & port: ('localhost', 8125)```

I am running gunicorn with this command (verified its running and able to hit the app):
```sudo -E gunicorn --statsd-host=localhost:8125 --reload -b 0.0.0.0:80 app.api:app```

Is there some other setup I am missing for this?  Any recommendatons

**Comment by danielrmeyer** [comment]
Also, I just upgraded to gunicorn 19.4.5 and still not seeing the metrics

**Comment by alq666** [comment]
@danielrmeyer I ran 19.4.5 with the following example application and was able to get metrics

```bash
gunicorn --workers=2 --statsd-host=localhost:8125 --statsd-prefix=alq test:app
```

This created a bunch of metrics called `alq.gunicorn.` visible in the Metrics explorer (it takes a minute or two usually for the drop-down to refresh with the update metric names).

If you're still hitting a wall, do you mind running a tcpdump trace and sending the results to help@datadoghq.com?

`sudo tcpdump -i eth0 -w dd-agent-2222.trace -n -v udp and host localhost and port 8125` (assuming you run on eth0).

**Comment by irabinovitch** [comment]
@danielrmeyer Per Alexis' last note, I'm going to close this but please do reach out via support if we can offer any further assistance.

"If you have questions, we’re here to help. You can get in touch with our support team by mentioning @support-datadog in a comment on Datadog itself, or by email, on IRC #datadog on irc.freenode.net, or on our customer service site."
