### ISSUE TITLE
Why is most recent zk.py version not in the most recent build (5.6.3)

### ISSUE THREAD

**Issue by paetling** [DataDog/dd-agent#2233]
Looking at the version of zk.py that is in the master branch I see that it emits metrics around: `zookeeper.instances`.   I wanted to use this feature in the zk integration, but I found that the code (which seems to have been added on 2015-07-14) was not included in the most recent build (2015-11-10).  I was wondering why this was the case?  Is it due to backwards incompatible changes and you are waiting for a bigger version change to update it?   Or is this code somehow unsafe or untested?

**Comment by olivielpeau** [comment]
Hi @paetling, thanks for opening this issue!

The changes that add the `zookeeper.instances.*` metrics have been merged into the master branch with PR #2156 on 2015-12-18, so it'll be part of our upcoming 5.7.0 release, which should be out in the next couple of weeks. The code has been tested and doesn't introduce any BC breaking change.

If you need the features of the updated check before 5.7 is released you could run it as a custom check (see http://docs.datadoghq.com/guides/agent_checks/ for more info), but in that case don't forget to switch back to the packaged check once 5.7 is released ;)

I'm going to close this issue, but feel free to comment on it if you still have questions!

**Comment by paetling** [comment]
Thanks.
