### ISSUE TITLE
Docker dd-agent getting weird error on ecs

### ISSUE THREAD

**Issue by posix4e** [DataDog/dd-agent#2247]
016-02-04 02:52:08 UTC | WARNING | dd.forwarder | transaction(transaction.py:213) | Transaction 15 in error (2 errors), it will be replayed after 2016-02-04 02:52:48
2016-02-04 02:52:28 UTC | ERROR | dd.forwarder | forwarder(ddagent.py:262) | Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://5-6-3-app.agent.datadoghq.com/intake/?api_key=*****',error=HTTPError('HTTP 599: Timeout',),headers={},reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f02f70c02d0>,request_time=20.003221035003662,time_info={})
2016-02-04 02:52:28 UTC | WARNING | dd.forwarder | transaction(transaction.py:213) | Transaction 12 in error (3 errors), it will be replayed after 2016-02-04 02:53:28

I removed my api key

**Comment by irabinovitch** [comment]
@posix4e Are you still experiencing this issue?  We're happy to help you here, but please keep in mind our support team is generally most responsive via email help@datadoghq.com.

**Comment by posix4e** [comment]
Yes I am still getting this error

**Comment by JohnLZeller** [comment]
Hey @posix4e, it's possible that this relates to a known issue, documented in our knowledge base here: http://help.datadoghq.com/hc/en-us/articles/205174285-HTTPError-HTTP-599-Timeout-appearing-in-logs

Take a look there, and let me know if that solves your problems.

**Comment by JohnLZeller** [comment]
If you could @posix4e, would you [send a flare to support](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support-using-flare). We'll continue troubleshooting from there.

**Comment by posix4e** [comment]
Please enter your email: posi@planet.com

2016-02-09 17:25:52,085 | INFO | dd.collector | utils.flare(flare.py:177) |
Uploading /tmp/datadog-agent-2016-02-09-17-20-16.tar.bz2 to Datadog Support

The upload failed:

Your request is incorrect: This case (2247) is not yours

root@de499a14eb06:/#

On Tue, Feb 9, 2016 at 6:13 PM John Zeller <notifications@github.com> wrote:

> If you could @posix4e <https://github.com/posix4e>, would you send a
> flare to support
> <https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support-using-flare>.
> We'll continue troubleshooting from there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DataDog/dd-agent/issues/2247#issuecomment-181961934>.
>
-- 
Sent from my mobile 4045076749
Alex Newman

**Comment by JohnLZeller** [comment]
ah, leave the case_id blank, that's a zendesk id, not github. You should be good to just run `sudo /etc/init.d/datadog-agent flare`

**Comment by posix4e** [comment]
2016-02-09 17:35:46,034 | INFO | dd.collector | utils.flare(flare.py:177) |
Uploading /tmp/datadog-agent-2016-02-09-17-35-40.tar.bz2 to Datadog Support

2016-02-09 17:35:51,494 | INFO | dd.collector | utils.flare(flare.py:575) |
Your logs were successfully uploaded. For future reference, your internal
case id is 44936

root@de499a14eb06:/#

On Tue, Feb 9, 2016 at 6:32 PM John Zeller <notifications@github.com> wrote:

> ah, leave the case_id blank, that's a zendesk id, not github. You should
> be good to just run sudo /etc/init.d/datadog-agent flare
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DataDog/dd-agent/issues/2247#issuecomment-181972050>.
>
-- 
Sent from my mobile 4045076749
Alex Newman

**Comment by irabinovitch** [comment]
@posix4e Thanks Alex. We'll take a look and get back to you shortly.

**Comment by irabinovitch** [comment]
@posix4e It looks like our support team made some suggestions in the case you had open. Let us know if we can offer any further assistance.

**Comment by ssbarnea** [comment]
I don't know what is happening but it seems that this bug become the "rule". Agent is not working on ALL redhat deployments. Why to have an installer if it doesn't work.

**Comment by irabinovitch** [comment]
@ssbarnea Thanks for reaching out.  Could you send us an email to support@datadoghq.com with your logs or issue a [flare](https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command) ? We have many RHEL, Centos, and Fedora users around the globe successfully using the Datadog agent across multiple versions so I'm confident that if there is an issue our support team can help you.  

I'm going to close this ticket as based on the support ticket mentioned here the issues experienced are most certainly unrelated.
