### ISSUE TITLE
Datadog agent installation faile don Windows machine

### ISSUE THREAD

**Issue by mdamera905** [DataDog/dd-agent#2252]
I tried to use the latest datadog installer on a windows machine and at the end it does finish with "setup wizard ended prematurely" error.

I did not find any thing in Event viewer application Logs

Beginning a Windows Installer transaction: D:\ddagent-cli.msi. Client Process Id: 4980.
Ending a Windows Installer transaction: D
Product: Datadog Agent -- Installation failed.:\ddagent-cli.msi. Client Process Id: 4980
Product: Datadog Agent -- Installation failed.

Let me know is there a solution for this issue.

**Comment by yannmh** [comment]
Hi @mdamera905,

I am sorry to hear that you are experiencing issues to install Datadog Agent on Windows. 

We'd need more context to troubleshoot. Would you be able to answer to the following questions please ?
1. Which version of Windows are you using ?
2. Was it a first install or an upgrade ?
   If upgrade: 
   2.1 Which version are you upgrading from (Datadog Agent version number and 32 or 64-bit package) ? 
   2.2 Which version are you upgrading to (32 or 64-bit package) ?
   We noticed that upgrading from 32-bit↔64-bit caused similar issues in the past. 
3. Did you try to re-install after it failed ?

Thank you,

Yann

**Comment by yannmh** [comment]
@mdamera905 I did not hear back from you, are you still experiencing the issue ?

**Comment by mdamera905** [comment]
Yannmh

I have an issue in connecting to the Host, I will check and get back to ytou

**Comment by yannmh** [comment]
Thanks @mdamera905. Please feel free also to reach our support team, they are generally faster to help and troubleshoot issues.
