### ISSUE TITLE
[zookeeper] metric is misleading

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#2254]
zookeeper.bytes_receieved_per_second
zookeeper.bytes_received
zookeeper.bytes_sent_per_second
zookeeper.bytes_sent

All derive from the zookeeper internals that are counting packets, not bytes.

See https://github.com/apache/zookeeper/blob/bd9a1448f9b29859092e6bdca93da121ec166b7a/src/java/main/org/apache/zookeeper/server/ServerStats.java#L83-L89

**Comment by yannmh** [comment]
Thanks for reporting this issue @miketheman,

I am adding the ticket to our 5.8.0 milestone.

**Comment by miketheman** [comment]
@yannmh Thanks! Considering the `bytes_per_second` metrics are new and unreleased, could thse be fixed before 5.7.0 is released?

**Comment by yannmh** [comment]
That's a good point.
I'll work on a quick fix before the 5.7.0 gets released.

Thanks again
