### ISSUE TITLE
No metric for disk space on docker systems

### ISSUE THREAD

**Issue by agios** [DataDog/dd-agent#2257]
When you are running docker using devicemapper with direct lvm as your storage backend (pretty much the de facto choice today if you are running a production environment) then the available disk space is not accessible using any other metric. This is a blocker for using Datadog in a production environment with Docker.

#2159 fixes this, but apparently was not accepted because it is difficult to test it.

**Comment by yannmh** [comment]
Thanks for reporting this issue @agios,

While #2159 was closed by the contributor, we are still assessing these changes for the next 5.8.0 Datadog Agent release. We'll keep you informed as we have more updates.

Yann

**Comment by yannmh** [comment]
Fixed with #2405 which will go out with Datadog Agent `5.8.0`.
Thanks for opening the issue @agios.
