### ISSUE TITLE
Folder(Log files) Monitoring using Loggly

### ISSUE THREAD

**Issue by mdamera905** [DataDog/dd-agent#2258]
I want to monitor all the log files which are under a Particular Folder.

In Loggly I can see an option to monitor File, I want to know can we monitor all the log files under a folder ? also
if the log file changes name(including the date) then how can monitor such log files?

Please suggest

**Comment by yannmh** [comment]
Hi @mdamera905,

Would you be able to give us more details about what you are trying to achieve it, and what would be the use cases please ?

In the meantime, here are two points that might be relevant 
1. Datadog Agent's [directory check](https://github.com/DataDog/dd-agent/blob/5.6.x/conf.d/directory.yaml.example) can be used for monitoring and reporting metrics on the files for a provided directory
2. Loggly recently released a [blog post](https://www.loggly.com/blog/how-to-monitor-logs-with-loggly-live-tail-and-datadog/) on how to monitor logs with their service while submitting custom time series metric to Datadog

Please let me know if that helps.

Looking forward to hearing from you

Yann

**Comment by mdamera905** [comment]
If I need to monitor several files in the same folder, is there a trick to enable all of them with a single loggly configuration?

**Comment by yannmh** [comment]
@mdamera905 I am not quite familiar with Loggly. 
Would you mind reaching out our support team ? They'll likely be more helpful on advises.

**Comment by remh** [comment]
@mdamera905 were you able to reach out our support team ?

**Comment by yannmh** [comment]
We haven't heard back from you @mdamera905. 

I am closing this issue, please feel free to reopen it if needed.
