### ISSUE TITLE
rpm: /etc/dd-agent/supervisor.conf should be marked as config

### ISSUE THREAD

**Issue by awasilyev** [DataDog/dd-agent#2262]
Datadog agent during upgrade silently rewrites /etc/dd-agent/supervisor.conf file.
Need to be handled like config - with rpmnew/rpmsave

**Comment by olivielpeau** [comment]
Thanks @awasilyev for your feedback! We need to think about the potential downsides of declaring this file as a config file, but at first glance it looks like a good improvement.

**Comment by remh** [comment]
Unfortunately we can't do that, we need to do that as sometimes we do change the way we start the agent. 

The last time was when we moved JMXFetch to its own supervisor entry, if the supervisor file was not being overwritten JMXFetch would have stopped working for users who didn't upgrade to the newest version of `supervisor.conf`

**Comment by remh** [comment]
@awasilyev out of curiosity, what modifications are you doing on the supervisor.conf file ?

**Comment by awasilyev** [comment]
I made a custom plugin, that allows me to transfer metrics from isolated nodes to another node via amqp protocol, and add them into the supervisor.conf.

**Comment by remh** [comment]
Closing this issue. Per the reasons mentioned here https://github.com/DataDog/dd-agent/issues/2262#issuecomment-183055427 we do not support custom modifications of the supervisor.conf file (and will likely remove the need for supervisor entirely in a not so distant future)
