### ISSUE TITLE
Postgres check query incompatibility when getting pct_connections on older DBs

### ISSUE THREAD

**Issue by tamasl** [DataDog/dd-agent#2265]
datadog-agent 5.6.3
on older postgres backend (replicated on 8.3.9)

The following query fails: 
Feb 12 23:32:23 appserver postgres[31043]: [73-1] user=datadog,db=postgres ERROR:  syntax error at or near "WITH max_con" at character 2
Feb 12 23:32:23 appserver postgres[31043]: [73-2] user=datadog,db=postgres STATEMENT:
Feb 12 23:32:23 appserver postgres[31043]: [73-3] #011WITH max_con AS (SELECT setting::float FROM pg_settings WHERE name = 'max_connections')
Feb 12 23:32:23 appserver postgres[31043]: [73-4] #011SELECT SUM(numbackends)/MAX(setting) AS pct_connections, MAX(setting) AS max_connections
Feb 12 23:32:23 appserver postgres[31043]: [73-5] #011  FROM pg_stat_database, max_con
Feb 12 23:32:23 appserver postgres[31043]: [73-6] #011

And so do all subsequent queries because of being in a single transaction:
Feb 12 23:32:23 appserver postgres[31043]: [74-1] user=datadog,db=postgres ERROR:  current transaction is aborted, commands ignored until end of transaction block
Feb 12 23:32:23 appserver postgres[31043]: [74-2] user=datadog,db=postgres STATEMENT:

Rewriting the query to: 
SELECT SUM(numbackends)/MAX(setting) AS pct_connections, MAX(setting) AS max_connections FROM pg_stat_database, (SELECT setting::float FROM pg_settings WHERE name = 'max_connections') as max_con

gives the same result on 9.x and does not fail on 8.3

**Comment by remh** [comment]
Hi @tamasl 

Thanks for the feedback!

Unfortunately Postgres 8.3 has been End Of Life for 3 years now (http://www.postgresql.org/support/versioning/) so we are not planning to add support for it.

Maybe you could patch the query and run the check as a custom check ?

Meanwhile i'm going to close this issue.

Thanks again for the feedback!
