### ISSUE TITLE
Remove hardcoded /proc

### ISSUE THREAD

**Issue by gtmtech** [DataDog/dd-agent#2267]
See end of PR #2202 

"This uses a hard-coded /proc which means it won't work when running in a docker container..."

This is a regression from the work that was done to make it proc agnostic (see 2163)

**Comment by remh** [comment]
Hi @gtmtech thanks for the feedback!

It's not really a regression as it's not breaking anything ;) but i agree it should be an option!

I'll schedule this for 5.8.0 but not sure if it will make it as our 5.8.0 backlog is already big. 

We would definitely welcome a patch though.

Thanks again for the feedback!

**Comment by olivielpeau** [comment]
Fixed by #2482, scheduled for `5.9.0`
