### ISSUE TITLE
setup_agent.sh vs install_agent.sh

### ISSUE THREAD

**Issue by kenden** [DataDog/dd-agent#2337]
Why are there 2 install / setup scripts?

What is the difference between these two?
https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent/source/install_agent.sh
https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent/source/setup_agent.sh

The first has this comment
```# Datadog Agent install script.```

But nothing for the second.

A google search brought nothing, it will show this ticket soon.

**Comment by olivielpeau** [comment]
Hi @kenden!

The difference is that:
- `install_agent.sh` installs a packaged agent on Linux (from a deb or rpm package depending on the distro)
- `setup_agent.sh` installs the agent from source (pulls the code, installs dependencies, etc), and tries to support any Unix environment.

I'll add some comments on these files to make that clearer.

Thanks for your feedback!
