### ISSUE TITLE
Riak CS integration 'legend' error

### ISSUE THREAD

**Issue by millerdev** [DataDog/dd-agent#2340]
I'm getting an error after setting up the riakcs integration:

``` sh
$ dd-agent info
===================
Collector (v 5.7.1)
===================

  Status date: 2016-03-10 19:46:45 (15s ago)
  Pid: 26946
  Platform: Linux-3.13.0-79-generic-x86_64-with-debian-jessie-sid
  Python Version: 2.7.11
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======

    NTP offset: 2.5778 s
    System UTC time: 2016-03-10 19:47:01.797154

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    ... snip ...

  Checks
  ======

    riakcs
    ------
      - instance #0 [ERROR]: "'legend'"
      - Collected 0 metrics, 0 events & 2 service checks

    ... snip ...

$ riak-cs version
2.1.0


```

Relevant source line: https://github.com/DataDog/dd-agent/blob/26e811c887a48ffaedf850e00600c4beea8e0e0a/checks.d/riakcs.py#L46
Comment from basho about removing 'legend': https://github.com/basho/riak_cs/issues/764#issuecomment-138485465

**Comment by olivielpeau** [comment]
Thanks @millerdev for reporting this issue in details! This is definitely something that needs to be fixed.

Adding this to the "Triage" milestone until we assess the priority of this issue.

Feel free to open a PR if you have time to write a fix :)
