### ISSUE TITLE
Include container id in docker_daemon metrics

### ISSUE THREAD

**Issue by ejholmes** [DataDog/dd-agent#2353]
Currently, the docker_daemon check [does not include the container id](https://github.com/DataDog/dd-agent/blob/master/checks.d/docker_daemon.py#L71-L82) as a tag in the metrics that are generated. Including this would be a great addition. Adding it would be pretty straightforward, but I'm not sure if there was any reasoning behind not including it in the first place.

**Comment by olivielpeau** [comment]
Hi @ejholmes and thanks for opening this issue!

We recommend using a combination of the `image_name` and the `image_tag` tags to identify the containers.

Basically we want to avoid tagging the metrics by container ID as it would create a lot of different (and possibly short-lived) sets of tags for each metric, which would put some stress on our backend while (as far as we know) not adding much value in terms of usability.

Do you have a use-case where using the `image_name` and the `image_tag` tags does not work well?

**Comment by ejholmes** [comment]
@olivielpeau understandable. Basically, our use case is that `image_name` and `image_tag` aren't suitable for uniquely identifying a single container. We have other systems that report the container id, so this would mostly help us correlate with those systems.

We're using ECS, so in theory we're already creating a lot of short lived `container_name`'s (sorry! :)).

**Comment by olivielpeau** [comment]
Thanks @ejholmes, we'll discuss this internally and see if/how we could add this tag. Will keep you updated!

**Comment by remh** [comment]
@ejholmes I think you can just edit this line https://github.com/DataDog/dd-agent/blob/master/conf.d/docker_daemon.yaml.example#L105 and add "container_id" to it to collect the container_id as a tag. Let us know how it goes!

**Comment by ejholmes** [comment]
@remh thanks for the heads up, but it [looks like there's no tag extractor for container_id](https://github.com/DataDog/dd-agent/blob/master/checks.d/docker_daemon.py#L90-L96). Would you guys accept a PR if `container_id` is disabled by default?

**Comment by remh** [comment]
Sorry for the delay @ejholmes . Just created a PR to add an extractor for that.
