### ISSUE TITLE
[iis] Non-digit value in WMI metric name

### ISSUE THREAD

**Issue by mausch** [DataDog/dd-agent#2354]
Getting this warning in v5.7.1 and `iis.site_up` is permanently triggered.

```
2016-03-16 14:57:40 GMT Standard Time | WARNING | checks.iis(iis.py:127) | When extracting metrics with WMI, found a non digit value for property 'name'.
```

This was working fine in v5.6.1

**Comment by olivielpeau** [comment]
Hi @mausch, thanks for opening this issue!

As far as I know this warning is not related to the change in the `iis.site_up` service check behavior.

To help us troubleshoot this, could you set the `log_level` to `DEGUB` in `datadog.conf`, restart the agent and send us a flare please: https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command

Thanks!

**Comment by mausch** [comment]
Done, internal case id is 48267

**Comment by sjenriquez** [comment]
@olivielpeau case id has been updated to 48283, @kwwalter is assigned
