### ISSUE TITLE
[varnish] v4.1 has increased security around varnishstat

### ISSUE THREAD

**Issue by matthewjackowski** [DataDog/dd-agent#2360]
Default varnish script didn't work until I added varnish group to dd-agent.  Unfortunately dd-agent gives a strange message due to parsing failure instead of permission denied.
This is how I fixed the problem locally:
```bash
usermod -G varnish -a dd-agent
````
Ref: https://www.varnish-cache.org/docs/trunk/whats-new/changes.html#proactive-security-features

**Comment by olivielpeau** [comment]
Hi @matthewjackowski, thanks for reporting this issue!

The documentation on the integration tile on the web app (https://app.datadoghq.com/account/settings#integrations/varnish, DD account required to access the page) mentions that `dd-agent` needs to be added to the varnish group, but it wasn't in the yaml file indeed. #2384 should fix it.
