### ISSUE TITLE
[core] Memory/handle leak in Windows agent

### ISSUE THREAD

**Issue by mausch** [DataDog/dd-agent#2364]
It seems there's a memory and handle leak in v5.7.1 of the Windows agent. Please see the attached Process Explorer screenshot. Note that the amount of memory and handles used were built up in less than 24 hours. The exact same thing happened in three different servers.
The vast majority of the handles are file handles for `c:\windows\system32\wbem\wbemdisp.tlb` which is used in WMI yet I am not using `wmi_check`.

I'm running v5.6.1 in two other servers and it's not displaying this behaviour. Memory usage is stable around 20MB with only a couple hunded handles.

I made a full dump of the ddagent.exe process, let me know if that's useful, it's 3.5GB.

![datadog-leak](https://cloud.githubusercontent.com/assets/95194/13849585/b3399c22-ec4e-11e5-95af-89df8f29d056.png)

**Comment by remh** [comment]
Thanks a lot for this report @mausch

We use WMI to capture system metrics (cpu, memory, etc), so even if the WMI check is not enabled, WMI is being used.

Is there a convenient way for you to share your memory dump ? Could you reach out to support@datadoghq.com please ?

Could you attach a flare (https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command) as well ?

Thanks a lot for this feedback. We'll investigate that shortly.

**Comment by mausch** [comment]
Thanks for quick fix! Things are back to normal now.
