### ISSUE TITLE
[wmi] Filter documentation

### ISSUE THREAD

**Issue by mausch** [DataDog/dd-agent#2368]
The comment in https://github.com/DataDog/dd-agent/blob/master/checks/libs/wmi/sampler.py#L314-L317 says that `*` is a valid wilcard to use in WMI filters, but it's not actually processed in the code that follows said comment. 
Only `%` is processed, which is fine, but I think the `*` should be removed from that comment.
A filter with `*` is also used in https://help.datadoghq.com/hc/en-us/articles/205016075-How-to-retrieve-WMI-metrics , it should be changed to `%`

Also there are no examples of wildcards in https://github.com/DataDog/dd-agent/blob/master/conf.d/wmi_check.yaml.example

**Comment by yannmh** [comment]
Sorry for the late answer @mausch.

You are completely right, we'll fix that shortly ! Thanks again.
