### ISSUE TITLE
[wmi] 32-bit agent cannot get metrics for 64-bit processes

### ISSUE THREAD

**Issue by mausch** [DataDog/dd-agent#2369]
At least for the .NET metrics e.g.  `Win32_PerfRawData_NETFramework_NETCLRLocksAndThreads`
It took me quite some time to figure this out, please document it somewhere very visible so that others don't make the same mistake.

**Comment by yannmh** [comment]
Interesting, we've heard about some similar issues in the past without being able to reproduce and properly understand where the limitation comes from.

I'll try  to see if i have more luck troubleshooting with the `Win32_PerfRawData_NETFramework_NETCLRLocksAndThreads` WMI class.
In the meantime, it'd make completely sense to document this behavior.

Thanks again @mausch !

**Comment by yannmh** [comment]
@mausch,

After further investigation, 64-bit Windows machine have two WMI providers one for 32-bit application, another one for 64-bit applications. By default, 32-bit WMI clients retrieve data from the 32-bit provider but there are metrics that only live in the 64-bit provider, like CLR metrics for 64bit .NET applications.

We are working on improving our WMI checks to be able to switch/fallback from one provider to the other: this would avoid this kind of discrepancies between Datadog Agent 32 and 64-bit on Windows.

**Comment by irabinovitch** [comment]
@yannmh I see this is flagged as documentation. Anything specific you'd like us to add on the WMI integration docs? We are in the process of rewriting them to be more detailed.

**Comment by yannmh** [comment]
@irabinovitch this is not related to documentation anymore: we are working on bringing WMI provider architectures support to our WMI checks  ✨  (c.f. my last message). 
I am updating the labels 🔖 .

**Comment by yannmh** [comment]
Fixed with https://github.com/DataDog/dd-agent/pull/2565
