### ISSUE TITLE
[network] Tag sockets states with process name

### ISSUE THREAD

**Issue by mausch** [DataDog/dd-agent#2375]
It would be great if we could tag sockets with the PID / process name of their owner. This would make it easier to track down socket leaks. At the moment we only get system-wide socket usage which means we can see a socket leak but we don't have the information to pinpoint which process is causing it.

In Windows, you can get process information by adding the `-b` flag to netstat (that is, after you apply #2352)

In Linux, both `ss` and netstat support the `-p` flag to get process info.

No idea about the other platforms but I'm guessing they have similar flags.

**Comment by olivielpeau** [comment]
Hi @mausch, and thanks for opening this issue!

On Linux, one problem I'd see with pulling the PID from `netstat`/`ss` is that the agent would need to use them as `root` to collect the PIDs of processes not owned by the `dd-agent` user.

That said we'll assess what could be done to work around this limitation.

**Comment by olivielpeau** [comment]
Also, tagging metrics by PID or process name wouldn't scale well. A better solution would be to have the process check collect the number of open sockets for the processes that it monitors.

The issue of the permissions needed to collect the information would remain. Maybe an approach similar to what's described in #853 would work.

**Comment by remh** [comment]
Yes, it's unlikely we'll implement this for the reasons described by @olivielpeau so i'm going to close this issue for now.
