### ISSUE TITLE
MySQL integration now needs PROCESS privilege

### ISSUE THREAD

**Issue by babbottscott** [DataDog/dd-agent#2376]
https://github.com/DataDog/dd-agent/blob/master/checks.d/mysql.py#L868 
With the addition of innodb status collection, the mysql user for datadog now needs PROCESS privilege as well as REPLICATION CLIENT.  Please update documentation to reflect.

**Comment by olivielpeau** [comment]
Hi @babbottscott, thanks for opening this issue.

To reflect this change, we've updated:
- the yaml example configuration file (https://github.com/DataDog/dd-agent/blob/5.7.2/conf.d/mysql.yaml.example#L37)
- the integration tile on the web app (see https://app.datadoghq.com/account/settings#integrations/mysql, DD account needed to access this page)

but you're correct the page on our docs website (http://docs.datadoghq.com/integrations/mysql/) is not up-to-date, we'll work on updating it too.

**Comment by babbottscott** [comment]
Many thanks!

**Comment by irabinovitch** [comment]
@babbottscott Thanks for reporting this. I'm going to close this out and track it over on our documentation repo in https://github.com/DataDog/dd-agent/issues/2386

We'll get it updated ASAP.

**Comment by technovangelist** [comment]
addressed in documentation pr 735 (https://github.com/DataDog/documentation/pull/735)
