### ISSUE TITLE
[gearman] integration failed: 'too many values to unpack'

### ISSUE THREAD

**Issue by acasademont** [DataDog/dd-agent#2395]
```
    gearmand
    --------
      - instance #0 [ERROR]: 'too many values to unpack'
      - Collected 0 metrics, 0 events & 1 service check
      - Dependencies:
          - gearman: 2.0.2
```

any ideas? what info can I provide you?

**Comment by hkaj** [comment]
Hi @acasademont, thank you for taking the time to opening this issue. Can you contact our support team with a flare command please? It would help us investigate. Instructions about that can be found here: https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command

**Comment by remh** [comment]
Closing while waiting for more details.
