### ISSUE TITLE
Issue Mysql

### ISSUE THREAD

**Issue by phanikumarp** [DataDog/dd-agent#2399]
How to integrate Mysql .

**Comment by phanikumarp** [comment]
How to integrate only Mysql  individually.

**Comment by irabinovitch** [comment]
@phanikumarp Thanks for your note and interest in using Datadog to monitor your MySQL instances.  Can you help clarify what you mean by "individually"?  

Docs for how to setup our MySQL integration are available here:
http://docs.datadoghq.com/integrations/mysql/

**Comment by phanikumarp** [comment]
"http://docs.datadoghq.com/integrations/mysql/ " i tried it showing only 6 metrics ,i want to all metrics for monitoring. 'individully ' means only mysql i want to monitor. where to send the data to database like  tsdb or casendra...

**Comment by irabinovitch** [comment]
@phanikumarp DD-Agent is intended for use with the Datadog service. It will collect and forward metrics from your systems to the Datadog as time series datastore and alerting platform.

In terms of the number of metrics, can you confirm which version of the Datadog agent you are running? and that you have granted both PROCESS and access to the performance_schema? Many of the metrics listed in the docs only became available in recent releases and require additional permissions. 

You may also want to set the following values in mysql.yaml if you are interested in detailed metrics from innodb or from replication status:

extra_status_metrics: true
extra_innodb_metrics: true

**Comment by olivielpeau** [comment]
Closing this issue as it doesn't seem directly related to the Agent.

@phanikumarp Feel free to contact our support team at help@datadoghq.com if you're still having issues.
