### ISSUE TITLE
Invalid tags in nginx example documentation 

### ISSUE THREAD

**Issue by sundbry** [DataDog/dd-agent#2408]
The documentation at https://github.com/DataDog/dd-agent/blob/master/conf.d/nginx.yaml.example
uses dictionaries in the tags yaml, however these are not supported on the latest datadog:kubernetes docker image. See the error below:

```2016-04-06 07:29:02 UTC | ERROR | dd.collector | checks.nginx(nginx.py:53) | Could not submit metric: ('nginx.net.waiting', 0, [{'profile': 'a'}],
 'gauge'): unhashable type: 'dict'```

`tags:` has to be a list of strings, not a list of dictionaries, in order to work.

**Comment by yannmh** [comment]
Sorry to hear about this issue @sundbry.

Would you mind attaching a snippet of your `nginx.yaml` where the tag`'profile': 'a'` is defined please ?

**Comment by remh** [comment]
@sundbry The example yaml file is correct. 

When there is no space after the column, it's a string.

So:
`foo:bar` is a string
while
`foo: bar` is a dictionary.

:disappointed: 

We should have better validation though but it shouldn't be specific to nginx so i'm going to close this issue.

Thanks for the feedback @sundbry !
