### ISSUE TITLE
does data dog agent rotate logs?

### ISSUE THREAD

**Issue by diwu1989** [DataDog/dd-agent#2416]
by default, on a vanilla ubuntu datadog install, does the agent rotate the log files in `/var/log/datadog/`?

just worried about logs growing unbounded

**Comment by masci** [comment]
Hi @diwu1989 
yes, logs are rotated using Python's [RotatingFileHandler](https://docs.python.org/2/library/logging.handlers.html#rotatingfilehandler).
Relevant code [here](https://github.com/DataDog/dd-agent/blob/master/config.py#L1005).

**Comment by diwu1989** [comment]
ah i see, its not handled by logrotate

**Comment by n0ts** [comment]
Hello, Did datadog agent is support logrotate `jmxfetch.log` `supervisord.log` ?
