### ISSUE TITLE
Installation error on windows 10

### ISSUE THREAD

**Issue by cw-pratik** [DataDog/dd-agent#2419]
When I try to install the agent it gives an error "A program required for this install could not be run".

I tried a lot of things mentioned on the net for this error. nothing seems to work. Then I printed the logs from the installer (log is attached). I think the issue is on line 3346. Here it is trying yo access c:\programdata\\\ddagent. Notice the double '\\'. 

[error.txt](https://github.com/DataDog/dd-agent/files/218430/error.txt)

**Comment by masci** [comment]
Hi @cw-pratik 
I need to reproduce the error and that could take some time.
Would you mind to reach our support team in the meantime?

Please keep this issue updated if you find a solution, thank you!

**Comment by cw-pratik** [comment]
Hi, I reached the support team. The problem was the anti-virus. I disabled it while installation and it worked.
