### ISSUE TITLE
Averaged Gauge Metric turns from Integer to Float

### ISSUE THREAD

**Issue by PeiwenChen** [DataDog/dd-agent#2428]
Hi,

I send a gauge metric to Datadog, but the value shown in Datadog is a Float value, like 0.26. 
It is not a Integer value I am expecting. Looks like the metric value is averaged and not Integer any more.

`statsd_gauge("metric.name", 2, tags)`

How can I change the averaging behavior and see the Integer value I sent in Datadog?

Thanks,

**Comment by remh** [comment]
Hi @PeiwenChen . Thanks for the feedback!

There are multiple factors in play when graphing data. 
Could you reach out to our support team https://app.datadoghq.com/help ? They'll be able to answer your questions.

Thanks!
Remi
