### ISSUE TITLE
Add a hostname check inspired by the hostname gist to the curl install

### ISSUE THREAD

**Issue by alq666** [DataDog/dd-agent#244]
# Synopsis

Since a number of aliasing issues (at least 2 or 3) come from people having funky settings, how about running the hostname script during the curl install process to double-check with the user that the hostname he's chosen is what is expected.

# Example

    We detected that this machine is known as $(socket.gethostname). Is this correct? (Y/N)

If he says No

    Since we are not picking up the right hostname, we can update datadog.conf with the proper hostname.
    It won't affect internal hostname resolution and helps Datadog assign the expected hostname to this machine.
    Do you want to do that? (Y/N)

If he says, Yes, we update the `hostname` field. If he says, No, we can say:

   Ok, this machine will be known as $(socket.gethostname) to Datadog.

**Comment by remh** [comment]
Closing this one. It's not that much of an issue anymore.
