### ISSUE TITLE
[kubernetes] add replicaset pods to kubernetes.pods.running metric

### ISSUE THREAD

**Issue by crunchie84** [DataDog/dd-agent#2444]
In PR #2277 @masci created the basics for the pod counts based on ReplicaControllers 🏆 . Since the release of Kubernetes (k8s) 1.2 this is no longer enough. The developers introduced `Deployments` in k8s 1.2 which work in combination with [`ReplicaSets`](http://kubernetes.io/docs/user-guide/replication-controller/#replicaset) instead of `ReplicaControllers` thus having pods be annotated as created-by `ReplicaSet`. 

## Proposed change

The pods are grouped by creator name in [`/checks.d/kubernetes.py`](https://github.com/DataDog/dd-agent/blob/master/checks.d/kubernetes.py#L246). Proposed change is to have this grouping also include pods grouped by ReplicaSet. As far as i can see the naming of ReplicationControllers/ReplicaSets is unique so no overlap should be possible.

## Example annotation output with new ReplicaSets:

```
"annotations": {
  "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"default\",\"name\":\"myreplicaset-2962775361\",\"uid\":\"618e8a0a-07c3-11e6-855b-42010af00104\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"3428\"}}\n"
}
```

This ticket has been created while using Kubernetes version 1.2.2

**Comment by crunchie84** [comment]
I have created a PR for the proposed change.

**Comment by pires** [comment]
Is this included in current Datadog? Using `Deployment`s and have no data.

**Comment by therc** [comment]
I don't see this, either. Running the latest :kubernetes image. Ideally, the agent should talk to the API server and figure the desired number of replicas for a ReplicaSet or Deployment, so that you can alert if they aren't 100% running for e.g. over 5 minutes.
