### ISSUE TITLE
aws instance storage

### ISSUE THREAD

**Issue by henryon** [DataDog/dd-agent#2450]
Is it possible to get aws ec2 instances storage metrics . Thanks a lot.

**Comment by remh** [comment]
Hi @henryon . Yes the agent collect metrics regarding all attached volumes. 
I'm closing this issue for now, can you reach out to our support team if you have any trouble getting these metrics ? http://docs.datadoghq.com/help/#desk

**Comment by henryon** [comment]
@remh  I meant instance storage. which is default on some instances.

**Comment by irabinovitch** [comment]
@henryon Thanks for the follow up note. If you mean ephemeral storage, then yes, as @remh it will be collected by dd-agent on both Linux and Windows.  Many of the metrics are covers as system.disk.* nd system.io*, see our [docs](http://docs.datadoghq.com/integrations/system/).

For further assistance, we'd recommend reaching out to our support team via the instructions here:
http://docs.datadoghq.com/help/#desk

**Comment by henryon** [comment]
@irabinovitch  thanks
