### ISSUE TITLE
Document event_type

### ISSUE THREAD

**Issue by ash2k** [DataDog/dd-agent#2452]
http://docs.datadoghq.com/guides/dogstatsd/ talks about `event_type` but does not document how to pass it. Please document it.

p.s. not sure if it is the right place to report this issue, sorry.

**Comment by remh** [comment]
Thanks for the feedback @ash2k .

You're right it's actually a mistake, you can't pass the event type when submitting events through Dogstatsd.

Closing in favor of: https://github.com/DataDog/documentation/issues/751

Thanks again for the feedback!
