### ISSUE TITLE
docker_daemon reports 'Couldn't find pid directory' on RancherOS

### ISSUE THREAD

**Issue by ricky26** [DataDog/dd-agent#2454]
On RancherOS, docker_daemon fails with the following message:
`[WARNING]:Couldn't find pid directory for container: container-name`

It looks like the regexp used for searching for the container ID in the namespace list catches the user-docker container ID not the current container. (Paths on RancherOS look like `/docker/0a71a4dfc948fb7d2817601f05c1d22474c425b5aca3dd4a3039f2ca98bc1a1b/docker/d000c19bcb47f853d6e66f4b853fdd29f49e9a7a9a17106d27ba2be706836251`, the first ID is the user-docker container, the second ID is the processe's container ID.)

Perhaps just a $ added to CONTAINER_ID_RE (https://github.com/DataDog/dd-agent/blob/master/checks.d/docker_daemon.py#L27) would be enough?

**Comment by remh** [comment]
Thanks for the feedback @ricky26 , we'll review this shortly.
