### ISSUE TITLE
[core] mounting a YAML configuration file with .yml extension (not .yaml) isn't copied into /etc/dd-agent/conf.d

### ISSUE THREAD

**Issue by oryband** [DataDog/dd-agent#2458]
From DataDog/docker-dd-agent#85:

> The source of the problem is in this line: https://github.com/DataDog/docker-dd-agent/blob/4a05382ac2acb1b656c310380fe80ce5a92bb15b/entrypoint.sh#L43
>
> .yml extension is a valid YAML extension and should also be taken into account.

The source of the problem is in this repo, specifically here: https://github.com/DataDog/dd-agent/blob/5.7.4/config.py#L791

**Comment by remh** [comment]
Hi @oryband . Thanks for the feedback!

I agree that it's common to find yaml files whose extension is `.yml`, however this is not a standard, nor a convention.

The FAQ actually recommends to use `.yaml` and only this extension so i'm going to close this issue as supporting `.yml` would mean adding more code without a clear benefit.

Thanks again for the feedback.

**Comment by oryband** [comment]
bah. @remh are you sure this isn't as easy as it sounds?
