### ISSUE TITLE
DD_INSTALL_ONLY in setup_agent.sh

### ISSUE THREAD

**Issue by themartorana** [DataDog/dd-agent#2471]
I'd like to submit a pull request for adding the `$DD_INSTALL_ONLY` variable to [setup_agent.sh](https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent/source/setup_agent.sh) as it exists in [install_agent.sh](https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent/source/install_agent.sh) but I wanted to see if there was any reason not to do so.

I'm installing the agent on FreeBSD, and would like to skip the agent foreground test since I'm packing VMs automatically.

**Comment by hkaj** [comment]
Hi @themartorana,
That's actually a use case I encountered last week when installing the agent from source on Alpine and packaging it as a container. It should be an easy change, we'll look into this shortly.

**Comment by hkaj** [comment]
Hi @themartorana 
actually you can use https://github.com/DataDog/dd-agent/blob/5.8.0/packaging/datadog-agent/source/setup_agent.sh#L34-L36 which does that already.
I'm going to close this issue, but feel free to reopen it if you encounter any difficulty.
