### ISSUE TITLE
[core] io metrics linux: device names with dashes are not supported

### ISSUE THREAD

**Issue by Martiflex** [DataDog/dd-agent#2517]
io metrics are grabbed from `iostat`: https://github.com/DataDog/dd-agent/blob/master/checks/system/unix.py#L121-L139

```
$ iostat -d 1 2 -x -k

Linux 2.6.32-573.7.1.el6.x86_64 (address.net) 05/19/2016 _x86_64_ (32 CPU)

Device: rrqm/s wrqm/s r/s w/s rkB/s wkB/s avgrq-sz avgqu-sz await svctm %util
xvaa 1.22 112.88 9.70 21.89 220.78 626.35 53.63 0.25 7.76 0.44 1.38
pm-0 0.00 0.00 6.63 13.80 38.52 55.19 9.17 0.67 33.01 0.26 0.53
pm-1 0.00 0.00 3.97 100.49 161.44 401.98 10.79 0.90 8.59 0.06 0.60
```

No data is reported under device name `pm-0` or `pm-1`, instead all data is reported under `pm`, and the last disk metrics erase values from previous pm disks.

Supporting dashes in device names regex (https://github.com/DataDog/dd-agent/blob/master/checks/system/unix.py#L38) solves the problem a.k.a:

`self.item_re = re.compile(r'^([\-a-zA-Z0-9\/]+)')`

See ticket: https://datadog.zendesk.com/agent/tickets/53558

**Comment by remh** [comment]
Thanks!

**Comment by remh** [comment]
Confirmed that the proposed regex works fine
