### ISSUE TITLE
Add note about supported architectures of binary packages

### ISSUE THREAD

**Issue by paulmenzel** [DataDog/dd-agent#2534]
Happy about reading that binaries for Debian are provided, I followed the instructions, only finding out that no packages for ARM (Raspberry Pi) are provided.

It’d be great to have a hint somewhere about this limitation.

**Comment by yannmh** [comment]
Hi @paulmenzel,

You're right we'll add a note to specify not only the supported operating systems but also the supported architecture. 
In the meantime, we advise our ARM users to install Datadog Agent ["From Source"](https://app.datadoghq.com/account/settings#agent/source).

**Comment by degemer** [comment]
Done: https://app.datadoghq.com/account/settings#agent/debian.
Thanks !

**Comment by paulmenzel** [comment]
Thanks a lot for the quick response!
