### ISSUE TITLE
Counter events from dogstreams should be aggregated in a meaningful way

### ISSUE THREAD

**Issue by charles-dyfis-net** [DataDog/dd-agent#254]
(#253 applies only to aggregating data points within the same second; this ticket applies to generating values with a meaningful time axis applied from dogstream "counter" events).

At present, if a dogstream plugin sends 4 counters, with value 1, at distinct seconds within the same minute, this case (4 counter events) is visually indistinguishable from the situation in which only a single counter datapoint, likewise with value 1, is sent.

If a dogstream counter serves as an instantaneous "increment" event, this behavior is faulty on its face.

If a dogstream counter is intended to be a dump  of accumulator contents, by contrast, this accumulator cannot  be meaningful without the time period being specified. Without knowing if numbers provided to a "clicks" counter are intended to be "clicks per minute" or "clicks per second", one cannot provide an appropriate value. (Moreover, should it be "clicks per second" -- what we would have with #253 fixed -- the current graphing behavior would be faulty).

Consequently, any expectations with respect to counter values sent to DataDog with respect to the time periods over which they are measured should be clearly documented.

**Comment by remh** [comment]
Thanks a lot @charles-dyfis-net 
We are currently evaluating new options to replace dogstream and we likely won't add new features to the current implementation unfortunately, so i'm going to close this issue. Feel free to reply or to reach out to our support team if you have more questions.

Thanks again for the feedback!
