### ISSUE TITLE
No --version?

### ISSUE THREAD

**Issue by olivierlacan** [DataDog/dd-agent#2540]
I'm trying to determine which version of the agent we have installed on one of our servers and it's very difficult to do that since `--help` doesn't output current version information and `--version` doesn't exist.

Do you mind adding that? Should I submit a PR with that?

**Comment by yannmh** [comment]
@olivierlacan, there are different ways you could use to determine which version of Datadog Agent is running. 
Two examples that randomly cross my mind would be to:

1. Use  the `datadog-agent info` command: the current version is shown on the header of the different components. 

	````
	===================
	Collector (v 5.8.0)
	===================
	[...]
	===================
	Dogstatsd (v 5.8.0)
	===================
	[...]
	===================
	Forwarder (v 5.8.0)
	===================
	[...]
	```
2. (Not great) On Linux systems, use the package manager to show the package version

Besides that, I agree with you: having a `--version` flag would be easier and appreciated. 

I can add a card in our backlog to add that, but if you decide to make a PR, we'll be also happy to review it :).

**Comment by irabinovitch** [comment]
Hi @olivierlacan, Would the info command meet your needs at the moment?

**Comment by yannmh** [comment]
We haven't heard back from you @olivierlacan. I think the `datadog-agent info` command is what you are looking.
I am closing this issue, please feel free to re-open it if you need further assistance.
