### ISSUE TITLE
Using dogstatsd directly appears to not use host tags from config

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#2546]
When using the dogstatsd as a standalone process, the `tags` value in datadog.conf appears to have no impact.

The use case is to have some default tags set in the config file at startup, so any payload flowing through the dogstatsd server decorates the payload with the host tags.

It appears that the logic for applying host tags is in the collector.py only, so it might be simpler to extract the logic to a common method and use it in both places.

**Comment by yannmh** [comment]
Thanks @miketheman :)

I am adding a card in our backlog to consider it in an upcoming release. I'll keep you update as we have more information on it.

Yann

**Comment by remh** [comment]
Thanks Mike! Not sure we want to do that. The host tags set in datadog.conf are passed to datadog as host tags, i.e. they are not applied directly to the metrics. You can just add the host tags directly to your host using the API or by running the collector.
