### ISSUE TITLE
sqlserver integration runs in a transaction

### ISSUE THREAD

**Issue by rlaveycal** [DataDog/dd-agent#2555]
It turns out that the adodbapi library used by the SQL Server integration defaults to starting transactions on opened connections. This is undesirable from a resource point of view. It can be disabled by passing `'autocommit':True` in the parameters dictionary (see page 5 of http://adodbapi.sourceforge.net/quick_reference.pdf).

I've made this change as part of my PR #2445

**Comment by masci** [comment]
Fixed in https://github.com/DataDog/integrations-core/pull/357
