### ISSUE TITLE
Document datadog.conf defaults better

### ISSUE THREAD

**Issue by tuukkamustonen** [DataDog/dd-agent#2558]
Looking at reference `datadog.conf`, it's not clear what the defaults are.

There are some inconsistencies. For example:

    # Collect AWS EC2 custom tags as agent tags (requires an IAM role associated with the instance)
    # collect_ec2_tags: no

I assume default here is ‘no’. Fair enough.

But then there is:

    # use unique hostname for GCE hosts, see http://dtdg.co/1eAynZk
    gce_updated_hostname: yes

If I comment that, does it default to ‘no’? Why is it not commented like the rest of the settings?

    # If you need a proxy to connect to the Internet, provide the settings here
    # proxy_host: my-proxy.com
    # proxy_port: 3128
    # proxy_user: user
    # proxy_password: password

Yeah it’s understandable that proxy is by default disabled, but if interpret this with the same logic as before, one would understand that proxy defaults to `user@pass:my-proxy.com:3128`.

Also:

    # Force the hostname to whatever you want.
    #hostname: mymachine.mydomain

I assume hostname is detected by default, `mymachine.mydomain` is not the default…

    # collector_log_file: /var/log/datadog/collector.log
    # forwarder_log_file: /var/log/datadog/forwarder.log
    # dogstatsd_log_file: /var/log/datadog/dogstatsd.log

In reality, logging is enabled only if these are uncommented, but reader can’t know that it’s the logic (I first assumed they were defaults and that logging would be enabled by default).

It would be clearer if you documented these settings like (as an example):

    # Collect AWS EC2 custom tags as agent tags (requires an IAM role associated with the instance) (default: no)
    # collect_ec2_tags: no

    # use unique hostname for GCE hosts, see http://dtdg.co/1eAynZk (http://dtdg.co/1eAynZk) (default: no)
    # gce_updated_hostname: no

    # If you need a proxy to connect to the Internet, provide the settings here (default: disabled)
    # proxy_host: my-proxy.com
    # proxy_port: 3128
    # proxy_user: user
    # proxy_password: password

    # Force the hostname to whatever you want (default: auto-detected)
    #hostname: mymachine.mydomain

Or some other way to indicate default value clearly.

I actually sent this to Datadog support first (before realising I can file a ticket here) and their response was:

> -- Everything you've said there is correct and I understand the confusion. There definitely seem to be discrepancies between what is commented out and what is considered default for different parameters. In some cases the values are examples and in others they are default. --

**Comment by irabinovitch** [comment]
Thanks @tuukkamustonen. Reasonable feedback. We'll take a pass on this ahead of the 5.9 release.

**Comment by degemer** [comment]
https://github.com/DataDog/dd-agent/pull/2618 adds more documentation about defaults. We can probably still do better, let us know what you think!

I'm closing this issue for now since I think we addressed your points, feel free to reopen if you think we should spend some more time on it!
