### ISSUE TITLE
dd-agent package pollutes top-level namespace

### ISSUE THREAD

**Issue by charles-dyfis-net** [DataDog/dd-agent#256]
Installing dd-agent creates a large number of top-level Python packages with names which aren't clearly delimited as related to DataDog, such as `checks`.

These should be moved under a top-level namespace -- `import datadog.checks as checks` rather than `import checks`.

Among other things, this makes it difficult for code to both have an internal `checks` module and to reference the DataDog `checks` module, particularly in Python interpreters not using absolute imports (behavior not default prior to Python 2.7).

**Comment by remh** [comment]
We don't use the system python anymore so it's not an issue anymore.
