### ISSUE TITLE
Should we track "load per cpu" on a machine

### ISSUE THREAD

**Issue by clutchski** [DataDog/dd-agent#258]
So that you don't need to to know how many cores are on a machine to understand the load. Or is there a way to calculate this with the data we collect already?

(question from a customer in the chat)

**Comment by fredflev** [comment]
@DevOpsDave How does this handles system with Hyperthreading enabled? 
Let say if I have a machine with 1 CPU/ 4 physical cores and Hyperthreading on. 
Will the system.load value by divided by 4 or 8?
