### ISSUE TITLE
kafka jmx metrics -- can't find some of the types

### ISSUE THREAD

**Issue by memelet** [DataDog/dd-agent#2594]
For example, in kafka.yaml.example

```
bean_regex: 'kafka\.consumer:type=consumer-fetch-manager-metrics,client-id=.*'
```

I can find no trace of this metric in the kafka source code. What metrics are these supposed to map to?

**Comment by degemer** [comment]
Hey @memelet !

It looks like this metrics are only available in 0.9.0.x consumers. (https://github.com/DataDog/dd-agent/blob/master/conf.d/kafka.yaml.example#L158-L172) Maybe you're not running this version of Kafka ?
If you want to know more about this metric, you can have a look at the metrics tab of https://app.datadoghq.com/account/settings#integrations/kafka.

Let us know if you need more help!

**Comment by memelet** [comment]
I was searching the kafka 0.9 and 0.10 source code.

**Comment by jeffwidman** [comment]
This should be closed IMO.

**Comment by degemer** [comment]
Sorry for the lack of response @memelet. If it's still an issue for you, could you contact our [support](https://www.datadoghq.com/support/) to debug this further?
Closing, thanks for the reminder @jeffwidman.
