### ISSUE TITLE
kafka_consumer.yaml will always issue errors?

### ISSUE THREAD

**Issue by memelet** [DataDog/dd-agent#2595]
For kafka_consumer.yaml, kafka_consumer.py seems to always try to find the offsets from both zookeeper and kafka. And when it does for either it logs errors. But won't this always log an error since the offsets will only be one or the other. Isn't this going to generate a lot of noise in the logs and unnecessary alerts?

**Comment by degemer** [comment]
Hi @memelet !

If I'm correct, Zookeeper has the consumer offsets whereas Kafka has the broker offsets, so it shouldn't log errors. For more details on `kafa_consumer`, you can have a look at our blog post about Kafka monitoring: https://www.datadoghq.com/blog/monitor-kafka-with-datadog/.

Let us know if that helps!

**Comment by jeffwidman** [comment]
This should be closed as @degemer is correct. The logging verbosity dropped greatly after the `kazoo` dependency was upgraded, so that should help.

**Comment by degemer** [comment]
Thank you for confirming @jeffwidman!
I'm going to go ahead and close, please let us know if it's still an issue for you @memelet!
