### ISSUE TITLE
Options you do not want to send the data to datadog

### ISSUE THREAD

**Issue by yoshida-mediba** [DataDog/dd-agent#2599]
To request the option of a do not send the data to the acceptable datadog the setting as "dd_url: null".

**Comment by hkaj** [comment]
Hi @yoshida-mediba 
I'm not sure why you would need this option, can you detail your use case a little bit?

**Comment by yoshida-mediba** [comment]
* I want to start the Datadog Agent with Vagrant.
* I want to send the data from the application to the DatadogStatsd.
* However, I do not want to send the data to Datadog.
* Datadog want to verify the operation of the configuration file.
* It may transmit the data to if not in billable Datadog.

**Comment by hkaj** [comment]
If I understand correctly you want to send metrics to dogstatsd, but don't want dogstatsd to forward them to our backend to not get billed. Is that correct? What is the goal of this setup, if the metrics don't flow to us I don't see what value you get from using dogstatsd.

**Comment by yoshida-mediba** [comment]
Such IF statement is want to avoid.

```
if (ENVIRONMENT == 'production') {
    statsd.gauge('key', data);
}
```

And then sent only to the Datadog when you want to check the metrics.

**Comment by remh** [comment]
@yoshida-mediba why not just stopping the agent ?
Statsd using UDP it shouldn't error if the statsd server is not running.

**Comment by yoshida-mediba** [comment]
Thank you, I did not know.

There are also these things.
```
- template: src={{ SERVER_TYPE }}.process.yaml.j2 dest=/etc/dd-agent/conf.d/process.yaml
  register: reload_process
- service: name=datadog-agent state=restarted
  when: reload_process.changed and APPLICATION_ENV == 'production'
```

I tried to issue I think that easy either.
I do not mind the close.

**Comment by degemer** [comment]
@yoshida-mediba I'm going to close this issue since it seems that @remh 's suggestion is enough. Let us know if you still need help!
