### ISSUE TITLE
WARNING (util.py:144): Hostname: localhost is local

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#2644]
It seems that DataDog is triggering a warning that is confusing and that it does not give much information regarding the cause.

This is thrown from https://github.com/DataDog/dd-agent/blob/master/util.py#L143 and in my case generates something like
```
Jun 30 13:48:32 localhost dd.collector[21819]: WARNING (util.py:144): Hostname: localhost is local
```
I do mention that the hostname of the machine is NOT localhost. Here are the results of:
```
>cat /etc/hostname
sodium

>hostname
sodium

>hostname -a
sodium

>hostname -s
sodium

>hostname -A
ip-172-31-59-153.ec2.internal ip-172-17-0-1.ec2.internal

>hostname -f
# same as `hostname --fqdn`
localhost
```

It seems that DataDog managed to pick the only flavour of hostname that returns localhost. What a joy!

**Comment by remh** [comment]
Thanks for the feedback @ssbarnea 
As per the `man hostname` page, 
`hostname -a` is deprecated and shouldn't be used
`hostname -s` is supposed to be the short host name. i.e. this is the host name cut at the first dot.

Using the FQDN is the reasonable thing to use to try to ensure unicity as much as possible so using `/etc/hostname` is not a great fit as well as per its documentation it should be the short name not the FQDN.

We could use `hostname -A` as it lists all FQDNs but this would likely change the hostname for existing installations without a clear benefit over `hostname -f`

In your situation, i think the best solution is to properly set the FQDN of the server or to set the desired hostname in `datadog.conf`.

Thanks again for the feedback.

**Comment by pauricthelodger** [comment]
@ssbarnea (second time we've both had the same issue this week!) - if you're running a Debian-based server, you could update the 127.0.1.1 with the custom hostname and alias rather than 127.0.0.1? That should fix `hostname -f` for datadog.
