### ISSUE TITLE
Log file does not always use standard format

### ISSUE THREAD

**Issue by memelet** [DataDog/dd-agent#2663]
Sometimes the log file will log bare lines, eg:

```
2016-07-07 02:00:15 UTC | WARNING | dd.collector | checks.collector(collector.py:797) | GOHAI LOG | Error fetching info for pid 29260: user: unknown userid 10000
Error fetching info for pid 29292: user: unknown userid 10000
Error fetching info for pid 29429: user: unknown userid 10000
Error fetching info for pid 29436: user: unknown userid 10000
```

**Comment by olivielpeau** [comment]
Hi @memelet!

These lines are all logged at once when `gohai` reports internal errors.
Multiple log lines can also be logged at once when an python exception's traceback is logged, for instance.

Is this behavior causing any issue on your end?

**Comment by memelet** [comment]
This kind of logging is very hard to ingest into ELK

**Comment by olivielpeau** [comment]
IMO having multi-line messages makes some types of messages way easier to read (exception tracebacks for instance), so even if we could change the behavior of gohai to avoid logging multiple lines at once, we'd generally want to keep multi-line messages in the collector's logs.

As for your use case, have you tried using the [multiline codec](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-multiline.html)?

**Comment by memelet** [comment]
@olivielpeau Agreed, if you reading the files directly. But not if you route them to elk and use kibana.

**Comment by olivielpeau** [comment]
@memelet: Could you explain how you route these logs to elk? Something could potentially be changed there to allow ingesting multi-line messages.

Unfortunately I think that most users read log files directly so keeping multi-line messages is more desirable overall for readability.

**Comment by memelet** [comment]
> Unfortunately I think that most users read log files directly so keeping multi-line messages is more desirable overall for readability.

Really, wow. I would have thought that ended about 5 years ago.

Sure it's possible to invest the time to get logstash to parse multiline logs. Not something I will probably invest in. 

Most modern logging libraries support emitting logs in json (eg, logback for java, bunyan for node). Not sure if what you use for python supports that.

**Comment by olivielpeau** [comment]
As a workaround, since the agent also logs to syslog, you could ingest the agent's logs from there and set up your syslog daemon to escape newlines (rsyslog does it by default for instance).

Having an option in the Agent configuration to only log one-line messages would make sense though, I'll add this to our backlog.

@memelet: about emitting logs in json, do you only mean that the Agent should have an option to format all its log messages into json, or do you also mean that it should be able to send json-formatted logs to a remote target (using a protocol that's not syslog since it's already supported by the Agent)?

**Comment by memelet** [comment]
@olivielpeau I would think that json formatted logs would only make sense to a file to aid in ingesting into something like ELK or Loggly. I don't think json to syslog would be useful.

**Comment by olivielpeau** [comment]
Closing the loop on this old issue: this was addressed in v6 and v7 of the Agent, with the `log_format_json` option (https://github.com/DataDog/datadog-agent/blob/a68a5b45bc7788ee86e7ca99089ef963863da494/pkg/config/config_template.yaml#L1303), so I'll go ahead and close this
