### ISSUE TITLE
Upgrade to boto3 plan?

### ISSUE THREAD

**Issue by n0ts** [DataDog/dd-agent#2664]
Now datadog agent use boto 2.x.
Do you have a plan for upgrade boto3?

Regards.

**Comment by yannmh** [comment]
Thanks for reaching out @n0ts,

Datadog Agent's usage of `boto` is very narrow and limited to some metadata collection. Out of curiosity, is there any particular reason, you'd want to see a newer version shipped ?

**Comment by n0ts** [comment]
@yannmh Hi, I make a my custom datadog agent check. `Boto3` is a latest version python's aws sdk.
So now I use `boto2`, in feature I want ot use boto3.

Thanks.

**Comment by remh** [comment]
@n0ts you can install boto3 with boto2 being present. They can live together:
```python
$ sudo /opt/datadog-agent/embedded/bin/pip install boto3
[...]
Successfully installed boto3-1.4.0 botocore-1.4.49 docutils-0.12 jmespath-0.9.0 s3transfer-0.1.2
```
```python
$ /opt/datadog-agent/embedded/bin/python
Python 2.7.12 (default, Jul 27 2016, 15:55:48)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto
>>> boto.__file__
'/opt/datadog-agent/embedded/lib/python2.7/site-packages/boto/__init__.py'
>>> import boto3
>>> boto3.__file__
'/opt/datadog-agent/embedded/lib/python2.7/site-packages/boto3/__init__.pyc'
>>>
```

So i'm going to close this issue.
