### ISSUE TITLE
[wmi] More friendly error for missing/incorrect WMI class

### ISSUE THREAD

**Issue by mausch** [DataDog/dd-agent#2671]
Currently if you try to query a non-existing class you get a rather obscure `OLE error`. https://github.com/DataDog/dd-agent/issues/2648#issuecomment-230834999
Instead, it would be nice to see a message such as "Invalid WMI class xxx".

**Comment by remh** [comment]
Thanks @mausch . It got fixed in an earlier version of the agent.
