### ISSUE TITLE
process check aggregates all processes together

### ISSUE THREAD

**Issue by directionless** [DataDog/dd-agent#2689]
Hi! I'm not totally sure if this is a bug or a feature request. (or if I just don't understand the intent of the process check).

I'd like to have basic metrics for the memory and cpu usage of several key processes. It looks like the process is designed to do this, but when it reports metrics, it does so by aggregating them all together into `system.processes.mname`, as opposed to `system.processes.process.mname` (https://github.com/DataDog/dd-agent/blob/master/checks.d/process.py#L327-L337)

Am I missing something obvious? How would I do this

**Comment by remh** [comment]
@directionless The process check tags its metrics by the process name.
See https://github.com/DataDog/dd-agent/blob/master/checks.d/process.py#L322

So in the graph editor in the web app you'll be able to pick the process you want to look at.

I'm closing the issue for now. I will reopen if needed.

**Comment by directionless** [comment]
Perfect, thank you!
