### ISSUE TITLE
[ceph] add metric for active monitors

### ISSUE THREAD

**Issue by ccocsas** [DataDog/dd-agent#2719]
Current check reports ceph.num_mons, which is the number of configured ceph-mon hosts.  The number of active ceph_mon processes can be obtained by the length of  [quorum] from the same data source.

Proposed addition.

```
        try:
            num_mons_active = len(raw['mon_status']['quorum'])
            self.gauge(self.NAMESPACE + '.num_mons.active', num_mons_active, tags)
        except KeyError:
            self.log.debug('Error retrieving mon_status quorum metrics')
```

**Comment by remh** [comment]
Thanks @ccocsas . Could you open a pull request please ?

**Comment by ccocsas** [comment]
yeah, made a mistake and committed it to master instead of a branch.  Sorting it out.
