### ISSUE TITLE
[kubernetes] add more metrics related to k8s deployments

### ISSUE THREAD

**Issue by onbjerg** [DataDog/dd-agent#2722]
Right now we can only filter based on replication controllers using `kube_replication_controller`. It is my understanding that ReplicaSet are also included in this.

It would be a lot better if you could filter based on `kube_replica_set` and/or `kube_deployment`. Specific metrics for these could prove valuable for monitoring, e.g. the number of pods running for a specific ReplicaSet/Deployment vs. the desired count. All of these values can be extracted from the k8s API.

Another nice addition would be the number of available and unavailable pods. A pod _can_ be running, but not be available. A pod is only available when it's readiness probe succeeds, otherwise it is unavailable. These metrics could be called `kubernetes.pods.available` and `kubernetes.pods.unavailable` respectively.

My proposal is to add the following:
- `kubernetes.pods.desired` (for ReplicaSet, Deployments and ReplicationControllers)
- `kubernetes.pods.available`
- `kubernetes.pods.unavailable`
- `kube_replica_set` or/and `kube_deployment` tags

The addition of these metrics and tags would improve the overall experience with the k8s integration.

**Comment by onbjerg** [comment]
I might work on this if I have time later this week and if the proposal is 👍

**Comment by onbjerg** [comment]
Maybe we could also pull some actual data from the pods, like their mem/CPU requests and limits.

**Comment by onbjerg** [comment]
The deployment statuses can be found in ``/apis/extensions/v1beta1/deployments``.

**Comment by jonmoter** [comment]
+1 on kube_deployment tags

**Comment by onbjerg** [comment]
Waiting for merge #2728
