### ISSUE TITLE
disk.py reports missing attribute

### ISSUE THREAD

**Issue by kangelos** [DataDog/dd-agent#2732]
Stock installation under Centos 6.7
disk collector breaks with
File "/root/.datadog-agent/agent/checks.d/disk.py", line 270, in _list_devices#012    flattened_devices = self._flatten_devices(raw_devices)#012  File "/root/.datadog-agent/agent/checks.d/disk.py", line 250, in _flatten_devices#012    elif previous and self._is_number(parts[0]):#012AttributeError: 'Disk' object has no attribute '_is_number'

**Comment by degemer** [comment]
Thank you for the report @kangelos !

Would you mind running `sudo -u dd-agent df -Tk` and either post it there or send it to support at datadoghq.com ?

We think we have a solution, but we'd like to be sure before merging it. 
Let us know if you have any question!

**Comment by kangelos** [comment]
Just in case you miss the email	

```

df -Tk
Filesystem Type 1K-blocks Used Available Use% Mounted on
/dev/sda3 ext4 93421512 70963180 17706052 81% /
tmpfs tmpfs 32969616 0 32969616 0% /dev/shm
/dev/sda1 ext4 512752 90460 395412 19% /boot
10.71.27.253:/vol/ads
nfs 1020054752 56080768 963973984 6% /ads
```

**Comment by degemer** [comment]
Thanks @kangelos ! I updated my PR thanks to this, it should work now.

If you want to give it a try, you can download the `disk.py` on my branch: https://raw.githubusercontent.com/DataDog/dd-agent/cf9928120c36318b0f597dacab2c937c8b08f70c/checks.d/disk.py, put it in place of ` /root/.datadog-agent/agent/checks.d/disk.py`, and restart the agent.

I used your `df -Tk` output for a test in https://github.com/DataDog/dd-agent/pull/2733/files (I changed the ip address and the mountpoint), is it okay with you ?

**Comment by kangelos** [comment]
Hi Quentin 

your patch is in and it looks good, 

no more complaints from disk.py 

Regards 

.A.

On 2016-08-04 23:36, Quentin Madec wrote:

> Thanks @kangelos [1] ! I updated my PR thanks to this, it should work now. 
> 
> If you want to give it a try, you can download the disk.py on my branch: https://raw.githubusercontent.com/DataDog/dd-agent/cf9928120c36318b0f597dacab2c937c8b08f70c/checks.d/disk.py, put it in place of /root/.datadog-agent/agent/checks.d/disk.py, and restart the agent. 
> 
> I used your df -Tk output for a test in https://github.com/DataDog/dd-agent/pull/2733/files (I changed the ip address and the mountpoint), is it okay with you ? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/kangelos
[2]
https://github.com/DataDog/dd-agent/issues/2732#issuecomment-237675503
[3]
