### ISSUE TITLE
Add support for F5 metric collection check

### ISSUE THREAD

**Issue by KCarretto** [DataDog/dd-agent#2742]
Description

The goal of this proposal was to poll a F5 BIGIP device for metrics and to send
that information to DataDog. We decided to make an AgentCheck to collect and 
report these metrics and attempted to make the check as adaptive as possible. 

This was achieved by using SNMP and the F5 specific MIB files to query the 
device for metric information stored in data structures in the class definition.

The format used allows for easily configurable metric collection, simply by 
finding the name of the name of the object desired as defined in an MIB file, 
and placing it in one of the structures. 

You can also very easily obtain data 
from SNMP tables that are singularly indexed. 

Tables that are indexed complexly
must be accessed through the custom metrics structure. 

You may also specify 
which tags to give a specific metric in these datastructures, however one 
feature of the table metric structure is that it will attempt to dynamically 
resolve values of tags using data collected from the specified table. This 
allows you to use one or more pieces of information, usually the table index 
(i.e. CPU Slot ID), as a tag for your metrics. The dependencies for this check 
include `easysnmp` to be installed through the DataDog agent's embedded pip.
This requires an installed version of `net-snmp 5.71` or later, which is 
unavailable on some distributions. We have successfully configured this check to
work on CentOS 6.7 although `net-snmp 5.7` is not available for it. Although it
depends on a newer version of glibc than is provided on CentOS 6.7, compiling
`net-snmp 5.7` from source has been successful. By installing it and copying the 
libnetsnmp.so.30 into the DataDog agent lib directory, the check is able to 
complete successfully. This check also depends on the F5-BIGIP MIB files to be 
installed into a directory that is configurable through the check. These files
can be downloaded from the F5 BIGIP device itself, instructions on how to do so
can be found through F5's website:

https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-external-monitoring-implementations-11-3-0/8.html

System Dependencies

```
easysnmp
net-snmp 5.7 or later
F5 BIGIP MIB files
```

We have not yet created a pull request in dd-agent-omnibus repository to add these 
dependencies but plan to.

**Comment by remh** [comment]
Thanks for the detailed proposal @KCarretto looking forward your PRs

**Comment by remh** [comment]
Closed. Follow up work on this PR: https://github.com/DataDog/integrations-extras/pull/27
