### ISSUE TITLE
[core] apt-get warns of weaks digest algorithm use by signature

### ISSUE THREAD

**Issue by rabbitfang** [DataDog/dd-agent#2754]
When running `apt-get update` on Ubuntu 16.04.1, I get the following warning: `W: https://apt.datadoghq.com/dists/stable/Release.gpg: Signature by key 935F5A436A5A6E8788F0765B226AE980C7A7DA52 uses weak digest algorithm (SHA1)`

Steps to reproduce (on Ubuntu 16.04.1):
1. `sudo sh -c "echo 'deb https://apt.datadoghq.com/ stable main' > /etc/apt/sources.list.d/datadog.list"`
2. `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C7A7DA52`
3. `sudo apt-get update`

ElasticSearch was recently affected by this: https://github.com/elastic/elasticsearch/issues/17724

**Comment by remh** [comment]
Hi @rabbitfang Thanks for reporting. We are aware of the issue and are planning to fix that in the next couple of days.

**Comment by thiagotalma** [comment]
any workaround while not solved?

**Comment by remh** [comment]
@thiagotalma no need for a work around, this is a non blocking warning. It shouldn't block the agent installation.

We are going to do a new release of the agent within the next 2 weeks that will solve this permanently.

**Comment by remh** [comment]
This is fixed. Thanks for the feedback!
