### ISSUE TITLE
pg8000 client doesn't work for our postgres/pgbouncer db setup

### ISSUE THREAD

**Issue by sethcleveland** [DataDog/dd-agent#2755]
We'd like to use the postgres custom metrics feature with our postgres db setup, but can't because of exceptions. To resolve this, swapping the pg8000 client with the psycopg2 one works. See below. I basically made a custom checker and overrode the pg.connect method.

```python
# pull in datadog's postgresql AgentCheck
import imp
imp.load_source("datadog_checksd_postgres", "/opt/datadog-agent/agent/checks.d/postgres.py")

import sys
import pprint
import psycopg2
import datadog_checksd_postgres
from datadog_checksd_postgres import PostgreSql

###
# replace pg8000 with psycopg2 because pg8000 does not work with our arch.
# the postgres agent fails with the following exception:
#
# 2016-08-12 15:50:30 UTC | ERROR | dd.collector | checks.postgres(__init__.py:767) | Check 'postgres' instance #0 failed
# Traceback (most recent call last):
#   File "/opt/datadog-agent/agent/checks/__init__.py", line 750, in run
#     self.check(copy.deepcopy(instance))
#   File "/opt/datadog-agent/agent/checks.d/postgres.py", line 674, in check
#     version = self._get_version(key, db)
#   File "/opt/datadog-agent/agent/checks.d/postgres.py", line 306, in _get_version
#     cursor.execute('SHOW SERVER_VERSION;')
#   File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pg8000/core.py", line 567, in execute
#     self._c.execute(self, "begin transaction", None)
#   File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pg8000/core.py", line 1684, in execute
#     self.handle_messages(cursor)
#   File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pg8000/core.py", line 1761, in handle_messages
#     raise self.error
# ProgrammingError: ('ERROR', '26000', 'prepared statement "pg8000_statement_0" does not exist')
datadog_checksd_postgres.pg = psycopg2
# need to rewire these -- InterfaceError routes to reconnect, ProgrammingError logs a message
datadog_checksd_postgres.InterfaceError = InterfaceError
datadog_checksd_postgres.ProgrammingError = ProgrammingError

###
# remove ssl from the kwargs, otherwise PostgreSql's get_connection fails with the following exception
#
# 2016-08-12 16:10:02 UTC | ERROR | dd.collector | checks.customMetricQuery(__init__.py:767) | Check 'customMetricQuery' instance #0 failed
# Traceback (most recent call last):
#   File "/opt/datadog-agent/agent/checks/__init__.py", line 750, in run
#     self.check(copy.deepcopy(instance))
#   File "/opt/datadog-agent/agent/checks.d/postgres.py", line 673, in check
#     db = self.get_connection(key, host, port, user, password, dbname, ssl)
#   File "/opt/datadog-agent/agent/checks.d/postgres.py", line 586, in get_connection
#     password=password, database=dbname, ssl=ssl)
#   File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
#     conn = _connect(dsn, connection_factory=connection_factory, async=async)
# OperationalError: invalid connection option "ssl"
psycopg2_connect = psycopg2.connect
def connect(*args, **kwargs):
	del kwargs['ssl']
	return psycopg2_connect(*args, **kwargs)
datadog_checksd_postgres.pg.connect = connect

class Psycopg2Check(PostgreSql):
	pass
```

**Comment by bpatelturnitin** [comment]
Also ability to add, custom query in puppet module of dd through puppet interface.

**Comment by remh** [comment]
@sethcleveland could you share more details about what's causing the issue ? What's the custom query that you are running that's failing ?
Also what version of PG are you running ?
Are you hitting pgbouncer or postgres directly ?

**Comment by remh** [comment]
@bpatelturnitin can you open an issue in the puppet module repo please ?

**Comment by sethcleveland** [comment]
This query causes challenges -- cursor.execute('SHOW SERVER_VERSION;'). Its in the stack trace above. It's part of the postgres.py datadog check -- https://github.com/DataDog/dd-agent/blob/master/checks.d/postgres.py#L303. That query runs before any of our custom querys and actually prevents the postgres agent from working. We're hitting the pgbouncer. Querying against postgres works fine with pg8000. FWIW, There's chatter on the pg8000 about querying against a pgbouncer -- https://github.com/mfenniak/pg8000/issues/89, but I don't think there's gonna be much traction/improvment.

It'd be nice to configure which python postgres client to use, or just use psycopg2 and remove pg8000. Is there a reason for using pg8000?

**Comment by sethcleveland** [comment]
Also wanted to mention, we tried the pgbouncer here -- https://github.com/DataDog/dd-agent/blob/master/checks.d/pgbouncer.py#L10. It actually uses the psycopg2 client. It errors for completely different reasons -- something to the effect of "Not Allowed." I'm assuming that's a permission issues. I didn't dig much further because that check lacks the custom metrics ability and the postgres built-in metrics. It'd be nice to "marry" these two modules together. I'm no expert on the field, but at least from our usage, this needs a little tender loving care.

**Comment by sethcleveland** [comment]
Made a tweak to the workaround to ensure reconnection --

```python
# pull in datadog's postgresql AgentCheck
import imp
imp.load_source("datadog_checksd_postgres", "/opt/datadog-agent/agent/checks.d/postgres.py")

import sys
import pprint
import psycopg2
import datadog_checksd_postgres
from datadog_checksd_postgres import PostgreSql

###
# replace pg8000 with psycopg2 because pg8000 does not work with our arch.
# the postgres agent fails with the following exception:
#
# 2016-08-12 15:50:30 UTC | ERROR | dd.collector | checks.postgres(__init__.py:767) | Check 'postgres' instance #0 failed
# Traceback (most recent call last):
#   File "/opt/datadog-agent/agent/checks/__init__.py", line 750, in run
#     self.check(copy.deepcopy(instance))
#   File "/opt/datadog-agent/agent/checks.d/postgres.py", line 674, in check
#     version = self._get_version(key, db)
#   File "/opt/datadog-agent/agent/checks.d/postgres.py", line 306, in _get_version
#     cursor.execute('SHOW SERVER_VERSION;')
#   File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pg8000/core.py", line 567, in execute
#     self._c.execute(self, "begin transaction", None)
#   File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pg8000/core.py", line 1684, in execute
#     self.handle_messages(cursor)
#   File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pg8000/core.py", line 1761, in handle_messages
#     raise self.error
# ProgrammingError: ('ERROR', '26000', 'prepared statement "pg8000_statement_0" does not exist')
datadog_checksd_postgres.pg = psycopg2
# need to rewire these -- InterfaceError routes to reconnect, ProgrammingError logs a message
datadog_checksd_postgres.InterfaceError = InterfaceError
datadog_checksd_postgres.ProgrammingError = ProgrammingError

###
# remove ssl from the kwargs, otherwise PostgreSql's get_connection fails with the following exception
#
# 2016-08-12 16:10:02 UTC | ERROR | dd.collector | checks.customMetricQuery(__init__.py:767) | Check 'customMetricQuery' instance #0 failed
# Traceback (most recent call last):
#   File "/opt/datadog-agent/agent/checks/__init__.py", line 750, in run
#     self.check(copy.deepcopy(instance))
#   File "/opt/datadog-agent/agent/checks.d/postgres.py", line 673, in check
#     db = self.get_connection(key, host, port, user, password, dbname, ssl)
#   File "/opt/datadog-agent/agent/checks.d/postgres.py", line 586, in get_connection
#     password=password, database=dbname, ssl=ssl)
#   File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
#     conn = _connect(dsn, connection_factory=connection_factory, async=async)
# OperationalError: invalid connection option "ssl"
psycopg2_connect = psycopg2.connect
def connect(*args, **kwargs):
    del kwargs['ssl']
    return psycopg2_connect(*args, **kwargs)
datadog_checksd_postgres.pg.connect = connect

class Psycopg2Check(PostgreSql):
    pass
```

**Comment by remh** [comment]
@sethcleveland thanks for the feedback.

Is there a reason you cannot connect to postgres directly ? 
We'd like to keep using pg8000 as it's a pure python module, which ensure it will work on all systems that can run python while psyocpg2 might be available in some environments.

**Comment by sethcleveland** [comment]
Did some investigating. All signs point to not connecting directly to postgres for custom metrics. Basically, we're setup to go through pgbouncer for HA, security, and performance reasons. There are other architectural/design reasons that are beyond my understanding at the moment as well.

**Comment by remh** [comment]
@sethcleveland Thanks for the details!

Using pgbouncer for HA is not a great idea for monitoring as you might be querying different PG instances resulting in incoherent metrics. I recommend pointing the agent directly to the local PG instance (it just uses one connection). 

If that's not an option, you should run your modified version as a custom check (just drop it in `/etc/dd-agent/checks.d`).

I'm going to close this issue as switching to psycopg2 for this check will prevent some users from running the check.

**Comment by sethcleveland** [comment]
We don't want to prevent other users from running the check. As it stands, my company can't use the built-in datadog postgres stuff because the checker's postgres client doesn't work with our database configuration. We are a customer and have a support request for this challenge.

Supporting our needs, enables datadog to potentially support others. There's also a cascading effect when we can't use the default stuff, ex. the datadog provided puppet stuff doesn't work anymore. We have to replicate and adjust that. The datadog puppet stuff's missing a deployment model for custom checks.

I would like datadog to provide metrics (including custom metric support) independent of the database client. In other words, we pick the metrics we want along with a client for a database configuration.  By default, the status quo can be maintained with the option to adjust according to different customer needs. For example, a customer can select a subset of the postgres metrics, add a few custom metrics, and pick the right postgres client for the job, with the default pg8000. 

Or, another approach that works for us. Provide custom metric support in the PGBouncer module, and allow the option to disable those built-in metrics (we don't need them at this time).

**Comment by DBLaw** [comment]
Hi @sethcleveland, to be certain we're on the same page, I'm going to have your rep schedule a quick call for us to discuss and find a reasonable way forward for you.

**Comment by sethcleveland** [comment]
Sounds good. I got the invite.

**Comment by sethcleveland** [comment]
Good discussion. Thank you for taking the time to talk about this 👍 .
