### ISSUE TITLE
[docker_daemon] No docker metrics whith systemd 226+

### ISSUE THREAD

**Issue by dadux** [DataDog/dd-agent#2775]
**Problem**
Systemd 226 introduces a new scope unit called init.scope that can encapsulate PID 1 of the system. When starting docker daemon with `native.cgroupdriver=systemd` , the cgroups files are prepended with `/init.scope/` resulting in the dd-agent reporting 0 for any cpu/memory metrics. 

**How to reproduce**
Run dd-agent on a distribution that uses systemd 226+, i.e CoreOS stable 1068.9.0, and check for docker metrics. 

**Workaround**
Override the docker daemon options to `native.cgroupdriver=cgroupfs` .

**Comment by hkaj** [comment]
Hi @dadux 
Thanks for the detailed report. We are investigating this issue and will keep you updated about a fix, stay tuned.

**Comment by remh** [comment]
This was actually fixed with this PR: #2537 
It will go out with our next agent release.

You can start using it using our `nightly` docker tag, but watch out, it's a nightly build and should be considered unstable https://hub.docker.com/r/datadog/docker-dd-agent/tags/

**Comment by dadux** [comment]
Awesome, thanks !
