### ISSUE TITLE
[kubernetes] Expose container restart count

### ISSUE THREAD

**Issue by mikekap** [DataDog/dd-agent#2778]
It would be really nice to be able to monitor container crash loops. `CrashloopBackoff` is a symptom of rapid crashes, but it would be nice to be able to alert on restarts in general.

**Comment by masci** [comment]
Hi @mikekap,
thanks for your feedback!

We're going to ship support for fetching Kubernetes events with the upcoming 5.9, it should help you setting up a monitor for your pods based on their status.

This feature is quite new though, so any feedback is really appreciated: if you think the format of the events we send could be improved in any way, please let us know!

**Comment by therc** [comment]
I think this is fixed in https://github.com/DataDog/dd-agent/pull/3070

No official images for testing yet.

**Comment by ojongerius** [comment]
Looks like 98cf16e932bf587366323ba947d14e669b7fe01a took care of this, and has been release. @mikekap case closed?

**Comment by mikekap** [comment]
Yep, LGTM!
