### ISSUE TITLE
use of old-style '%s' string interpolation borks use of SQL '%' wildcard char

### ISSUE THREAD

**Issue by dblackdblack** [DataDog/dd-agent#2792]
https://github.com/DataDog/dd-agent/blob/d18f3cbd9049d80280caa72b073190ad82377795/checks.d/postgres.py#L489

My query string includes the SQL `%` wildcard character which I have to double-escape as `%%` or else I get a python string formatting exception

At the very least, this should be well documented or cause a warning to be emitted into the logs.

**Comment by remh** [comment]
Thanks for the feedback @dblackdblack 
Can you please provide the informations asked in the Issue Template please ? https://github.com/DataDog/dd-agent/blob/master/.github/ISSUE_TEMPLATE.md It will help us fixing the issue.
