### ISSUE TITLE
[disk] Host disk metrics missing when running under docker

### ISSUE THREAD

**Issue by mikekap** [DataDog/dd-agent#2806]
*_Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) *_

```
# /etc/init.d/datadog-agent info
===================
Collector (v 5.8.5)
===================

  Status date: 2016-09-04 19:37:00 (16s ago)
  Pid: 14
  Platform: Linux-4.4.0-21-generic-x86_64-with-debian-8.5
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: -0.0053 s
    System UTC time: 2016-09-04 19:37:16.422458

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    ec2-hostname: ip-10-0-14-133.us-west-2.compute.internal
    local-ipv4: 10.0.14.133
    hostname: ip-10-0-14-133.us-west-2.compute.internal
    socket-hostname: dd-agent-eu48j
    local-hostname: ip-10-0-14-133.us-west-2.compute.internal
    instance-id: i-057b449523a8ad6cd
    socket-fqdn: dd-agent-eu48j

  Checks
  ======

    fluentd
    -------
      - instance #0 [OK]
      - Collected 3 metrics, 0 events & 2 service checks

    kubernetes
    ----------
      - instance #0 [OK]
      - Collected 663 metrics, 0 events & 2 service checks

    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check

    disk
    ----
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 1 service check

    docker_daemon
    -------------
      - instance #0 [OK]
      - Collected 440 metrics, 0 events & 2 service checks


  Emitters
  ========

    - http_emitter [OK]

===================
Dogstatsd (v 5.8.5)
===================

  Status date: 2016-09-04 19:37:14 (2s ago)
  Pid: 11
  Platform: Linux-4.4.0-21-generic-x86_64-with-debian-8.5
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 166
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.8.5)
===================

  Status date: 2016-09-04 19:37:14 (2s ago)
  Pid: 13
  Platform: Linux-4.4.0-21-generic-x86_64-with-debian-8.5
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 465 bytes
  Queue Length: 1
  Flush Count: 554
  Transactions received: 249
  Transactions flushed: 248
  Transactions rejected: 0
```

**Additional environment details (Operating System, Cloud provider, etc):**
Running on kubernetes in EC2, but I don't think that matters.

**Steps to reproduce the issue:**
1. Run dd-agent in a docker container (even with `--privileged`). 

**Describe the results you received:**
Only some metrics are reported (for the root volume mostly).

**Describe the results you expected:**
All volumes are reported; even those used by other containers.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens because both `df` and `psutil` use `statvfs` to get the volume usage information. `statvfs` takes the path to the mount - not the path to the device. Because dd-agent is running in a cgroup, that path doesn't exist in the cgroup, so we can't get the volume information there. Some options:
- Rely on `/proc/diskstats` instead. This may not be 1:1 compatible with the existing reporting, but it's what prometheus uses. Perhaps only use this for docker under a new metric prefix?
- Similarly - switch to `lsblk`
- Mount the root filesystem somewhere like `/rootfs` in the docker container and `chroot` there or translate paths (prefix them with `/rootfs`). This may be hard to make work with `df` since `chroot` may lose the `df` binary.
- This works on custom installs: if your volumes are only ever mounted under one directory, (e.g. `/data`), you can mount `/data/` in the `dd-agent` container and the reporting will work, but this doesn't generalize.

**Comment by gmmeyer** [comment]
Thanks for the issue report @mikekap!

This is definitely something we could improve, and you've given us some good suggestions for improvement.

**Comment by xvello** [comment]
Dear Mike,

The layered nature of the Linux storage subsystem (block devices, logical volumes and partitions) makes it necessary to have a partition mounted to be able to report its free space, as the block layer has no means of knowing what part if the allocated size is used or free, and that logic is specific to every filesystem.

dd-agent will report disk metrics and rates for every partition that is accessible (even if only partially) to its container, but not others, as this separation is enforced by cgroups / docker. To allow disk usage reporting on a partition, you need to expose it through a docker volume via the -v argument to docker run.

We wrote a knowledge base article to sum up the various ways to address the issue: https://help.datadoghq.com/hc/en-us/articles/115001786703

**Comment by untitaker** [comment]
This would've been super-useful information to find at https://docs.datadoghq.com/integrations/disk/ -- also the knowledge base article you link 404s.

**Comment by GaboFDC** [comment]
If anyone has issues with this still, and as the previous link doesn't work, refer to: https://docs.datadoghq.com/agent/faq/host-metrics-with-the-container-agent/#disk-check
