### ISSUE TITLE
[directory] Add modified_sec_ago.min metric

### ISSUE THREAD

**Issue by jeffbyrnes** [DataDog/dd-agent#2831]
I have this situation:
- A directory of files that, as time passes, cease to be modified
- We wish to ensure that files representing future events continue to be updated until the moment in time they represent has passed (and thus, they become history)

I’m keeping an eye on time series data on disk that includes future predictions. Thus have a `modified_sec_ago.min` and check that value is no greater than 3 hours would be handy.

**Comment by jeffbyrnes** [comment]
@ironwallaby @thegrossman, FYI

**Comment by johnglow** [comment]
Has anyone found a solution for this?
In my case I want to verify that a backup is being created everyday.
Perhaps there is a different way to do that. If so please let me know.

**Comment by jeffbyrnes** [comment]
@johnglow I’ve been using [`stripe/datadog-checks/checks.d/file.py`](https://github.com/stripe/datadog-checks/blob/master/checks.d/file.py). Check out the [“File” section of their README for how to use it](https://github.com/stripe/datadog-checks#file).

To use it, I drop it on-disk using my wrapper Chef cookbook for installing & configuring the Datadog Agent:

```ruby
remote_file "#{dd_config_dir}/checks.d/file.py" do
  source 'https://raw.githubusercontent.com/stripe/datadog-checks/master/checks.d/file.py'
  owner  'dd-agent'
  group  'dd-agent'
  mode   '0600'
end
```

**Comment by jeffbyrnes** [comment]
Closing as stale
