### ISSUE TITLE
[kubenetes] Lookup k8s API endpoint using environment variables

### ISSUE THREAD

**Issue by rosskukulinski** [DataDog/dd-agent#2837]
From: https://github.com/DataDog/dd-agent/pull/2551

The Kubernetes integration finds the `kubernetes` api using DNS which is not always available.  Specifically, not all namespaces will have the `kubernetes` service running (e.g. `kube-system`).

The preferred mechanism to get the API server host/port is by using the environmental variables injected into every pod: KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT.

Relevant code: https://github.com/DataDog/dd-agent/blob/master/utils/kubeutil.py#L66

**Comment by onbjerg** [comment]
I'll take this when #2728 is merged.

**Comment by xvello** [comment]
Hello,

5.14 uses `KUBERNETES_SERVICE_HOST`, and 5.15 will also use `KUBERNETES_SERVICE_PORT`, plus configurable host and port for the apiserver (see 
https://github.com/DataDog/dd-agent/pull/3401)

Regards
