### ISSUE TITLE
[kubernetes] Events from all namespaces

### ISSUE THREAD

**Issue by rosskukulinski** [DataDog/dd-agent#2838]
from https://github.com/DataDog/dd-agent/pull/2551

Currently the Kubernetes events feature only gets events from the `default` namespace.  This means that datadog is unable to capture critical events from the `kube-system` namespace as well as any other user-defined namespaces.

I believe the dd-agent kubernetes configuration should support two options:
1. Capture events from all namespaces (defaults to `False`)
2. Capture events from list of namespaces (defaults to `default` only)

This will not change the functionality of new 5.9 deployments but will enable improved kubernetes support down the road for all users.

relevant code: https://github.com/DataDog/dd-agent/blob/master/checks.d/kubernetes.py#L362

**Comment by hkaj** [comment]
Hi @rosskukulinski

Thanks for opening this issue. As @masci mentioned you can specify another namespace in the instance of `kubernetes.yaml` (to see how we use the namespace parameter, see: https://github.com/DataDog/dd-agent/blob/master/checks.d/kubernetes.py#L361)
Although it should be documented, and we should probably allow collecting events from all/several namespaces.

The options you suggest seem reasonable and we'll work on supporting them for the next release.

Thanks again

**Comment by AndrewDryga** [comment]
+1

**Comment by olivielpeau** [comment]
Moving to the 5.11 milestone, the merge window for 5.10 is closing soon and we still need to assess what solution would be best to allow collecting events from more than one namespace.

**Comment by alexouzounis** [comment]
To me, it looks like we can specify one namespace at a time https://github.com/DataDog/dd-agent/blob/master/checks.d/kubernetes.py#L426 .Hence we would need a dd agent per namespace to watch for events. Would it possible to get wildcard support ?

**Comment by hkaj** [comment]
Yes @alexouzounis that's the plan (allowing a list of namespace and probably regex). It's still in our backlog but should be ready for 5.11

**Comment by alexouzounis** [comment]
Nice! Will keep an eye on it then ;)

**Comment by mazzy89** [comment]
Not clear why it has been closed. Here I've reported a proposal to design a solution https://github.com/DataDog/docker-dd-agent/issues/215
