### ISSUE TITLE
[mysql] No timeouts on connecting/queries can block all checks

### ISSUE THREAD

**Issue by Xon** [DataDog/dd-agent#2854]
The MySQL check does not appear to have any hard-time outs, and if the connect process becomes deadlocked in MariaDB, the check hangs and prevents the collector from functioning.

This lasted >45 minutes before the MySQL server process was killed and dd-agent resumed expected operation.

Agent state

```
===================
Collector (v 5.8.5)
===================

  Status date: 2016-09-16 17:32:19 (61s ago)
  Pid: 30646
  Platform: Linux-2.6.32-xxxxxxxxx
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======

    NTP offset: 0.0001 s
    System UTC time: 2016-09-16 17:33:22.119772

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    No host information available yet.

  Checks
  ======

    No checks have run yet.

  Emitters
  ========

    No emitters have run yet.

===================
Dogstatsd (v 5.8.5)
===================

  Status date: 2016-09-16 17:33:18 (4s ago)
  Pid: 30395
  Platform: Linux-2.6.32-xxxxxxxxx
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 21
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.8.5)
===================

  Status date: 2016-09-16 17:33:23 (0s ago)
  Pid: 30397
  Platform: Linux-2.6.32-xxxxxxxxx
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log, syslog:/dev/log

  Queue Size: 0 bytes
  Queue Length: 0
  Flush Count: 63
  Transactions received: 20
  Transactions flushed: 20
  Transactions rejected: 0
```

collector.log after restarting the agent;

```
2016-09-16 17:50:40 UTC | INFO | dd.collector | root(agent.py:353) | Running in foreground
2016-09-16 17:50:40 UTC | INFO | dd.collector | daemon(daemon.py:157) | Starting
2016-09-16 17:50:40 UTC | WARNING | dd.collector | daemon(daemon.py:168) | pidfile doesn't contain the pid of an agent process. Starting normally
2016-09-16 17:50:40 UTC | INFO | dd.collector | daemon(daemon.py:171) | Pidfile: /opt/datadog-agent/run/dd-agent.pid
2016-09-16 17:50:41 UTC | INFO | dd.collector | config(config.py:1024) | initialized checks.d checks: ['system_core', 'network', 'mysql', 'redisdb', 'system_swap', 'ntp', 'disk']
2016-09-16 17:50:41 UTC | INFO | dd.collector | config(config.py:1025) | initialization failed checks.d checks: []
2016-09-16 17:50:41 UTC | INFO | dd.collector | checks.collector(datadog.py:48) | Dogstream parsers: []
2016-09-16 17:50:45 UTC | INFO | dd.collector | checks.collector(collector.py:414) | Running check system_core
2016-09-16 17:50:45 UTC | INFO | dd.collector | checks.collector(collector.py:414) | Running check network
2016-09-16 17:50:45 UTC | INFO | dd.collector | checks.collector(collector.py:414) | Running check mysql
```

CentOS 6.8, MariaDB 10.1.17 from mariadb.org's yum repo.

**Steps to reproduce the issue:**
1. MySQL/MariaDB suffered an internal deadlock, which accepts an TCP connect & login but refuses to finish the login process.
2. dd-agent's collector essentially hangs.

**Describe the results you received:**
Datadog collector to fail the MySQL check, but other check would continue to work

**Describe the results you expected:**
Datadog collector stopped reporting any checks.

**Additional information you deem important (e.g. issue happens only occasionally):**
MySQL/MariaDB suffered an internal deadlock

Connecting with the configured user for dd-agent resulted in the mysql command line client hanging after entering the password. Gracefully stopping MySQL did not work, and required kill -9 to terminate.

Snippet from the MariaDB error log;

```
--Thread 140693152380672 has waited at btr0cur.cc line 258 for 272.00 seconds the semaphore:
X-lock (wait_ex) on RW-latch at 0x7ff65173dba0 '&block->lock'
a writer (thread id 140693152380672) has reserved it in mode  wait exclusive
number of readers 1, waiters flag 1, lock_word: ffffffffffffffff
Last time read locked in file btr0cur.cc line 258
Last time write locked in file /home/buildbot/buildbot/build/mariadb-10.1.17/storage/xtradb/btr/btr0cur.cc line 258
Holder thread 0 file not yet reserved line 0
```

**Comment by remh** [comment]
@Xon Thanks for this. Actually the internal watchdog should have kicked in after 2 minutes. It didn't ? Can you reach out to our support team with more details ? Mainly the hostname of the impacted host and all logs that you may have (if you still have them).

There are no easy way with the current agent architecture to properly fix that problem however:
 - We are in the process of moving to a completely different architecture
 - The watchdog should have kicked in and restarted the agent, we definitely need to have a look if that was not the case.

**Comment by Xon** [comment]
@remh This has just happened again on v5.10.0. This time it looks like the agent was able to cleanly shutdown, even if it blocked all other checks for upto ~17 minutes after which the DB node it was trying to talk to crashed.

**Comment by masci** [comment]
The new agent will have a global watchdog for any check running, we're not going to backport the feature on the current one.
