### ISSUE TITLE
STOP RabbitMQ regex matching group dark magic and allow set tags directly (feature request) 

### ISSUE THREAD

**Issue by sunshineo** [DataDog/dd-agent#2893]
We were mis-guided by your article https://help.datadoghq.com/hc/en-us/articles/211590103-Tagging-RabbitMQ-queues-by-tag-family

![mis-guide](https://cloud.githubusercontent.com/assets/1072766/19165733/d8a75a0c-8bb9-11e6-90ee-a338379d456a.jpg)

It seems you have strict requirement about the regular expression. Something about the first matching group in the regular expression. We are still figuring it out.

PLEASE CORRECT THE ARTICLE. PLEASE CORRECT THE ARTICLE. PLEASE CORRECT THE ARTICLE.

PLEASE READ PLEASE READ PLEASE READ:
One dev can do this in a day but it has great value. Stop using this dark magic regular expression matching group thing to tag a rabbit mq. Support tag queue specifically in the rabbitmq.yaml configuration. Here is an example:

![suggestion](https://cloud.githubusercontent.com/assets/1072766/19165744/e71dafa0-8bb9-11e6-8ee6-c2246a843fdc.jpg)

**Comment by sunshineo** [comment]
Can someone have a look at this?

**Comment by masci** [comment]
Hi @sunshineo,

THANKS FOR REPORTING THANKS FOR REPORTING THANKS FOR REPORTING 😄 

I've requested a fix for the docs, thanks for spotting the error.
Regarding the feature you're requesting, I agree it makes sense to have it so I'm adding this to our queue, we'll keep you posted.

**Comment by sunshineo** [comment]
Thank you @masci ! It's awesome!

**Comment by l0k0ms** [comment]
KB updated :)
