### ISSUE TITLE
[rabbitmq] make ssl verification optional

### ISSUE THREAD

**Issue by iancward** [DataDog/dd-agent#2905]
*_Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) *_

```
[root@myhost01 conf.d]# service datadog-agent info
===================
Collector (v 5.9.1)
===================

  Status date: 2016-10-11 12:14:09 (3s ago)
  Pid: 12084
  Platform: Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: 0.0005 s
    System UTC time: 2016-10-11 19:14:12.603287

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    agent-hostname: myhost01
    hostname: myhost01
    socket-fqdn: MYHOST01.MYDOMAIN.COM

  Checks
  ======

    nginx
    -----
      - instance #0 [OK]
      - Collected 7 metrics, 0 events & 2 service checks

    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check

    disk
    ----
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 1 service check

    rabbitmq
    --------
      - instance #0 [OK]
      - Collected 0 metrics, 0 events & 2 service checks

    network
    -------
      - instance #0 [OK]
      - Collected 15 metrics, 0 events & 1 service check


  Emitters
  ========

    - http_emitter [OK]

===================
Dogstatsd (v 5.9.1)
===================

  Status date: 2016-10-11 12:14:04 (9s ago)
  Pid: 12081
  Platform: Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 3
  Packet Count: 28
  Packets per second: 0.0
  Metric count: 14
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.9.1)
===================

  Status date: 2016-10-11 12:14:14 (0s ago)
  Pid: 12083
  Platform: Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 540 bytes
  Queue Length: 1
  Flush Count: 10
  Transactions received: 8
  Transactions flushed: 7
  Transactions rejected: 0

```

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
1. Stand up RabbitMQ server with management plugin enabled
2. Create a self-signed SSL certificate and configure the management plugin to use it
3. Configure datadog's rabbitmq integration on host, using `https://localhost:15672/api/` as `rabbitmq_api_url`
4. Manually execute check for rabbitmq integration

**Describe the results you received:**

```
[root@myhost01 conf.d]# sudo -u dd-agent dd-agent check rabbitmq
2016-10-11 12:16:39,975 | WARNING | dd.collector | checks.disk(disk.py:87) | Using `use_mount` in datadog.conf has been deprecated in favor of `use_mount` in disk.yaml
2016-10-11 12:16:39,983 | INFO | dd.collector | config(config.py:1061) | initialized checks.d checks: ['nginx', 'ntp', 'disk', 'rabbitmq', 'network']
2016-10-11 12:16:39,984 | INFO | dd.collector | config(config.py:1062) | initialization failed checks.d checks: []
2016-10-11 12:16:39,984 | INFO | dd.collector | checks.collector(collector.py:526) | Running check rabbitmq
2016-10-11 12:16:40,014 | ERROR | dd.collector | checks.rabbitmq(rabbitmq.py:163) | Error executing check: Cannot open RabbitMQ API url: https://localhost:15672/api/queues [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
Metrics: 
[]
Events: 
[]
Service Checks: 
[{'check': 'rabbitmq.status',
  'host_name': 'myhost01',
  'id': 1,
  'message': u'Error executing check: Cannot open RabbitMQ API url: https://localhost:15672/api/queues [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)',
  'status': 2,
  'tags': None,
  'timestamp': 1476213400.014164}]
Service Metadata: 
[{}]
    rabbitmq
    --------
      - instance #0 [OK]
      - Collected 0 metrics, 0 events & 1 service check
```

**Describe the results you expected:**
That the code should support the ability to selectively enable/disable ssl verification on a per-integration or per-instance basis. Currently the python `requests` library is called, but no `verify=` option is passed, so this is not configurable.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Comment by iancward** [comment]
I may be able to undertake the effort to add this feature; however, I'd want to know if it would be better if ssl verification should be a per-instance configuration option (like the [mesos integration](https://github.com/DataDog/dd-agent/pull/2809)) or a per-integration configuration (e.g. init_config option, like the [openstack integration](https://github.com/DataDog/dd-agent/blob/master/checks.d/openstack.py#L135)).

**Comment by iancward** [comment]
It looks like the mesos integration and the http check both use an instance variable: https://github.com/DataDog/dd-agent/blob/master/conf.d/http_check.yaml.example#L60

**Comment by masci** [comment]
Hi @iancward and thanks for reporting!

Yes, I think the right place is putting the setting at the instance level. I've added this to our queue but if you want to give a shot to it and open a PR, that would speed up the process.

**Comment by iancward** [comment]
@masci I believe I have something together, but I'm trying to sort out how to add a test for it. I'll also need to go through my employer's review process in order to submit the code.

**Comment by masci** [comment]
If you need any help with testing, please let me know!
