### ISSUE TITLE
Docker_daemon check metrics: what is 'docker.cpu.throttled' metric. Can't found in Datadog-Docker Integration docs

### ISSUE THREAD

**Issue by xufeibuaa** [DataDog/dd-agent#2911]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
(paste your output here)
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
1. Use docker_daemon check. Config docker_daemon.yaml url to unix://var/run/docker.sock
2. Restart dadadog-agent
3.

**Describe the results you received:**
In the metrics, I find 'docker.cpu.throttled', but I can't find that in  Datadog-Docker Integration docs.
What means?
tkx
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by hkaj** [comment]
Hi @xufeibuaa 
Thanks for reporting this. The description should be in the Metrics tab of [the docker tile](https://app.datadoghq.com/account/settings#integrations/docker), but it looks like we forgot to add it.

We'll fix this, in the meantime I can clarify it for you:
`docker.cpu.throttled` is directly extracted from the cgroup file `cpu.stat`'s `nr_throttled` value, which represents the "number of times the group has been throttled/limited"\[0\]. The group being the container's cgroup.

It is reported as a rate, so the value we send is the difference between the current value and the value at the previous collector run (15 seconds ago by default).

Hope that helps. I'm closing the issue, but feel free to reopen if you have more questions.

\[0\]: [https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt](https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt)

**Comment by xufeibuaa** [comment]
thks
