### ISSUE TITLE
How to change the collector rate. By default, collector run pre 15 seconds .

### ISSUE THREAD

**Issue by xufeibuaa** [DataDog/dd-agent#2917]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
(paste your output here)
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by hkaj** [comment]
Hi @xufeibuaa 
You will find documentation about this here: https://help.datadoghq.com/hc/en-us/articles/204261645-How-do-I-change-the-collection-frequency-for-the-agent-

Closing this issue but feel free to reopen if you have more questions.
