### ISSUE TITLE
[mysql] Warning: Maximum number (20) of custom queries reached.  Skipping the rest.

### ISSUE THREAD

**Issue by n0ts** [DataDog/dd-agent#2922]
Hello, I use mysql custom about 30 queries.
The datadog agent got a warning.

```
    mysql
    -----
      - instance #0 [WARNING]
          Warning: Maximum number (20) of custom queries reached.  Skipping the rest.
      - Collected 42 metrics, 0 events & 1 service check
```

Why MAX_CUSTOM_QUERIES is 20?
I want to set my configuration the MAX_CUSTOM_QUERIES.

**Comment by irabinovitch** [comment]
@n0ts apologies for the delay, MAX_CUSTOM_QUERIES can now be overridden via the MySQL integrations config file. See an example here: https://github.com/DataDog/integrations-core/blob/master/mysql/datadog_checks/mysql/data/conf.yaml.example#L65

We set the default to 20 a reasonable default to protect your bill and agent run times, but you're welcome to set it higher as you see fit!
