### ISSUE TITLE
[kubernetes] Integration only works when run in a Pod

### ISSUE THREAD

**Issue by jonmoter** [DataDog/dd-agent#2927]
I am building a Kubernetes cluster from scratch, and installing the datadog on each host, including the etcd nodes. I want to run the agent as a system-level service, so that it works even if the Kubernetes components themselves (like kublet) fail. Therefore, I don't want to run it as a pod or daemonset.

The Kubernetes integration code assumes that the agent is running inside a pod. For example, it assumes that it can reach the API server by making a request to "https://kubernetes" (actually, this was changed yesterday to look up an ENV var), and it assumes service tokens can be found in [/run/secrets/kubernetes.io](https://github.com/DataDog/dd-agent/blob/master/utils/kubeutil.py#L34-L35).

It would be great if I could specify a kubeconfig.yml file that it would read for credentials, or configure it to specify a service token or client certificate I could use to authenticate with the API server.

**Comment by xvello** [comment]
Hello,

This is addressed in https://github.com/DataDog/dd-agent/pull/3401 and 
https://github.com/DataDog/integrations-core/pull/508 that are scheduled to be merged in 5.15.
Would you be willing to test the release candidate?

**Comment by xvello** [comment]
Closing as #3401 is merged
