### ISSUE TITLE
kubernetes configuration for dd-agent uses incorrect value for env variable KUBERNETES

### ISSUE THREAD

**Issue by basilboli** [DataDog/dd-agent#2961]
During initial setup of dd-agent default kubernetes configuration proposed by [Installation  Wizard](https://app.datadoghq.com/signup/agent#kubernetes)  uses incorrect value **yes** as a value of environment variable KUBERNETES :  

```
   env:
          - name: API_KEY
            value: xxxxxxxxxxx
          - name: KUBERNETES
            value: yes     
```

As far as I understand value **yes** resolves to boolean by [kubernetes validation](https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/vendor/gopkg.in/yaml.v2/resolve.go) when expected type is string.

Using "yes" instead of yes fixes the problem.

**Additional environment details (Operating System, Cloud provider, etc):**

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Steps to reproduce the issue:**
1. kubectl create -f dd-agent.yaml 

**Describe the results you received:**

```
error validating "kubernetes/daemonsets/dd-agent.yaml": error validating data: expected type string, for field spec.template.spec.containers[0].env[1].value, got bool; if you choose to ignore these errors, turn validation off with --validate=false
```

**Describe the results you expected:**

I expect kubernetes resources to be created successfully with the following message : 

```
daemonset "dd-agent" created
```

**Comment by remh** [comment]
Thanks for the feedback @basilboli .
That was indeed an issue, we fixed the manifest: https://app.datadoghq.com/account/settings#agent/kubernetes

Thanks again!
