### ISSUE TITLE
OpLog Stats for MongoDB check rely on deprecated namespace.

### ISSUE THREAD

**Issue by amol-** [DataDog/dd-agent#2992]
The mongodb check uses the `local.system.namespaces` collection to lookup for the oplog ( https://github.com/DataDog/dd-agent/blob/master/checks.d/mongo.py#L936 ) 

This collection has actually been deprecated since MongoDB 3.0 (see [https://docs.mongodb.com/manual/reference/system-collections/#<database>.system.namespaces](https://docs.mongodb.com/manual/reference/system-collections/#<database>.system.namespaces) ) and is in fact not existing on our system.

This leads to the agent not reporting any oplog detail even though the oplog collection is available:
```
PRIMARY> db.getCollectionInfos()
[
	{
		"name" : "oplog.rs",
		"options" : {
			"capped" : true,
			"size" : 5906779904,
			"autoIndexId" : false
		}
	},
```

**Comment by gmmeyer** [comment]
Thanks for the report @amol-! This seems like an important issue, I've added it to our internal work tracker and hopefully we'll get to fixing it soon!

**Comment by amol-** [comment]
Any news on this? I can contribute a pull request if that is appreciated

**Comment by gmmeyer** [comment]
We're hoping to implement this for the next release in about 2 months, but I don't think anyone has worked on it yet. If you would like to do it, please go ahead. We'd definitely appreciate it. 😄

**Comment by masci** [comment]
Fixed in https://github.com/DataDog/integrations-core/pull/491
