### ISSUE TITLE
More metrics from Kubernetes State API

### ISSUE THREAD

**Issue by therc** [DataDog/dd-agent#3045]
5.10 introduced new metrics from the kubernetes-state-metrics API.
There are still some in the API that haven't made it to DataDog, e.g.:

kube_pod_container_status_ready{container="dd-agent",namespace="kube-system",pod="dd-agent-0fv0y"} 1
kube_pod_container_status_restarts{container="dd-agent",namespace="kube-system",pod="dd-agent-0fv0y"} 0
kube_pod_container_status_running{container="dd-agent",namespace="kube-system",pod="dd-agent-0fv0y"} 1
kube_pod_container_status_terminated{container="dd-agent",namespace="kube-system",pod="dd-agent-0fv0y"} 0
kube_pod_container_status_waiting{container="dd-agent",namespace="kube-system",pod="dd-agent-0fv0y"} 0

kube_pod_container_requested_cpu_cores{container="kubedns",namespace="kube-system",node="10.X.Y.Z",pod="kube-dns-v20-juul3"} 0.1
kube_pod_container_requested_memory_bytes{container="kubedns",namespace="kube-system",node="ip-10.X.Y.Z",pod="kube-dns-v20-juul3"} 1.048576e+08

At least the restarts and the requested resources (as opposed to limits) are very interesting to us.

I guess one question is how to map the pod and container names into DataDog: separate tags or combined into one?

**Comment by schasse** [comment]
+1

**Comment by ojongerius** [comment]
Is the plan to keep this as the meta issue for improvements?

**Comment by ahawkins** [comment]
I think #3305 dupes this.

**Comment by hkaj** [comment]
this should be fixed now, we're also working on supporting kube-state-metrics v0.5
