### ISSUE TITLE
Bug? Cannot compute CPU stats after restart datadog agent in docker-dd-agent container

### ISSUE THREAD

**Issue by xufeibuaa** [DataDog/dd-agent#3064]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
(paste your output here)
```
![image](https://cloud.githubusercontent.com/assets/17919255/20952943/fb6b1006-bc6a-11e6-8847-8690d591936d.png)

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
1. run docker-dd-agent container
2. exec container and /opt/datadog-agent/agent/agent.py restart
3. tail -f /var/log/datadog/collector.log

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
But if I restart docker-dd-agent container: docker restart docker-dd-agent. Everything is ok

**Comment by xufeibuaa** [comment]
agent version 5.10.1, the latest version

**Comment by masci** [comment]
My guess is something is altering the PATH variable and the Agent is not able to find `mstat` anymore after the restart. You seem to run a couple of custom checks, can you please send a flare[0] and contact support providing any info about those checks you think it might be useful to debug your issue?

Thanks in advance!

[0] `docker exec -it dd-agent /etc/init.d/datadog-agent flare` should work

**Comment by xufeibuaa** [comment]
The same result even I delete the custom checks.

**Comment by remh** [comment]
@xufeibuaa you shouldn't run `/opt/datadog-agent/agent/agent.py restart`
If you need to restart the collector, please run:
```bash
/opt/datadog-agent/bin/supervisorctl -c /etc/dd-agent/supervisor.conf restart datadog-agent:collector
```
instead.

**Comment by xufeibuaa** [comment]
thanks
