### ISSUE TITLE
[core] disk check incorrectly reports metrics for rootfs

### ISSUE THREAD

**Issue by lachlancooper** [DataDog/dd-agent#3081]
On systems with a rootfs device listed in `/etc/mtab`, disk.py reports metrics for that device. These metrics do not reflect the actual usage of the device, but instead mirror those of the filesystem mounted at `/`. This leads to a proliferation of duplicate metrics.

I have worked around this issue by adding `rootfs` to `excluded_filesystems` in the config, but the core problem with the check should be addressed.

**Additional environment details (Operating System, Cloud provider, etc):**
Tested on CentOS 7 and Debian 8, running on AWS EC2.

**Steps to reproduce the issue:**
1. Provision a CentOS 7 machine with a single disk volume, `/dev/xvda1`.
1. Configure a `disk` check with default config.
2. Run the check (`sudo -u dd-agent dd-agent check disk`).

**Describe the results you received:**
Each metric is reported twice; once with the incorrect device_name `rootfs`, and once with the correct device_name `/dev/xvda1`. For example:

```
2016-12-14 15:34:41,159 | INFO | dd.collector | checks.collector(collector.py:542) | Running check disk
Metrics:
[('system.fs.inodes.used',
  1481690081,
  98131,
  {'device_name': 'rootfs',
   'hostname': 'fe1.test',
   'type': 'gauge'}),
('system.fs.inodes.used',
  1481690081,
  98131,
  {'device_name': '/dev/xvda1',
   'hostname': 'fe1.test',
   'type': 'gauge'}),
...
```

**Describe the results you expected:**
rootfs should be excluded from metric reporting.

**Additional information you deem important (e.g. issue happens only occasionally):**
disk.py gathers a list of partitions using `psutil.disk_partitions`, which on Linux ultimately examines the file `/etc/mtab`. By default psutil will exclude non-block devices such as rootfs or tmpfs (as determined by examining `/proc/filesystems`), but disk.py explicitly requests all filesystems with `all=True`.

Older CentOS and Debian releases are not affected because their `/etc/mtab` is a normal file instead of a symlink to `/proc/self/mounts` or `/proc/mounts`. Only these latter list rootfs.

My preferred solution would be to exclude non-block devices by instead calling `psutil.disk_partitions` with `all=False`. However, this would have the side effect of excluding all tmpfs devices, which some users may prefer to monitor. This could perhaps be made into a config option.

I have not tested this solution on other platforms.

**Comment by sjenriquez** [comment]
Hi @lachlancooper 

Thanks for reaching out with the detailed info! Excluding `rootfs` by default could break some monitors and/or dashboards, so we're not going to exclude it by default. However, I'm adding a note to the yaml file for the disk check about this issue for some Linux distributions: https://github.com/DataDog/integrations-core/pull/263. 

Thanks again for your detailed info here!
