### ISSUE TITLE
Switch `agentConfig` to `agent_config` per PEP-8

### ISSUE THREAD

**Issue by jeffwidman** [DataDog/dd-agent#3083]
In python, this should be `agent_config` not `agentConfig`:
https://github.com/DataDog/dd-agent/blob/master/checks.d/kafka_consumer.py#L25

I tried switching it in some of the built-in checks.d files, but then those break because the agent is passing a kwarg `agentConfig` to the underlying checks, it's not just a positional config. So it needs to be changed globally throughout the project.

**Comment by remh** [comment]
You are right @jeffwidman 
However many integrations (and likely custom checks) rely on this, so we are likely not going to fix it as it's a purely cosmetic issue that could cause things to break if we were to fix it.

Thanks again!
