### ISSUE TITLE
Add support for agent integration to pull Prometheus text-based metrics via HTTP

### ISSUE THREAD

**Issue by aantono** [DataDog/dd-agent#3119]
With Prometheus monitoring system gaining popularity, more and more services/libraries offer exposing/consuming metrics using Prometheus [text4](https://prometheus.io/docs/instrumenting/exposition_formats/#format-version-0.0.4) format.  This can typically be consumed over HTTP configurable endpoint (either `/metrics` or `/prometheus`).
There is already provided Python library for parsing said format, available at https://github.com/prometheus/client_python#parserd

Having an agent check integration for consuming metrics from services/applications that expose it in Prometheus format would be great increase for adoption and transition for users who already use Prometheus or consume Prometheus-based metrics in the text format. (Looking at the agent code, it appears that there is already internal support for Prometheus-based Protobuf encoded metrics, which is what Kubernetes uses to expose it's statistics- https://github.com/DataDog/dd-agent/tree/master/utils/prometheus, https://github.com/DataDog/dd-agent/blob/master/checks.d/kubernetes_state.py#L37)

**Comment by aerostitch** [comment]
#3317 should fit that need.

**Comment by hkaj** [comment]
totally does, closing. Thanks guys :)
