### ISSUE TITLE
php-fpm check does not talk FastCGI

### ISSUE THREAD

**Issue by galaxy4public** [DataDog/dd-agent#3131]
The php-fpm.yaml file proposes to extract the PHP/FPM stats via HTTP.  This means that in order to achieve that one needs a web server reachable to the agent, but it is not always possible.  Imagine that you have a pool of nginx'es talking to a pool of PHP/FPMs through a load-balancer.

The agents are installed on instances and to get the stats from the local to the instance PHP/FPM we need to talk to the PHP/FPM through its socket and not through some webserver out there, since if we do the later chances are that we will get stats from some other instance (since the web server will redirect the request to the load-balancer).

**Comment by ict4ngo** [comment]
+1

**Comment by qbaze** [comment]
+1

**Comment by lamiska** [comment]
+1

**Comment by masci** [comment]
Fixed in https://github.com/DataDog/integrations-core/pull/1997

**Comment by qbaze** [comment]
Nicely done! Thanks!

It would be nice if you document the 'use_fastcgi' param a little in readme. 
I understood how it works and what defaults it uses after I looked at the check code not before.

Thanks!
