### ISSUE TITLE
[jmx] Ignore unavailable instances

### ISSUE THREAD

**Issue by alex-ilyin** [DataDog/dd-agent#3136]
We're using Storm to manage our java applications. This means that new instances can be started and stopped automatically on the servers of our cluster. And different servers may have different number of instances running on them at any given moment of time. They all use ports 16700, 16701, ... and so on to expose jmx metrics. The problem is that if I specify several instances in jmx.yaml to match the maximum possible number of applications running on a server, datadog agent will fail to report metrics for _any_ of them in case some instances are missing. In other words, all instances specified in jmx.yaml should be present on a server which is not possible in our case.

Proposed change: add an ability to mark instances in jmx.yaml as "optional" or add an option to the agent to tolerate missing instances.

Datadog agent version: 5.10.1-1

**Comment by remh** [comment]
@alex-ilyin thanks for the feedback. That shouldn't be the case, can you send us a flare ? 
https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command

If one instance is not working it should error in the logs but it shouldn't impact other instances.

**Comment by alex-ilyin** [comment]
@remh Thanks for the answer. I've added several instances to my config one more time to reproduce the problem and this time it worked :) Probably I've messed something up first time. Sorry to bother you!
