### ISSUE TITLE
mongodb `serverStatus` fails if `auth` is enabled

### ISSUE THREAD

**Issue by xcolour** [DataDog/dd-agent#318]
We use the `serverStatus` command to collect metrics from MongoDB.

If authentication is enabled (that is, `auth = true` in the `mongod.conf`), this command fails with the following error:

```
2012-12-18 23:23:02,884 - checks - ERROR - Unable to get MongoDB status
Traceback (most recent call last):
File "/usr/share/datadog/agent/checks/db/mongo.py", line 113, in check
status = db.command('serverStatus') # Shorthand for {'serverStatus': 1}
File
"/usr/lib/python2.6/site-packages/pymongo-2.4-py2.6-linux-x86_64.egg/pymongo/database.py",
line 395, in command
msg, allowable_errors)
File
"/usr/lib/python2.6/site-packages/pymongo-2.4-py2.6-linux-x86_64.egg/pymongo/helpers.py",
line 144, in _check_command_response
raise OperationFailure(msg % details["errmsg"])
OperationFailure: command SON([('serverStatus', 1)]) failed: exception:
unauthorized db:admin ns:admin lock type:0 client:10.52.30.71
```

NOTE: If the agent is configured to connect to localhost and an admin user has never been created, everything will be fine because mongo allows admin connections to localhost in the absence of admin users. So, make sure you have an admin user to be able to reproduce this issue:

```
$ mongo
> use admin
> db.addUser('admin', 'admin')
```

**Comment by devinrsmith** [comment]
Just ran into this. For me, I had to give the datadog user the additional role of "clusterMonitor" http://docs.mongodb.org/manual/reference/built-in-roles/

**Comment by gdelgado** [comment]
Just ran into this issue and using "devinrsmith" suggestion fixed it. Documentation should be updated in datadog.

**Comment by alq666** [comment]
@gdelgado updated the external documentation first in https://github.com/DataDog/documentation/commit/18323348eff75a90ee7b1891906f5c90834005f7

**Comment by BretFisher** [comment]
db.grantRolesToUser("datadog",[{ role: "clusterMonitor", db:"admin" }])

**Comment by digz6666** [comment]
@BretFisher mine is saying this:
```
2015-12-10T13:01:21.651+0800 Error: not authorized on autoland to execute command { grantRolesToUser: "digz", roles: [ { role: "clusterMonitor", db: "admin" } ], writeConcern: { w: "majority", wtimeout: 30000.0 } } at src/mongo/shell/db.js:1319
```

**Comment by dimsamaras** [comment]
Thanks @devinrsmith.
Here are my 2cents:

i have my db hosted on mLab and the Mongo version is 2.6:
on datadog Agent define:
 - server: mongodb://datadog:pass@mongo-url:mongo-port,mongo-replica-url:mongo-port/**admin**?replicaSet=replica-id

then:

use admin
db.auth("user","pass")
db.createUser("datadog","pass",true)
db.**runCommand**({grantRolesToUser:"datadog",roles:["clusterMonitor"]})

**Comment by DI-DaveGoodine** [comment]
Thank you @dimsamaras  - the db.runCommand finally got the integration working for me.
