### ISSUE TITLE
Datadog 5.11.0 breaks SNMP integration

### ISSUE THREAD

**Issue by baleofhay** [DataDog/dd-agent#3181]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
 snmp
    ----
      - instance #0 [WARNING]
          Warning: Fail to collect some metrics: poll error: Traceback (most recent call last):
          ;  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pysnmp/carrier/asynsock/dispatch.py", line 37, in runDispatcher
              use_poll=True, map=self.__sockMap, count=1)
          ;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 220, in loop
              poll_fun(timeout, map)
          ;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 201, in poll2
              readwrite(obj, flags)
          ;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 123, in readwrite
              obj.handle_error()
          ;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 110, in readwrite
              obj.handle_write_event()
          ;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 468, in handle_write_event
              self.handle_write()
          ;  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pysnmp/carrier/asynsock/dgram/base.py", line 66, in handle_write
              self.socket.sendto(outgoingMessage, transportAddress)
          ;TypeError: getsockaddrarg() takes exactly 2 arguments (6 given)

      - Collected 0 metrics, 0 events & 1 service check

```

**Additional environment details (Operating System, Cloud provider, etc):**
This check is running on Centos 7.1.1503 and had been working just fine.  The agent starts up just fine and the rest of the integrations that we know about are good.  But all our SNMP integrations on all our servers started failing as soon as they bumped to the latest version of the agent.

**Steps to reproduce the issue:**
1. Have a SNMP check that is running with the OID option to directly query an OID.
2. Upgrade the agent from 5.10.0 to 5.11.0 and watch it start spitting out errors.

**Describe the results you received:**
Now we get "No-data" on all our monitors that are watching the service check for SNMP.  The out put also now warning for SNMP in the info page with the above stack trace.

**Describe the results you expected:**
We used to get the integer stored in that OID send to datadog and our monitors report correctly.  

**Additional information you deem important (e.g. issue happens only occasionally):**
We are going to roll back to the last version of datadog agent to make sure this is what is causing the issue.

**Comment by baleofhay** [comment]
Rolling back to 5.10.1-1 fixes the integration issues we are seeing.  Something wrong in latest release.

**Comment by truthbk** [comment]
@baleofhay we have identified the cause. Unfortunately a subdependency (`pyasn1`) we don't have pinned got inadvertently upgraded during the last release. Pinning the dependency to `0.1.9` addresses the issue. See https://github.com/DataDog/dd-agent/pull/3183

**Comment by baleofhay** [comment]
Thank you for your prompt resolution on this issue.

**Comment by mpalermo73** [comment]
It seems (at least) the Mac Package is still broke.  This is `dd-agent` version `5.11.3`.  I downloaded and installed dd-agent on a 100% fresh machine on 2017-06-07.

```
2017-06-08 14:42:53 EDT | WARNING | dd.collector | checks.snmp(__init__.py:675) | Fail to collect some metrics: poll error: Traceback (most recent call last):
;  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pysnmp/carrier/asynsock/dispatch.py", line 37, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 110, in readwrite
    obj.handle_write_event()
;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 468, in handle_write_event
    self.handle_write()
;  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pysnmp/carrier/asynsock/dgram/base.py", line 66, in handle_write
    self.socket.sendto(outgoingMessage, transportAddress)
;TypeError: getsockaddrarg() takes exactly 2 arguments (6 given)
```


```
host:site-packages root# ls -ld /opt/datadog-agent/embedded/lib/python2.7/site-packages/pyasn1*
drwxr-xr-x  11 root  wheel  374 Jun  7 11:00 pyasn1
drwxr-xr-x   9 root  wheel  306 Feb 27 15:14 pyasn1-0.2.2.dist-info
```

**Comment by olivielpeau** [comment]
Unfortunately it appears that the `5.11.3` macOS agent still has this issue. See  https://github.com/DataDog/dd-agent/issues/3380#issuecomment-307218767 that details a workaround
