### ISSUE TITLE
win32_event_log instace issue

### ISSUE THREAD

**Issue by rnpkreddy** [DataDog/dd-agent#3184]
Hi
 we are facing an issue

win32_event_log
Initialization error: Traceback (most recent call last): File "config.pyc", line 919, in _load_file_config File "util.pyc", line 123, in check_yaml Exception: You need to have at least one instance defined in the YAML file for this check 

 we want to have event logs for a sql server. We are getting this error . can you help us.

**Comment by yannmh** [comment]
Sorry for the late answer @rnpkreddy,

It looks like your check is not properly configured. Could you reach out our support team? They'll be able to give you the help you need to get started.
