### ISSUE TITLE
Update DataDog-Couchbase integration to add new N1QL metrics

### ISSUE THREAD

**Issue by kunal711** [DataDog/dd-agent#3216]
We are currently using DataDog-Couchbase integration for monitoring our production Couchbase Cluster but it looks like the integration is still using TAP protocol and is missing all the new N1QL specific metrics. https://github.com/DataDog/integrations-core/blob/master/couchbase/check.py

Can you please update the integration to change to DCP and add new available metrics. 

**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
(paste your output here)
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by zippolyte** [comment]
Hi @kunal711, I just started working on your request, sorry for the wait.

Regarding the new N1QL metrics, I'm having trouble getting the exact metrics listed [here](https://developer.couchbase.com/documentation/server/4.6/monitoring/ui-monitoring-statistics.html#topic16695__query_stats) via the REST API, but I did find [this](https://developer.couchbase.com/documentation/server/4.5/tools/query-monitoring.html). Do these metrics suit your needs ?

**Comment by zippolyte** [comment]
Hey @kunal711, have you had a chance to see if what i'm proposing corresponds to what you need ?

**Comment by kunal711** [comment]
@zippolyte - Sorry for the delay in getting back, the link you included above shows details about queries, those are good to have but I was wondering if it is also possible to add some more stats about Index like: ep_dcp_2i_items_remaining which shows number of documents waiting to be indexed, percentage of index RAM available, etc.

**Comment by zippolyte** [comment]
@kunal711 I'm glad to tell you that I've implemented your request. The changes are on our master branch and will be shipped with the next release.
Closing the issue

**Comment by kunal711** [comment]
Thank you @zippolyte
