### ISSUE TITLE
Cassandra YAML example?

### ISSUE THREAD

**Issue by macalinao** [DataDog/dd-agent#3219]
The link here is broken: http://docs.datadoghq.com/integrations/cassandra/

**Comment by rocky1201** [comment]
looks like all yaml example have been removed :(

**Comment by yannmh** [comment]
I apologize for the inconvenience,

We are actually moving to a different repository structure for the Datadog Agent. 
This repository now hosts the Datadog Agent core while intergrations belongs in [integrations-core](https://github.com/DataDog/integrations-core) and [integrations-extra](https://github.com/DataDog/integrations-extras) repositories.
We'll update the links in the documentation shortly to reflect this.
