### ISSUE TITLE
Monitoring checks at a specific time

### ISSUE THREAD

**Issue by tizzythegrey** [DataDog/dd-agent#3239]
We are in a situation where we need to create monitoring for a specific event but we want to only check for that event at a certain time everyday. How can we accomplish this? Does not look like there is a way. 

e.g monitor if eventA has happened in the last 24Hrs but we want the monitoring check to happen at 11pm everyday. 

So we are looking for some kind of custom monitoring where we can specify exactly when we want the metric to be checked everyday. Thanks for any help on this.

**Comment by degemer** [comment]
Hello @tizzythegrey !

The agent wasn't designed to run checks at a specific time of the day, the closest option we have is the [min_collection_interval](https://github.com/DataDog/dd-agent/blob/da02e5f01b030d2c1cd6682a37eb4f474d6d003d/checks/__init__.py#L337-L338) option that you can set in the `init_config` part of your yaml config file. It guarantees that at least {min_collection_interval} will pass between two check runs (for the check configured with this option).

However I think the best option in your case (once a day) would be to setup a cron, and write a script using [our libraries](http://docs.datadoghq.com/libraries/) to interact with our [API](http://docs.datadoghq.com/api/), and send an event/metric/service check.

So the script would send once a day this event, and you would check for its presence (or absence) using a [event monitor](https://help.datadoghq.com/hc/en-us/articles/203766245-How-can-I-alert-on-events-).

I am not really sure this answers your question, if you want a more specific response you can contact our [support](https://www.datadoghq.com/support/).
