### ISSUE TITLE
Why docker run datadog/docker-dd-agent need 2 minutes on centos? It's so long...

### ISSUE THREAD

**Issue by xufeibuaa** [DataDog/dd-agent#3241]
**Output of the info page **

output - docker run docker-dd-agent:
```
2017年 03月 08日 星期三 10:19:42 CST
c94cc579b4aecc47f2219eafa222ae22e272942d3c58a84c7b6d938f07f8b076
2017年 03月 08日 星期三 10:21:42 CST
```
![image](https://cloud.githubusercontent.com/assets/17919255/23687812/66a4301a-03eb-11e7-8f40-73326184b70f.png)

Additional environment details (Operating System, Cloud provider, etc):
core version
3.10.0-327.4.5.el7.x86_64
lsb_release -a
LSB Version: :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description: CentOS Linux release 7.3.1611 (Core)
Release: 7.3.1611
Codename: Core
docker version
Docker version 1.12.3, build 6b644ec, experimental

Steps to reproduce the issue:

run command: date; docker run -d --restart=always --log-driver=json-file --name dd-agent-test -v /var/run/docker.sock:/var/run/docker.sock -v /proc/:/host/proc/:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro -v /var/log/mathilde/ddagent/:/var/log/mathilde/ddagent/ -e API_KEY=API_KEY -e DD_URL=DD_URL datadog/docker-dd-agent:latest; date
Describe the results you received:
It need 2 minute to run docker-dd-agent container successfully

Describe the results you expected:
The time cost is too long

**Comment by xvello** [comment]
Hello,

This time is indeed longer than what we see on most hosts. We need to analyse your debug logs to see if any blocking calls / request timeouts occur. Could you please get in touch with support@datadoghq.com, they will guide you into sending a debug flare and will have a look at it.

As support is the appropriate channel for resolving this issue, I am closing this ticket.

Regards
