### ISSUE TITLE
Add support for S.M.A.R.T. counters

### ISSUE THREAD

**Issue by PenegalECI** [DataDog/dd-agent#3278]
Even if their aren't the only one, S.M.A.R.T. counters can help to prevent data losses due to disk failures; supporting at least some of them, like Reallocated Sectors Count (0x05), Reported Uncorrectable Errors (0xBB) or Current Pending Sector Count (0xC5) could be very useful to continuously monitor them, instead of relying on a custom script.

**Comment by hush-hush** [comment]
Hello,

Thanks for the feature request. It seems indeed like a good idea. I created a ticket in our internal work management tool.  We will discuss it with the team to see if there’s enough traction for it to be developed. I will answer back when I have more information.

In the meantime, if you want to contribute it we'll be happy to merge a PR.

**Comment by hush-hush** [comment]
I forgot to tell you that if you choose to contribute it, please do it in this repo: https://github.com/DataDog/integrations-extras

**Comment by hush-hush** [comment]
Hi @PenegalECI,

Thanks for the feature request. We've discussed it, and while we agree the feature has merit, unfortunately we're not able to dedicate engineering resources to it at this time. That said, we like the idea and as I said if you submit a PR to our [integrations-extras repo](https://github.com/DataDog/integrations-extras) we're happy to review and merge it. If you have any questions or need assistance with the process, we have [community office hours](https://github.com/DataDog/dd-agent/wiki/Community-Office-Hours) twice a month.
