### ISSUE TITLE
[Kubernetes] Please Collect Deployment/HorizontalPodAutoscaler Metrics

### ISSUE THREAD

**Issue by jcderr** [DataDog/dd-agent#3279]
We would like to monitor the number of pods a deployment has in the cluster as managed by the horizontal pod autoscaler.

Ultimately, we'd like to do things like have a metric on dashboards and monitors like:

* `sum:kubernetes.pods.running{kube_name:some-deployment-name,kube_namespace:default}` 
  * return the number of running pods attached to the `deployment/some-deployment-name`

Currently, this information is only available by filtering on the currently active replicaset. This doesn't work well because replicasets are replaced with every deployment update (ie. `kubectl set image deployment/some-deployment-name mycontainer=jcderr/mycontainer:1.2.3` creates a whole new replicaset, requiring me to then manually update my monitors and dashboards).

* `sum:kubernetes.pods.pending{kube_name:some-deployment-name,kube_namespace:default}`
  * return number of pods currently in pending (eg. unscheduled/unschedulable) status

Having this data would allow us to alert on situations where kubernetes is attempting to horizontally scale beyond the currently provisioned hardware capacity.

**Comment by someword** [comment]
@jcderr 
It looks like kube-state-metrics will be adding support for HPA metrics - https://github.com/kubernetes/kube-state-metrics/pull/71/commits/3186399518e04b0198007828edba571f186a8b13

This would mean you need to run kube-state-metrics deployment though.   Stumbled across this ticket shortly after looking at the above commit and thought I would at least mention this.

**Comment by xvello** [comment]
Hello @jcderr 
I am currently working on this feature (deployment and service tagging) and hope to integrate it in the 5.14 release. I'll ping you once it's merged in master.

**Comment by xvello** [comment]
Hi!
5.14 is at the door and adds kube_service and kube_deployment (but also _replica_set, _daemon_set and _job) tags to autodiscovery, docker.* and kubernetes.* metrics.
See https://github.com/DataDog/dd-agent/pull/3300 https://github.com/DataDog/integrations-core/pull/319 https://github.com/DataDog/dd-agent/pull/3348 and https://github.com/DataDog/integrations-core/pull/434

Cheers
