### ISSUE TITLE
[kubernetes] Add more kube-state-metrics

### ISSUE THREAD

**Issue by ahawkins** [DataDog/dd-agent#3305]
The official kube-state-metrics (https://github.com/kubernetes/kube-state-metrics) lists a bunch of useful metrics to have. Right now the DD agent shows deployments and some node metrics. However the full set of deplyoyment metrics is not reported. DaemonSet, Pod, and ResourceQuota metrics are not reported at all. I'm keen on getting the various `_phase` gauges to monitor all sorts of things. Right now the set of available data is quite limited compared to what's available.

Relevant code here: https://github.com/DataDog/dd-agent/blob/master/utils/kubernetes/kube_state_processor.py#L29

**Comment by austinmoore-** [comment]
On a related note, it seems that upgrade the kube-state-metrics image to the most recent version at the time of writing -  `v0.4.1` - seems to cause problems, and the dd-agent does not report them. `v0.4.0` adds the metrics mentioned in the OP.

**Comment by ahawkins** [comment]
@austinmoore What problem are you having? We're using `0.4.1` without any issue. Metrics are reporting in and checks work as expected.

**Comment by hkaj** [comment]
Hi @ahawkins 
Thanks for reaching out. As you mentioned on #3045 this is a dup. We'll keep the older one for tracking, and we are working on covering more of the kube state metrics.

@austinmoore- Hi there! The agent should work as expected with 0.4.1. Please reach out to support if you have any issue making it work.
