### ISSUE TITLE
Add support for upcoming new kubernetes_state metrics

### ISSUE THREAD

**Issue by yannrouillard** [DataDog/dd-agent#3312]
The kube state metrics application will support a lot of new additional metrics.
See https://github.com/kubernetes/kube-state-metrics/ for the complete list.

This metrics are already available in the current development version and will be part of next release.

It would be cool to support these metrics in datadog agent to allow people using the development version to have access to these metrics.

**Comment by yannrouillard** [comment]
BTW, I filled this bug against this repo and not integration-core as the file to modify is currently located in the utils directory that is still in dd-agent repo.

**Comment by xvello** [comment]
Hello Yann,

We are in the process of merging https://github.com/DataDog/dd-agent/pull/3309 that enables these new metrics. As 5.13 is in feature freeze, this is scheduled for 5.14.
As you can see, the kube_limitrange handling is commented out as these metrics are not released yet and could change. Feel free to uncomment them if needed.

**Comment by olivielpeau** [comment]
Fixed in #3309, closing. Will be included in `5.14.0` release
