### ISSUE TITLE
[kubernetes] Support custom label prefixes

### ISSUE THREAD

**Issue by yolken** [DataDog/dd-agent#3321]
Currently, the `extract_kube_labels` function in `kubeutil.py` hard codes a `kube_` prefix on all pod labels. It would be great if this prefix were configurable (including allowing it to be blank) to give more control over how these labels appear in the Datadog UI.

The use case is that we're also exporting stats from pods (using their labels as tags), and we want the tags to match up in our Datadog dashboards; currently, because of the `kube_` prefix, the stats exported for the Docker Daemon and other integrations don't match up with the ones exported from the app itself.

**Comment by hkaj** [comment]
Hi @yolken 
Thanks for reaching out!
Agreed, it could be useful to make this prefix configurable. I'll add it to our backlog, but if you (or someone else looking at the issue) wants to give it a shot we'll happily review a PR :)
A tip for interested readers: the label prefix could be declared in kubernetes.yaml (and default to `kube_` for backward compatibility).
