### ISSUE TITLE
send metrics to datadog

### ISSUE THREAD

**Issue by karampuri** [DataDog/dd-agent#3322]
Hi ,

I tried to send metrics to datadog using api.I did't get any error but can't show my metrics in datadog.
Please assist me .
ex:   api.Metric.send([{'metric':'my.series', 'points':15}, {'metric':'my1.series', 'points':16}])
I followed below link
http://docs.datadoghq.com/api/

**Comment by jeremy-lq** [comment]
karampuri, thanks for using Datadog. This issue queue is primarily intended for tracking features, bugs and work items associated with the dd-agent open source project. For your request, please contact our [support](http://docs.datadoghq.com/help/) and [send them your logs](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support).
