### ISSUE TITLE
datadog log parser

### ISSUE THREAD

**Issue by karampuri** [DataDog/dd-agent#3324]
Hi,

I tried to send metrics through log files to data-dog. But i unable to send and shown it in data-dog metrics summary list. I didn't get any error also.Please assist me.

I followed below link
http://docs.datadoghq.com/guides/logs/

**Comment by jeremy-lq** [comment]
karampuri, thanks for using Datadog. This issue queue is primarily intended for tracking features, bugs and work items associated with the dd-agent open source project. For your request, please contact our [support](http://docs.datadoghq.com/help/) and [send them your logs](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support).
