### ISSUE TITLE
Disabling APM Tracing instructions in the CHANGELOG appear to be incorrect

### ISSUE THREAD

**Issue by mlcooper** [DataDog/dd-agent#3325]
In this section of the CHANGELOG, https://github.com/DataDog/dd-agent/blob/master/CHANGELOG.md#details, it says to disable the APM tracing agent by putting `apm_enabled: no`, however the documentation everywhere else and the dd-trace-agent code looks like `apm_enabled` should have a boolean value after it.

**Comment by hush-hush** [comment]
Hi @mlcooper,

Actually both value are supported by the APM agent ("no" or "false") to disable it. I agree that the CHANGELOG and documentation should be align but both are correct (see here  https://github.com/DataDog/datadog-trace-agent/blob/master/config/agent.go#L246).

Thanks.
