### ISSUE TITLE
Support custom pod labels for kubernetes_state.* metrics

### ISSUE THREAD

**Issue by andreychernih** [DataDog/dd-agent#3347]
Right now I can not scope `kubernetes_state.deployment.replicas_available` metric by pod label. `kube-state-metrics` introduces pod labels in [0.5.0](https://github.com/kubernetes/kube-state-metrics/releases/tag/v0.5.0) which dd-agent can extract. They look like:

```
# HELP kube_pod_labels Kubernetes labels converted to Prometheus labels.
# TYPE kube_pod_labels gauge
kube_pod_labels{label_k8s_app="etcd-server",namespace="kube-system",pod="etcd-server-ip-10-51-44-183.us-west-2.compute.internal"} 1
kube_pod_labels{label_k8s_app="etcd-server-events",namespace="kube-system",pod="etcd-server-events-ip-10-51-44-183.us-west-2.compute.internal"} 1
kube_pod_labels{label_k8s_app="kube-apiserver",namespace="kube-system",pod="kube-apiserver-ip-10-51-44-183.us-west-2.compute.internal"} 1
kube_pod_labels{label_k8s_app="kube-controller-manager",namespace="kube-system",pod="kube-controller-manager-ip-10-51-44-183.us-west-2.compute.internal"} 1
kube_pod_labels{label_k8s_app="kube-scheduler",namespace="kube-system",pod="kube-scheduler-ip-10-51-44-183.us-west-2.compute.internal"} 1
```

**Comment by hkaj** [comment]
Hey @andreychernih 
thanks for the report! We're working on supporting 0.5 and all its new stuff in the next release of the agent, stay tuned ;)

**Comment by andreychernih** [comment]
Any news regarding this? Updated to `datadog/docker-dd-agent:12.4.5202` but still don't see labels coming.

**Comment by greg-jaunt** [comment]
I'm also looking for this.  Looks like the ticket was closed but not implemented?

**Comment by CharlyF** [comment]
@andreychernih, @greg-jaunt Sorry for the delay here.
We currently collect `kubernetes_state.deployment.replicas_available` as you can see in [the check](https://github.com/DataDog/integrations-core/blob/master/kubernetes_state/check.py#L56), but we do not support joining metadata from the kube-state output between metrics. 
Though this has been worked on in the past weeks and should be merged very soon
https://github.com/DataDog/dd-agent/pull/3632/files#diff-a8b772ecb4a190cb581a545b06a45c9aR42.
With such a feature, we will be able to work on joining the pod labels with the metrics of your choice.

Thank you very much for your patience.

**Comment by mikkoc** [comment]
We also need this. Has this been ever implemented @CharlyF ?
