### ISSUE TITLE
[core] capitalized 'Name' parameter doesn't match majority of examples

### ISSUE THREAD

**Issue by vanveele** [DataDog/dd-agent#3354]
When throwing an exception the log references the instance 'Name' parameter. Using the example config for http_check, I think this should be 'name' (lower case 'n').

https://github.com/DataDog/dd-agent/blob/master/checks/network_checks.py#L161

**Comment by hush-hush** [comment]
Hi @vanveele,

Thanks a lot for spotting the typo ! This will be fix in the next agent version (5.15).
The PR is here #3374.
