### ISSUE TITLE
Not all nodes are discovered in multi instance per server in ES cluster

### ISSUE THREAD

**Issue by dbuzolin-datto** [DataDog/dd-agent#3361]
I have very simple setup where on one physical node I run two ES 2.3.2 instances. Both are master/data nodes
```
node.host_name: test_es
node.master: true
node.data: true
```

But second node has:
```
http.enabled: "false"
```

From REST API I see correct status:
```
_cluster/health?pretty=true
{
  "cluster_name" : "test",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 112,
  "active_shards" : 218,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```
elastic.yaml points to first node http port:
```
- url: http://10.40.149.179:9200
```

However Datadog reports one node in the cluster in "Nodes by cluster status" and "Available nodes"

**Comment by hush-hush** [comment]
Hi @dbuzolin-datto , thanks for using Datadog.

This issue queue is primarily intended for tracking features, bugs and work items associated with the dd-agent open source project. For your request, please contact our [support](http://docs.datadoghq.com/help/) and send them your [logs](https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command).

Thanks and sorry for the delay.
