### ISSUE TITLE
Datadog agent fails to start on boot if docker not yet running

### ISSUE THREAD

**Issue by subuk** [DataDog/dd-agent#3367]
Hello,

We are using amazon linux with docker and datadog agent installed (from RPM package). The problem is when the instance starts, datadog agent starts before docker and immediately trying to connect to it and fails with 'Connection aborted' error in logs.

I see two ways to resolve this issue (both requires changes in this repository:
* Change chkconfig tag to '345  99 01', so datadog-agent will be the last service to start on boot and the first to stop on shutdown (seems reasonable for monitoring agent) https://github.com/DataDog/dd-agent/blob/master/packaging/centos/datadog-agent.init#L12
* Try to connect to docker multiple times before fail.

Or maybe I am doing something completely wrong and you know more easy way to resolve this issue (except installing datadog agent in docker container)?

**Additional environment details (Operating System, Cloud provider, etc):**

Provider: AWS
OS: Amazon Linux 2016.09.1.20170119 (ami-0b33d91d)

**Steps to reproduce the issue:**
1. Launch instance
2. Install docker and datadog-agent on it
3. Enable docker sd backend
4. Create AMI from that instance
5. Launch instance from just created AMI

**Describe the results you received:**

Datadog agent won't start with the following traceback in collector.log:
```
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/config.py", line 897, in _service_disco_configs
    sd_backend = get_sd_backend(agentConfig=agentConfig)
  File "/opt/datadog-agent/agent/utils/service_discovery/sd_backend.py", line 19, in get_sd_backend
    return SDDockerBackend(agentConfig)
  File "/opt/datadog-agent/agent/utils/singleton.py", line 11, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/opt/datadog-agent/agent/utils/service_discovery/sd_docker_backend.py", line 91, in __init__
    self.docker_client = self.dockerutil.client
  File "/opt/datadog-agent/agent/utils/dockerutil.py", line 232, in client
    return Client(**self.settings)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/docker/client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/docker/client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
```

**Comment by hush-hush** [comment]
Hi @subuk,

Thanks to raising the issue. I open a PR for the start/stop order.

For your question about retry:
we do: https://github.com/DataDog/integrations-core/blob/master/docker_daemon/check.py#L250-L252
it’s called in __init__ and then a couple more times in check:  https://github.com/DataDog/integrations-core/blob/master/docker_daemon/check.py#L258-L261

Feel free to comment back if you have more questions. Once the PR is reviewed we'll release it with the next version of the agent.

**Comment by subuk** [comment]
Thanks! I think your PR will resolve our issue.

**Comment by deppfx** [comment]
@hush-hush Can you post the PR or fix link for this issue?
