### ISSUE TITLE
Datadog 5.11.3 has broken SNMP integration on MacOS

### ISSUE THREAD

**Issue by mpalermo73** [DataDog/dd-agent#3380]
```
donut:site-packages root# /usr/local/bin/datadog-agent status
Datadog Agent (supervisor) is running all child processes
```

**Additional environment details (Operating System, Cloud provider, etc):**
```
donut:site-packages root# system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.4 (XXXXXX)
      Kernel Version: Darwin 16.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: donut
      User Name: System Administrator (root)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 70 days 4:02
```

**Steps to reproduce the issue:**
1. Install `dd-agent` `5.11.3` for Mac from here:
    `https://app.datadoghq.com/account/settings#agent/mac`
2. Configure `dd-agent` for `SNMP`:
```
  - ip_address: 192.168.2.1
    port: 161
    community_string: officefortigate
    snmp_version: 2
    timeout: 1
    retries: 3

    metrics:
      - MIB: IF-MIB
        table: ifTable
        symbols:
          - ifInOctets
          - ifOutOctets
        metric_tags:
          - tag: interface
            column: ifName
```
3. Run `dd-agent`:  ` /usr/local/bin/datadog-agent start`
4. Watch the log: `tail -F /private/var/log/datadog/collector.log `

```
2017-06-08 14:53:47 EDT | WARNING | dd.collector | checks.snmp(__init__.py:675) | Fail to collect some metrics: poll error: Traceback (most recent call last):
;  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pysnmp/carrier/asynsock/dispatch.py", line 37, in runDispatcher
    use_poll=True, map=self.__sockMap, count=1)
;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 110, in readwrite
    obj.handle_write_event()
;  File "/opt/datadog-agent/embedded/lib/python2.7/asyncore.py", line 468, in handle_write_event
    self.handle_write()
;  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pysnmp/carrier/asynsock/dgram/base.py", line 66, in handle_write
    self.socket.sendto(outgoingMessage, transportAddress)
;TypeError: getsockaddrarg() takes exactly 2 arguments (6 given)
```

**Describe the results you expected:**
No errors and values being reported

**Additional information you deem important (e.g. issue happens only occasionally):**

In reference to ticket #3181 I'm pasting this:

```
host:site-packages root# ls -ld /opt/datadog-agent/embedded/lib/python2.7/site-packages/pyasn1*
drwxr-xr-x  11 root  wheel  374 Jun  7 11:00 pyasn1
drwxr-xr-x   9 root  wheel  306 Feb 27 15:14 pyasn1-0.2.2.dist-info
```

It looks like either the Mac package of `dd-agent` version `5.11.x` wasn't fixed since the `pyasn1` version wasn't downgraded to `0.1.9` as said in #3181 ( #3183 ), or there's some new breakage somewhere else now.

M.

**Comment by olivielpeau** [comment]
Thanks @mpalermo73 for reporting this issue. The macOS build of the agent is not in a great state right now unfortunately, so I'm not sure exactly why the fix in `5.11.2` wasn't present in the `5.11.3` macOS-only release.

As a workaround, you can downgrade `pyasn1` on your agent installation by running:
```bash
sudo /opt/datadog-agent/embedded/bin/pip install pyasn1==0.1.9
```

Let me know if this fixes the issue, thanks!

**Comment by mpalermo73** [comment]
(Sorry for the delay...)

Yep.  Dropping the version of `pyasn1` to `0.1.9` does indeed stop the boom.  Thank you for the fast response, man!

M.

**Comment by olivielpeau** [comment]
Thanks @mpalermo73 for confirming that the workaround works!

I'm going to go ahead and close this issue then, the next version of the MacOS agent we release definitely won't have this issue
