### ISSUE TITLE
source installer fails on archlinux

### ISSUE THREAD

**Issue by clutchski** [DataDog/dd-agent#343]
`/usr/bin/python` points to python3, at minimum.

**Comment by remh** [comment]
Probably a won't fix at least for now.

**Comment by mide** [comment]
I don't mean to bump an old thread, but this is all that comes up when searching for [Arch Linux DataDog](https://www.google.com/search?q=arch+linux+datadog).

This might be a bit of a starting point for someone. It looks like everything runs normally once you get over the hump of the installation. I've currently got it working in interactive mode, and I'm not sure if the daemon setup went correctly... But like I said, this might be a good starting point.

```sh
wget https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh
sed s/python/python2/g setup_agent.sh > arch_datadog_setup.sh
DD_API_KEY=YOUR_GREAT_KEY bash arch_datadog_setup.sh
```

**Comment by cdown** [comment]
I have this working under systemd with a separate user, using the following:

```
useradd -m -r -d /opt/datadog-agent -k /dev/null -s /bin/bash dd-agent

wget https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh
sed 's/python/&2/g' setup_agent.sh > /tmp/arch_datadog_setup.sh
chmod a+xr /tmp/arch_datadog_setup.sh

sudo -iu dd-agent DD_HOME=/opt/datadog-agent DD_START_AGENT=0 DD_API_KEY=YOUR_API_KEY /tmp/arch_datadog_setup.sh

cat > /etc/systemd/system/datadog-agent.service << 'EOF'
[Unit]
Description=Datadog Agent
After=network.service
Requires=network.service

[Service]
Type=simple
User=dd-agent
ExecStart=/opt/datadog-agent/bin/agent
KillSignal=SIGINT
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl enable datadog-agent
systemctl start datadog-agent
```

**Comment by sflip** [comment]
For the same reason I want to point out: The script has been adjusted. The `python2` sed hack is not necessary anymore, if you have `python2` installed on your arch linux.
