### ISSUE TITLE
dd-agent taking a lot of CPU

### ISSUE THREAD

**Issue by duxing** [DataDog/dd-agent#3501]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **
Note: I restart the datadog-agent to stop it from taking a lot of CPU and these output are collected *after* the restart. It looks no different that what I've checked *before* restart.

```
2017-08-29 19:14:13,977 | WARNING | dd.collector | config(config.py:283) | Ignored histogram aggregate , invalid
===================
Collector (v 5.9.1)
===================

  Status date: 2017-08-29 19:13:55 (18s ago)
  Pid: 17743
  Platform: Linux-4.4.35-33.55.amzn1.x86_64-x86_64-with-redhat-6.5-Final
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======
  
    NTP offset: -0.0043 s
    System UTC time: 2017-08-29 19:14:14.108167
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    ec2-hostname: ip-10-196-210-245.usw2.zynga.com
    local-ipv4: 10.196.210.245
    local-hostname: ip-10-196-210-245.usw2.zynga.com
    socket-hostname: poker-web-consumer-149.usw2.zynga.com
    public-hostname: ec2-34-210-89-185.us-west-2.compute.amazonaws.com
    hostname: poker-web-consumer-149.usw2.zynga.com
    instance-id: i-0cf9e00e65e1e5a41
    public-ipv4: 34.210.89.185
    socket-fqdn: poker-web-consumer-149.usw2.zynga.com
  
  Checks
  ======
  
    fluentd
    -------
      - instance #0 [OK]
      - Collected 63 metrics, 0 events & 2 service checks
  
    postfix
    -------
      - instance #0 [OK]
      - Collected 3 metrics, 0 events & 1 service check
  
    apache
    ------
      - instance #0 [OK]
      - Collected 8 metrics, 0 events & 2 service checks
  
    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check
  
    disk
    ----
      - instance #0 [OK]
      - Collected 24 metrics, 0 events & 1 service check
  
    mcache
    ------
      - instance #0 [OK]
      - Collected 455 metrics, 0 events & 2 service checks
      - Dependencies:
          - memcache: 1.53
  
    network
    -------
      - instance #0 [OK]
      - Collected 27 metrics, 0 events & 1 service check
  
  
  Emitters
  ========
  
    - http_emitter [OK]

===================
Dogstatsd (v 5.9.1)
===================

  Status date: 2017-08-29 19:14:11 (3s ago)
  Pid: 17740
  Platform: Linux-4.4.35-33.55.amzn1.x86_64-x86_64-with-redhat-6.5-Final
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 255
  Packet Count: 112
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.9.1)
===================

  Status date: 2017-08-29 19:14:14 (0s ago)
  Pid: 17742
  Platform: Linux-4.4.35-33.55.amzn1.x86_64-x86_64-with-redhat-6.5-Final
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log, syslog:/dev/log

  Queue Size: 9591 bytes
  Queue Length: 1
  Flush Count: 858
  Transactions received: 381
  Transactions flushed: 380
  Transactions rejected: 0
```

**Additional environment details (Operating System, Cloud provider, etc):**
Cloud provider: AWS
Kernel release: 4.4.35-33.55.amzn1.x86_64
Support case id: 106557 (flare sent)

**Steps to reproduce the issue:**
1. Have dd-agent running and wait.
2. run this command and observe:
```
  ps aux | grep dd-agent | grep -v grep
```

**Describe the results you received:**
Missed the screenshot so I'll briefly describe what happened.
Usually I see 4 processors from dd-agent user(see "expected" for details)
But on this host I'm seeing 6. Other than the 4 listed below, there are 2 process executing the
same command "netstat -n -u -t -a".
And these 2 commands are taking 80% of CPU on avg.

**Describe the results you expected:**
```
dd-agent 17734  0.0  0.0 196808 14556 ?        Ss   18:31   0:00 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/bin/supervisord -c /etc/dd-agent/supervisor.conf
dd-agent 17740  0.1  0.0 192908 27232 ?        Sl   18:31   0:03 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/dogstatsd.py --use-local-forwarder
dd-agent 17742  0.1  0.0 142668 30100 ?        S    18:31   0:04 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/ddagent.py
dd-agent 17743  1.7  0.1 287820 44152 ?        S    18:31   0:49 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/agent.py foreground --use-local-forwarder
```

**Additional information you deem important (e.g. issue happens only occasionally):**
I've got hundreds of servers running datadog agent and this is the only one that had this issue. It does not happen all the time since I don't need to restart my datadog agent often.

I've looked at your source code and my guess is network.py started the process but did not clean that up properly. Can someone briefly describe to me when would datadog agent kick off netstat and why, and under what circumstance would it be left alone.

Much thanks in advance!

**Comment by gmmeyer** [comment]
Hey @duxing, thanks a lot for your report! Sorry I didn't see this sooner, it was a long holiday here in the United States.

I'm gonna ask you a few questions about your situation, but before anything else I want to ask you to open up a ticket with support. We're going to want a flare to debug and we'll want to properly track this issue to ensure it gets resolved.

Some questions for you to answer: has this happened more than once with this same server? How often does it happen? When it happens, can you run netstat? Does it hang for you? Can you kill those processes?

I do not know why netstat is hanging. When something like that happens, we do try to kill it. However, sometimes, very rarely, it won't die. Zombie processes are not fun. There may well be a bug in our subprocess code, but I think it's more likely that the agent has tried to kill them without success. 

I'll look into what can be done to make this better, in the meantime, one suggestion I do have is to upgrade your agent. Version 5.9.1 was released almost a year ago, and I know there have been some changes surrounding this code in the meantime.

FYI: the relevant code is here: https://github.com/DataDog/integrations-core/blob/8beed84d7a64ae67e61daafa118dd6ead78e22b2/network/check.py#L287

**Comment by duxing** [comment]
hi @gmmeyer 
glad to hear back from you.

so I've contacted support and had  a support case opened: 106557

flare has been sent to the support case as well, but I didn't do a good job highlighting this part of information in my first post.

To answer your questions:
 - for me it's a one-time issue so far. and I've got no idea how often this will happen. hopefully not a lot.
 - I didn't test running netstat but I guess it will run but it will hang.
 - When this happened, I did not test killing those process, but simply restarted datadog agent. by doing that, those processes are killed. so I think they can be killed. restarting process did not hang either.

As for your suggestion, support has told me the same information too, and I've upgraded my farm with latest datadog agent(5.17)

I've briefly look at your source code(network.py) and I think the issue is netstat not responding. It could be a transient issue on the OS level, but I can't find a way to verify.

**Comment by duxing** [comment]
hi @gmmeyer 

this same issue happened again on the same host *after* I upgraded to the latest version of dd-agent.(5.17.1 I think)

from htop:
![dd-agent-htop](https://user-images.githubusercontent.com/1322437/30567336-b397eaba-9c84-11e7-95a2-28ba47e1b8aa.png)

from `ps aux | grep dd-agent`
![dd-agent-netstat](https://user-images.githubusercontent.com/1322437/30567339-bc390992-9c84-11e7-884d-6c5c72b0a5d6.png)

flare has been sent again to id=106557

can you please take a look?

**Comment by gmmeyer** [comment]
Hey @duxing thanks for the update! We will have a look at this. 

This is bad behavior and the agent shouldn't do this, if we kill those before they can return the network check won't really return almost any metrics anymore. So, we have a bad tradeoff.

**Comment by duxing** [comment]
@gmmeyer more update on this issue:
 - it happened 3 times in the past 2 days
 - all 3 times it's on the same server

so I've spent some time looking at that server and tried running the netstat command. surprisingly I found out the jobs running on that server did not clean up connections, and the output of netstat command is >130K lines.

I figured that's probably the real issue so I fixed that on my application end.
Yet I'd like to point out, dd-agent should still take this kind of extreme case into consideration. From my perspective, the process was kicked off by dd-agent and was not properly shutdown. (I guess your script is waiting for an outcome for too long.)

and I'd suggest put a timeout for executing process.

**Comment by gmmeyer** [comment]
Hey @duxing! Yea, you're right, we should be more resilient. This is a bad failure. I need to look into how to ensure that this is better. However, at the same time, it's hard to say when a job should timeout. I'll look into adding this feature to the agent, though, I think that long running commands should be killed.

**Comment by adamthedeveloper** [comment]
Hey - I want to give a +1 on this. dd-agent runs away sometimes and causes outages on servers for us. Is there an update available?
info output:

```bash
$ sudo dd-agent info
2017-11-14 16:34:54,396 | ERROR | dd.collector | utils.dockerutil(dockerutil.py:138) | Failed to initialize the docker client. Docker-related features will fail. Will retry 0 time(s). Error: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
====================
Collector (v 5.18.1)
====================

  Status date: 2017-11-14 16:34:50 (3s ago)
  Pid: 5371
  Platform: Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
  Python Version: 2.7.14, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======
  
    NTP offset: 1.1434 s
    System UTC time: 2017-11-15 00:34:54.444171
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    socket-hostname: HIDDEN
    hostname: HIDDEN
    socket-fqdn: HIDDEN
  
  Checks
  ======
  
    ntp (5.18.1)
    ------------
      - Collected 0 metrics, 0 events & 0 service checks
  
    disk (5.18.1)
    -------------
      - instance #0 [OK]
      - Collected 36 metrics, 0 events & 0 service checks
  
    network (5.18.1)
    ----------------
      - instance #0 [OK]
      - Collected 25 metrics, 0 events & 0 service checks
  
  
  Emitters
  ========
  
    - http_emitter [OK]
```

**Comment by gmmeyer** [comment]
@adamthedeveloper can you make a ticket with support about this? We like to track these and it's easier to track through that than through gh issues. We'll ask you to send a flare with debug logging up to them--we'd like to see more data from you than we can get in a gh issue.

I  am curious if you're seeing exactly the same behavior that @duxing was seeing.

**Comment by duxing** [comment]
from the information attached I don't think it's a related issue. probably better to file a different issue with more details.

**Comment by gmmeyer** [comment]
Yea, that's my thought as well. Please file a ticket with our support, @adamthedeveloper. You can find them at support@datadoghq.com or you can message them directly through the app. We'll need to see a flare to properly debug this. 😄 

Thank you both again for helping us out by filing these issues!

**Comment by jairud** [comment]
Reporting the same here. process-agent consumes almost 40% CPU at any time.
Working with ubuntu 17.10 and datadog-agent 5.22.0-1

**Comment by gmmeyer** [comment]
@hegyre can you open a ticket? This is very unlikely to be the same issue.
