### ISSUE TITLE
Build ARM packages

### ISSUE THREAD

**Issue by ejholmes** [DataDog/dd-agent#3502]
I'd really love to be able to easily use the datadog-agent on some raspberry pi's. There's a guide in https://help.datadoghq.com/hc/en-us/articles/208163513-Deploying-the-Agent-on-RaspberryPI with information on building the datadog-agent from source, which works, but is incredibly slow compared to an `apt-get install datadog-agent` on an amd64.

Are there any plans to build arm packages? Any plans to re-build the datadog-agent with Go for 6.x? :)

**Comment by jeremy-lq** [comment]
@ejholmes As a Datadog on rPi user myself, this is something I'm also keeping an eye on. v6 is a fairly size-able rewrite of the agent and will include a change in language. Expect more news on this at Datadog Summit in September.

**Comment by janisz** [comment]
I'd love to get package to monitor my big ARM machines e.g. https://www.packet.net/bare-metal/servers/type-2a/

**Comment by masci** [comment]
@janisz we successfully cross compiled the new Agent https://github.com/DataDog/datadog-agent to ARM, this feature is going to be officially supported but it's still undocumented. If you feel comfortable running a beta, we'd love to get feedback - feel free to open an issue on the other repo.
As a side note, being really close to a GA version of the new Agent, we likely won't put efforts in a v5 ARM package.

**Comment by jeremy-lq** [comment]
Also, as an update for @ejholmes - the new agent is written in Go. The video from Summit detailing the new agent is available here: https://vimeo.com/album/4813750/video/237931772

I'm going to close this issue, but if you'd like to provide feedback or beta test the new agent, head to DataDog/datadog-agent and we're happy to help.
