### ISSUE TITLE
dd-agent forwarder keeps stopping on alpine:latest (until it gets to FATAL state after 3 retries)

### ISSUE THREAD

**Issue by zsoltkatona** [DataDog/dd-agent#3516]
Maybe I'm doing something wrong, but the forwarder always stops when installed in an alpine:latest docker image, whereas it start and doesn't stop in an ubuntu:latest image.

What works:
1. `docker run -t -i ubuntu /bin/bash`
2. then in the shell:
```
  apt-get update
  apt-get install -y python
  apt-get install -y sysstat
  apt-get install -y curl
  DD_HOME=/opt/datadog-agent DD_START_AGENT=0 DD_API_KEY=xxxx sh -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh)"
  cd /opt/datadog-agent
  bin/agent
```

What doesn't work:
1. `docker run -t -i alpine /bin/sh`
2. then in the shell:
```
  apk update
  apk add python
  apk add python-dev
  apk add py-pip
  apk add curl
  apk add tar
  apk add gcc
  apk add linux-headers
  apk add musl-dev
  apk add libffi-dev
  apk add libressl-dev
  apk add postgresql-dev
  apk add py-curl
DD_HOME=/opt/datadog-agent DD_START_AGENT=0 DD_API_KEY=xxxx sh -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh)"
  cd /opt/datadog-agent
  bin/agent
```

Note that there's no need for a number of libraries in the second case, I just wanted to get rid of the gcc compilation errors, but it looks like it doesn't have any significance, because under Ubuntu even with the compilation errors present in ddagent-install.log the forwarder starts and doesn't stop.

The problem I see in the forwarder.log file is:
`Socket error %s. Is another application listening on the same port ? Exiting`

I added a `time.sleep(60)` statement into the block that is executed like this:
```
try:
    # non_local_traffic must be == True to match, not just some non-false value
    if non_local_traffic is True:
        http_server.listen(self._port)
    else:
        # localhost in lieu of 127.0.0.1 to support IPv6
        try:
            http_server.listen(self._port, address=self._agentConfig['bind_host'])
        except gaierror:
            log.warning("localhost seems undefined in your host file, using 127.0.0.1 instead")
            http_server.listen(self._port, address="127.0.0.1")
        except socket_error as e:
            time.sleep(60)                                        # <------ here
            if "Errno 99" in str(e):
                log.warning("IPv6 doesn't seem to be fully supported. Falling back to IPv4")
                http_server.listen(self._port, address="127.0.0.1")
            else:
                raise
except socket_error as e:
    log.exception("Socket error %s. Is another application listening on the same port ? Exiting", e)
    sys.exit(1)
except Exception as e:
    log.exception("Uncaught exception. Forwarder is exiting.")
    sys.exit(1)
```
... and while the timer was ticking I checked the open ports with `netstat -tulpna` and indeed 17123 was already open in LISTEN state - as if `http_server.listen(self._port, address=self._agentConfig['bind_host'])` had succeeded but then had also raised a socket_error.

(I masked the API key with "xxxx".)

**Comment by xvello** [comment]
Hello @zsoltkatona ,

We do provide [ready-made docker images](https://hub.docker.com/r/datadog/docker-dd-agent/). The `latest-alpine` variant would be what you are looking for.


Regards

**Comment by zsoltkatona** [comment]
Hi @xvello ,

Thanks for your quick answer. I'm aware of these images, but my use case is different. I don't only need a running agent, but I'd like to install the agent into the same image where my nginx process runs in order to monitor it using checks.

Since this is a distributed environment, i.e. the number of the instances running nginx is dynamic, I cannot configure a dd-agent to monitor the instances started up. So this is why I'd like to install the dd-agent right into the image where my nginx runs.

This works properly in Ubuntu but not in Alpine.

Regards,
Zsolt

**Comment by xvello** [comment]
Hi @zsoltkatona ,

The [autodiscovery](https://docs.datadoghq.com/guides/autodiscovery/) feature looks to be what you are looking for. As it would be very time-consuming, we don't support custom docker images, but accept PRs / feature requests on [the official image](https://github.com/DataDog/docker-dd-agent) if needed.


Regards
