### ISSUE TITLE
Datadog Agent doesn't boot under systemd on restart

### ISSUE THREAD

**Issue by rcaught** [DataDog/dd-agent#3526]
Running Centos 7 with the `datadog/primary_db` yum source.
Using systemd.

**Steps to reproduce the issue:**
1.  Have `datadog-agent.x86_64 1:5.15.0-1` installed.  Will boot on restart.  Available in `systemctl status`.
2.  Upgrade to `datadog-agent-5.17.2-1.x86_64`.  Does not boot on restart.  Not in `systemctl status`.
3.  `systemctl start datadog-agent`.  Now available in `systemctl status` but will still not boot on restart.

**Comment by rcaught** [comment]
Likely related: https://github.com/DataDog/dd-agent/pull/3477#issuecomment-326334640

**Comment by rcaught** [comment]
Version `5.16` works fine.  Must be introduced with `5.17`.

**Comment by hush-hush** [comment]
Hi @rcaught,

Thank you for the issue, it's indeed a bug introduce in 5.17 as we moved to systemd on centos 7. We're going to publish a fix as soon as possible.

In the meanwhile a workaround is to manually enable the agent:
```
systemctl enable datadog-agent.service
```

**Comment by olivielpeau** [comment]
Fixed in https://github.com/DataDog/dd-agent-omnibus/pull/201, will be shipped in 5.18.0.

Thanks again @rcaught for reporting this issue!
