### ISSUE TITLE
Request datadog-agent able to rescan config files without restart

### ISSUE THREAD

**Issue by aalbertson** [DataDog/dd-agent#354]
Presently you have to restart the agent anytime you make modifications to anything in the /conf.d directory. Would like a way to either have the agent automatically check the configs, or at least an "update" command to send to the agent telling it to scan it's configs again.

**Comment by ssbarnea** [comment]
Can't we reopen this? Most services do allow for "service xxx reload" ... nginx, postgresql, ... This is an essential feature as we do get too many alerts for restarting the agent due to configuration change.

**Comment by remh** [comment]
I agree with this. It's not a priority for now but it should be fixed.
Reopening.

Thanks for the feedback @ssbarnea !

**Comment by remh** [comment]
This was actually implemented in #1983 and released in 5.6.0
