### ISSUE TITLE
Does kube integration support open file descriptors metric?

### ISSUE THREAD

**Issue by sokoow** [DataDog/dd-agent#3552]
Hi All,

https://docs.datadoghq.com/integrations/kubernetes/ doesn't mention open file descriptors metric for kube. Is there any way to enable/collect this metric?

**Comment by xvello** [comment]
Hi @sokoow ,

Unfortunately, neither `docker` nor `cadvisor` (kubernetes' performance monitoring system) tracks open FDs, so we don't have that information to extract.

From my research, the linux kernel only allows to set fd quotas per user/group, and not for a cgroup/process, so the kernel would need to evolve first. Do you have more information on that topic?

**Comment by sokoow** [comment]
Hey @xvello , thanks for replying, I'm afraid I've no other info on this topic :/ It's a nice to have but seem to require broad restructuring. So either we do the kernel hacking ourselves or wait for somebody to do it :D
