### ISSUE TITLE
No configtest command for osx agent

### ISSUE THREAD

**Issue by cbliard** [DataDog/dd-agent#3566]
When starting agent on osx, the following error message can be displayed:

https://github.com/DataDog/dd-agent/blob/0ba863249cd566fe9139e10e010d682c20ad21d5/packaging/osx/datadog-agent#L65-L69

But there is no `configtest` command available.

```
sudo datadog-agent configtest
Password:
Usage: /usr/local/bin/datadog-agent {start|stop|restart|info|status|reload|configcheck|check|flare|jmx}
```

I saw that the `configtest` command is available in other environments though, like Debian:

https://github.com/DataDog/dd-agent/blob/1d44b6294655ea2ff82cae58c3f4439d0c705b9a/packaging/debian/datadog-agent.init#L230-L233

**Comment by gmmeyer** [comment]
@cbliard, we don't use init to manage the agent on OSX, so the init commands aren't available on OSX. The configtest command is available from the agent as the `configcheck` command.

**Comment by gmmeyer** [comment]
@cbliard we don't use init to manage the agent on OSX, so you cannot interface with the agent through those commands. You can only use the commands in the agent itself. The command in the agent itself is called `configcheck`. We could make a small change to allow people to use `configtest` as well, but they would do the same thing. You can see that it works here:

```
$ sudo datadog-agent configcheck
All yaml files passed. You can now run the Datadog agent.
```

**Comment by cbliard** [comment]
Sure, I understand. I was trying to find why the agent would not start, so I was reading the script, running some commands to find why it would not start and I stumbled upon this. If it is intended, we can close this issue.

Thanks

**Comment by gmmeyer** [comment]
It's a good spot and I can submit a fix for it, it does in fact appear to be a bug.
