### ISSUE TITLE
Support TLS client certificates for prometheus check

### ISSUE THREAD

**Issue by discordianfish** [DataDog/dd-agent#3639]
Hi,

I've created https://github.com/latency-at/datadog-agent-prometheus to scape Prometheus metrics with datadog by using the PrometheusCheck: https://github.com/latency-at/datadog-agent-prometheus/blob/master/check.d/prometheus.py#L32

Now I want to scrape endpoint that requires TLS client authentication (a secure etcd-member) but that doesn't seem to be possible with the PrometheusCheck.

**Comment by hkaj** [comment]
Hi @discordianfish thanks for reaching out. We heard good things from your project here!
@mfpierre will TLS client cert be supported in the new prom check?

**Comment by mfpierre** [comment]
Hi @discordianfish just opened a PR to add the support of custom settings for SSL in the prometheus check.

I'm also working on something similar to https://github.com/latency-at/datadog-agent-prometheus that will be soon integrated in the core integrations, I'll add the support of the SSL in the yaml settings
