### ISSUE TITLE
Kubernetes 1.9 breaks pod owner lookup

### ISSUE THREAD

**Issue by andor44** [DataDog/dd-agent#3642]
The code [here](https://github.com/DataDog/dd-agent/blob/774a58204238b8029b075fa937eb43ed3ab77897/utils/kubernetes/kubeutil.py#L649-L663) to find the pod's creator no longer works because in https://github.com/kubernetes/kubernetes/pull/54445 they removed the pod annotation that the agent code is looking for. They advise on using the stabilized `metadata.ownerReferences` field instead. The above patch is in 1.9, therefore any pods created by k8s 1.9 and later will be missing owner tags on metrics (e.g. `kube_deployment`, `kube_daemonset`, etc.)

**Comment by CharlyF** [comment]
Hey @andor44, it does seem like it indeed - Thank you very much for bringing this up to our attention!

I have added a task in our backlog so we can further investigate.
While we'll do our best to solve this as soon as possible, should you want to be updated on the progress made, feel free to reach out to our support team (support@datadoghq.com) with a reference to this issue so we can best communicate on our efforts.

Cheers,
.C
