### ISSUE TITLE
Failed to retrieve Kubernetes deployments

### ISSUE THREAD

**Issue by Boojs** [DataDog/dd-agent#3654]
Hi,

I have the dd-agent daemonset running and working as needed thus far. A few days back I have enabled the process agent, ie DD_PROCESS_AGENT_ENABLED= true

I am noticing a lot of warnings and debug entries in the process agent log.

DEBUG (cgroup.go:567) - could not parse container id from path '10:pids:/'
WARN (kubernetes.go:60) - Failed to retrieve Kubernetes deployments: decode error status: payload is not a kubernetes protobuf object

I will continue to investigate on my end, but if anyone has any ideas or thoughts, would be greatly appreciated. I have a feeling this is due to some missing RBAC permissions, but not sure which ones

**Comment by antoinepouille** [comment]
Hi @Boojs 

Indeed, this is unexpected. So that we can investigate this, could you please [open a new support case](https://www.datadoghq.com/support/) where we will be able to assist you.
It will allow us to safely exchange your logs and configs through a flare.

Thank you

**Comment by Boojs** [comment]
Thanks @antoinepouille 

I have done so and working with your support team

**Comment by sylr** [comment]
@Boojs Any update on this subject, I've the same problem.

**Comment by Boojs** [comment]
@sylr 

This was the update provided from datadog support:

> apparently version 5.22.0 of our agent (the newest version) includes a number of fixes to how we fetch tags from Kubernetes. Would it be possible for you to give this new version a try to see if it fixes this issue?

Also, ensure you have the necessary RBAC permissions: https://gist.github.com/hkaj/404385619e5908f16ea3134218648237

**Comment by sylr** [comment]
It was indeed a RBAC permission issue.

If not allowed the endpoint returns a plain text error when then client expects a protobuf response hence the decoding error.
