### ISSUE TITLE
dd-agent fails to install on alpine 3.7

### ISSUE THREAD

**Issue by sravankasu** [DataDog/dd-agent#3682]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
N/A 
```

**Additional environment details (Operating System, Cloud provider, etc):**
OS: Alpine Linux 3.7 running inside a Docker container
dd-agent version: 5.22.0

**Steps to reproduce the issue:**
1. curl https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh > /tmp/setup_agent.sh
2. sh /tmp/setup_agent.sh

**Describe the results you received:**
The following error:
```
Command "/opt/datadog-agent/venv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-ggTuLv/psycopg2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-46oUJS-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/datadog-agent/venv/include/site/python2.7/psycopg2" failed with error code 1 in /tmp/pip-build-ggTuLv/psycopg2
```

**Describe the results you expected:**
Successful installation of dd-agent

**Additional information you deem important (e.g. issue happens only occasionally):**
I have the following packages installed on the OS:

```
python2=2.7.14-r2
sysstat=11.6.0-r0
ca-certificates=20171114-r0
curl=7.58.0-r0
gcc=6.4.0-r5
linux-headers=4.4.6-r2
musl-dev=1.1.18-r3
pgcluster-dev=1.9.0_rc5-r10
python2-dev=2.7.14-r2
tar=1.29-r1
```

**Comment by xvello** [comment]
@hush-hush is that fixed by your recent changes?

**Comment by hush-hush** [comment]
Yes, you will have to install the agent without any integrations on alpine (or install every dependencies needed by each integrations, but I think that would defeat the purpose of the alpine image).

```
DD_SKIP_INTEGRATIONS=1 sh /tmp/setup_agent.sh
```

**Comment by sravankasu** [comment]
Thanks, we've implemented this in our install script.
