### ISSUE TITLE
apt-key C7A7DA52 expired on 2018-03-04

### ISSUE THREAD

**Issue by nehalrp** [DataDog/dd-agent#3692]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
service datadog-agent status
Datadog Agent (supervisor) is running all child processes

```

**Additional environment details (Operating System, Cloud provider, etc):**

```
uname -a
Linux staging-us1-ecs-uswest2-i-0249b2f12 4.4.0-111-generic #134~14.04.1-Ubuntu SMP Mon Jan 15 15:39:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps to reproduce the issue:**
```
apt-key list | grep C7A7DA52
pub   2048R/C7A7DA52 2011-03-16 [expired: 2018-03-04]
```

**Describe the results you received:**
Expired apt-key. Breaking our configuration management builds.

**Describe the results you expected:**
We expected the key to be renewed, or a new valid one to be provided on the repo.

**Additional information you deem important (e.g. issue happens only occasionally):**
NA

**Comment by olivielpeau** [comment]
Hi @nehalrp! Sorry this broke your config management builds.

We've rotated the key of our APT repo last week (see mention of it, and details, in our changelog: https://github.com/DataDog/dd-agent/blob/master/CHANGELOG.md#5220--02-13-2018). Our official installation methods/config management plugins have been updated to use the new key.

Please refer to our updated step-by-step instructions for your platform (https://app.datadoghq.com/account/settings#agent/ubuntu) for the ID of the new key.

I'm going to go ahead and close this issue, but feel free to comment on it or re-open if anything's unclear.
