### ISSUE TITLE
Add connection count to base OS checks.

### ISSUE THREAD

**Issue by drohr** [DataDog/dd-agent#379]
Would be nice if dd-agent also got the amount of connections and added it to its "base" of stats to check, like disk space and memory today. Either something from netstat or fetch the data from proc. Maybe group on type, TCP/UDP and such.

``` bash
$ cat /proc/net/sockstat
sockets: used 786
TCP: inuse 702 orphan 0 tw 4346 alloc 703 mem 382
UDP: inuse 22 mem 2
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```

**Comment by mfractal** [comment]
any chance to add this functionality in windows @LotharSee ?

**Comment by vladimir-i** [comment]
Note that this issue requests the number of TCP connections but it was closed after the number of packets sent/received was added. Could the number of connections be added, please?

**Comment by jpza** [comment]
Bump

**Comment by slmingol** [comment]
This should be reopened, it doesn't address the original ask. The ask was for individual tallys for specific ports, not just the aggregations of all ports in the given states.
