### ISSUE TITLE
ImportError: No module named checks

### ISSUE THREAD

**Issue by grosser** [DataDog/dd-agent#3864]
on 6.15.0 this started happening :/

```
    dnsmasq
    -------
      Core Check Loader:
        Check dnsmasq not found in Catalog

      JMX Check Loader:
        check is not a jmx check, or unable to determine if it's so

      Python Check Loader:
        unable to import module 'dnsmasq': Traceback (most recent call last):
  File "/etc/datadog-agent/checks.d/dnsmasq.py", line 3, in <module>
    from checks import AgentCheck
ImportError: No module named checks
```

```python
from checks import AgentCheck
```

same here:
- https://www.gitmemory.com/issue/jwestbrook/datadog-asteriskpbx/18/536599083
- https://pastebin.com/XC0VTAT6

**Comment by grosser** [comment]
`from datadog_checks.checks` as per [check docs](https://docs.datadoghq.com/developers/write_agent_check/?tab=agentv6#custom-agent-check)

**Comment by KSerrania** [comment]
Hi @grosser,

Thanks for reporting this, we removed the legacy import by mistake and will reintroduce it in the next bugfix release of the Agent (6.15.1).

As you found, using `from datadog_checks.checks import AgentCheck` is now the preferred import path (on Agent `6.0.0` and later).

**Comment by kefayati** [comment]
I am on dd agent `7.22.0` on mac os and get the same error. Isn't it fixed?!
