### ISSUE TITLE
Datadog agent installation issue

### ISSUE THREAD

**Issue by rgooneratne** [DataDog/dd-agent#3904]
I tried to use the latest datadog installer on a Windows machine and it's rolling back. Please advice.

**Comment by olivielpeau** [comment]
Hi @rgooneratne, for your issue please [open a support case with our support team](https://www.datadoghq.com/support/) and attach your [Agent's MSI installer logs](https://docs.datadoghq.com/agent/guide/agent-log-files/?tab=agentv6v7#agent-installation-log-files) to your support case.

I'll go ahead and close this issue, but please comment here if you have any problem with these steps.

**Comment by rgooneratne** [comment]
Hello Team,

Please help I’m struggle with this issue more than 2 days. Someone close my ticket without help.

CC: Hello Skylar,

Regards,

Ruwan Gooneratne | Systems Engineer | Crane Merchandising Systems
Email: rgooneratne@cranems.com<mailto:rgooneratne@cranems.com> | Office: +1 803-266-8473|| Website:  www.cranems.com<http://www.cranems.com/>

[CPI_eSignature_CraneMerchandisingMerger]
