### ISSUE TITLE
Unable to disable dd-agent startup without disabling supervisor

### ISSUE THREAD

**Issue by conorbranagan** [DataDog/dd-agent#437]
If you want to to disable the agent from starting you'd expect to be able to do:

`update-rc.d datadog-agent disable`
or
`update-rc.d -f datadog-agent remove`

But even after running both and removing all links to the init.d script in /etc/rc*.d, the agent still starts because it's getting started when supervisor starts. The only way to completely disable the agent start (without removing the package) is to disable supervisor altogether.

`update-rc.d supervisor disable`

This is definitely not ideal when someone is using supervisor for something other than the agent.

**Comment by ruchit-cognicept** [comment]
I know it is older and closed issue. But how can I do this now? Not able to find anything to disable datadog agent from starting up with system boot.

**Comment by elijahandrews** [comment]
@ruchit-cognicept Hello! Which operating system are you running? Assuming you're running Linux and installed the agent through a package, you should be able to use your system's init manager to stop the agent from starting up.
