### ISSUE TITLE
info command requires elevated privileges

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#482]
Any non-root user will be asked to authenticate for `info`.

ref: https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent-base-deb/datadog-agent.init#L76-L81

However, removing the su commands from the init surfaces errors like:

    Log file is unwritable: '/var/log/datadog/forwarder.log'

So I'm guessing there's a test that is being done in the context of the $AGENTUSER

Basically, you shouldn't need elevated privileges to see the info page, unless details on the info page are restricted (which there probably shouldn't be anyways).

**Comment by remh** [comment]
This is a won't fix. The info page also requires to read datadog.conf that is not readable by anyone.
