### ISSUE TITLE
When aggregating a statsd counter, should we use a Long instead of an Int?

### ISSUE THREAD

**Issue by alq666** [DataDog/dd-agent#534]
https://github.com/DataDog/dd-agent/blob/master/aggregator.py#L294 casts the value as an int or as a float, which means that large numbers (e.g. 64-bit integers) cannot be represented properly and will yield a rate of 0 as the absolute number overflows the mantissa.

Should we cast the value to a long when the type is a `class Counter`?

**Comment by remh** [comment]
This hasn't been an issue so far. Closing.
