### ISSUE TITLE
Ignore more non-real filesystems

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#537]
Similar to "none" on https://github.com/DataDog/dd-agent/blob/master/checks/system/unix.py#L61-L63
add "devfs" and "procfs".

These are not devices and will report like so (sanitized data):

```
# df -k
Filesystem                                 1024-blocks       Used      Avail Capacity  Mounted on
devfs                                                1          1          0   100%    /dev
/dev/sometemp                                  1012974         26     931912     0%    /tmp
procfs                                               4          4          0   100%    /proc
```

These devices reporting 100% use and 0 things free (bytes, inodes, etc) will prevent setting useful alerts on the other filesystem-related stats.

**Comment by notjoe** [comment]
Not sure why this is closed as it is a legitimate request.

**Comment by domenkozar** [comment]
Yes, these should be excluded by default (macOS).
