### ISSUE TITLE
Allow to exclude filesystems from metrics reporting

### ISSUE THREAD

**Issue by LotharSee** [DataDog/dd-agent#568]
Related to #537 but more generic.
We should be able to skip reporting metrics on certain disks (they can be not interesting because they are virtual, the disk of a guest VM, the swap ...). The main reason is that it avoid the user to filter them out on dashboards.

We can use a shared syntax with the network check which already allow to exclude network interface.
We can start with a list, but the support for pattern would be great too.

**Comment by notjoe** [comment]
I am getting false alerts on tmpfs, which is not a real file system.

**Comment by remh** [comment]
Thanks for the update @notjoe . Reopening this issue.

**Comment by QuirkyMarc** [comment]
Excluding filesystems by type is needed to.

For instance, I have 100+ servers mounting the same NFS filesystem, I don't need to be alerted by the NFS server, and all 100+ clients, alerting about that same filesystem.

**Comment by LeoCavaille** [comment]
It would be cool also to have an option to tag by filesystem type (that is interesting to filter out stuff also on graphs).
Nonetheless, it should be featured flagged off by default because it will recreate too many contexts otherwise.
