### ISSUE TITLE
network connection state should be tracked with tags instead of metrics

### ISSUE THREAD

**Issue by clutchski** [DataDog/dd-agent#593]
Our connection tracking uses a lot of different metrics. This is a bit of a pain to create dashboards. Instead of the following metrics:
 
```
system.net.udp6.connections
system.net.tcp4.established
system.net.tcp4.opening
system.net.tcp4.closing
system.net.tcp4.listening
system.net.tcp4.time_wait
system.net.tcp6.established
system.net.tcp6.opening
system.net.tcp6.closing
system.net.tcp6.listening
system.net.tcp6.time_wait
```

Does it make sense to have a single metric with tags, like so:

```
system.net.connections{protocol:tcp,state:opening}
```

This would be a relatively simple change. We could deprecate the old metrics, and alert any customers graphing/alerting on the above metrics.

**Comment by remh** [comment]
This is a won't fix. We won't rename these metrics as it would break backward compatibility and we didn't have more requests for that.
