### ISSUE TITLE
Add ability to track stats directly from gunicorn web server

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#609]
There's no direct 100% way to go about it, but here's couple of ideas that might work:

- https://gist.github.com/m0n5t3r/661377
- https://github.com/m0n5t3r/gstats

**Comment by remh** [comment]
gunicorn supports metrics sending through statsd: http://docs.gunicorn.org/en/19.4.5/instrumentation.html
This seems to be the right way to do it.
Closing this issue.
