### ISSUE TITLE
Jenkins integration failing after upgrading agent to 3.9.0

### ISSUE THREAD

**Issue by adamjt** [DataDog/dd-agent#614]
At the end of a job, this appears in the syslog:

Aug 13 14:00:06 c-jenkins04 dd.collector[15139]: ERROR (__init__.py:454): Check 'jenkins' instance #0 failed#012Traceback (most recent call last):#012  File "/usr/share/datadog/agent/checks/__init__.py", line 445, in run#012    self.check(instance)#012  File "/usr/share/datadog/agent/checks.d/jenkins.py", line 141, in check#012    if output['result'] == 'SUCCESS':#012KeyError: 'result'

**Comment by remh** [comment]
We now have a jenkins plugin to directly push events to datadog
https://github.com/DataDog/jenkins-datadog-plugin
