### ISSUE TITLE
Nagios performance perf data does not work with pnp4nagios

### ISSUE THREAD

**Issue by conorbranagan** [DataDog/dd-agent#686]
pnp4nagios will rewrite the performance data file after every read which breaks our log file "tail" which assumes this data file will constantly be growing.

We could change how the log parsing works so that it can optionally read the entire file on every check instead of tailing, but then we'd have to be able to de-dupe from the last run.

**Comment by jkoppe** [comment]
I think I'm ready to stop using pnp4nagios entirely. How do y'all have nagios setup so this works without pnp4nagios?  I'm mainly interested in how you delete the host_perfdata_file and service_perfdata_file when they're done being processed in a way which doesn't lose data.

**Comment by jkoppe** [comment]
Thoughts?

**Comment by alq666** [comment]
Hi @jkoppe, sorry for the delay. I'll speak under the authority of @LeoCavaille and @remh who may contradict me, but our Nagios integration relies on an ever-growing file (or more likely, one under rotation on a periodical basis).

The Nagios check relies on https://github.com/DataDog/dd-agent/blob/master/checks/utils.py#L31, which expects the file to grow with occasional resets (it checks the first 16 bytes of the file and the inode for changes).

So it should actually work nicely.

**Comment by alq666** [comment]
Hi @jkoppe, I don't know if the nagios log following worked according to what I described earlier.

**Comment by remh** [comment]
Going to close this issue as we didn't get more questions about it. Will reopen if it gets more traction.

**Comment by jkoppe** [comment]
I wish datadog recommended some solution to have nagios send all perfdata to datadog.
