### ISSUE TITLE
dd-agent fails to get gunicorn process on linux

### ISSUE THREAD

**Issue by nxvl** [DataDog/dd-agent#706]
dd-agent try to gets unicorn master process by name using this line [1]:

``` python
   return  "gunicorn: master [%s]" % name
```

However, psutil trims the process name removing spaces, in this line [2]:

``` python
  name = f.read().split(' ')[1].replace('(', '').replace(')', '')
```

which return "gunicorn:" as process name, generating the following error:
- instance #0 [ERROR]: GUnicornCheckError('Found no master process with name: gunicorn: master [PROCESS_NAME]',)
1. https://github.com/DataDog/dd-agent/blob/master/checks.d/gunicorn.py#L129
2. https://code.google.com/p/psutil/source/browse/psutil/_pslinux.py#472

**Comment by ava-dylang** [comment]
For the posteriors,

I was having trouble getting these to work and realized I didn't have the necessary `setproctitle` pip package installed in the gunicorn env.

**Comment by ramtinms** [comment]
`sudo /usr/local/bin/pip install psutil` solved my problem
