### ISSUE TITLE
detect AZ for AWS integration

### ISSUE THREAD

**Issue by MisterRayCo** [DataDog/dd-agent#715]
Pick up availability zone tags quickly so as to prevent this occurring in legends:

![screen shot 2013-11-01 at 5 23 52 pm](https://f.cloud.github.com/assets/1970694/1457253/fc6ceab6-433b-11e3-823c-274f2724da29.png)

Should be done here:
https://github.com/DataDog/dd-agent/blob/191df7eefab77832f7092041e7722c6109605e80/util.py#L226

**Comment by remh** [comment]
Closing as it doesn't seem to be an issue anymore.
