### ISSUE TITLE
Agent should collect system swap metrics

### ISSUE THREAD

**Issue by sethrosenblum** [DataDog/dd-agent#716]
When doing system checks with the agent, we don't look at /proc/vmstat, so we don't get metrics like "swapped in" and "swapped out".  We should add this to our unix system checks.

**Comment by dtorgy** [comment]
We would love to see this implemented. We are investigating switching from a very large graphite + dashboard implmentation to datadog for monitoring and alerting. This is one of the pain points in switching.

+1

**Comment by remh** [comment]
Thanks for the feedback @dtorgy .
Changing the milestone to 5.3.0 to figure out what we can do.
