### ISSUE TITLE
[redis] check should poll the slowlog periodically and produce some metrics

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#717]
It would beneficial to be able to correlate how frequently slow queries are happening, and how long they are taking, so an operator could then inspect the log for debug information.

Should be relatively easy to implement, as the functionality has been in redis since 2.2.12 (3 years ago).

Refs: http://redis.io/commands/slowlog
Good article further explaining slowlog: http://garantiadata.com/blog/enhancing-redis-slow-log

**Comment by suprememoocow** [comment]
This would be great. It's a very good performance metric for Redis :+1:

**Comment by miketheman** [comment]
Thinking about this again, and I think the values to pull would be:

> - <strike>A unique progressive identifier for every slow log entry.</strike>
- The unix timestamp at which the logged command was processed.
- The amount of time needed for its execution, in microseconds.
- The array composing the arguments of the command.

A sample from `SLOWLOG GET 1`:

```console
1) 1) (integer) 504
   2) (integer) 1422536239
   3) (integer) 12629
   4) 1) "LPUSH"
      2) "somekey"
      3) "somevalue (35959 more bytes)"
```

We would pick 2 (timestamp), 3 (slow duration in microseconds as the metric value) and 4.1 (command as a tag).

This should then provide the ability to graph out slow log entries and slice by operation to help find slowness.

**Comment by suprememoocow** [comment]
In the mean time, I'm using Fluent and the [fluentd-plugin-redis-slowlog](https://github.com/suprememoocow/fluent-plugin-redis-slowlog) (my own fork) and then forwarding the results to datadog via the Fluent statsd client, so I can get Redis slowlog charts in Datadog, like so

![Slowlog](http://cl.ly/image/1K1I0m2w0t0y/Image%202015-01-29%20at%202.18.57%20pm.png)

**Comment by miketheman** [comment]
That's nifty - thanks for sharing! I might use some of those ideas as well.

**Comment by suprememoocow** [comment]
WFIF, I'm also doing the same thing for MongoDB with a fork of the [fluent-plugin-mongo-slow-query]( https://github.com/suprememoocow/fluent-plugin-mongo-slow-query) plugin.

**Comment by remh** [comment]
Fixed by https://github.com/DataDog/dd-agent/pull/1400
