### ISSUE TITLE
Get OOM kills as events

### ISSUE THREAD

**Issue by clofresh** [DataDog/dd-agent#720]
A little tricky because we'd need to parse the kernel log, which requires a privileged user

**Comment by williammpratt** [comment]
In this thread we explain how we are scared of the word kernel.

**Comment by remh** [comment]
You can now tail your whole kernel log and send them to datadog through our log processing features:
https://www.datadoghq.com/blog/announcing-logs/'

You can then track and alert on OOM kills.

Closing this.
