### ISSUE TITLE
Support * globs in dogstream file configuration

### ISSUE THREAD

**Issue by clofresh** [DataDog/dd-agent#753]
So that this will do the Right Thing(tm):

dogstreams: /var/log/mydir/*.log

**Comment by gtaylor** [comment]
Bigtime! Trying to write some Ansible playbooks now, but the requirement that this directive only appear once is complicating things. Various roles require different dogstreams.

**Comment by gtaylor** [comment]
Pull request plus tests sent!

**Comment by gtaylor** [comment]
Took this to an even higher level in #1557 with a dogstreams.d feature (similar to conf.d and checks.d). You can drop YAML files in *and* wildcarding is supported.

**Comment by Joeasaurus** [comment]
+1000 I was just about to start work on making the dogstreams config support much better, but this guy has nailed it. Props to you @gtaylor

**Comment by gtaylor** [comment]
@Joeasaurus It's a bit disappointing not to hear a peep from the Datadog maintainers, since this is IMO a glaring omission. I'm not sure whether to even waste the time rebasing this given the lack of response.

**Comment by Joeasaurus** [comment]
I for one would be most grateful.

**Comment by gtaylor** [comment]
Yeah, I just don't want to waste any more time on it if they aren't going to accept it. Feel free to encourage them to take a look at this if it's causing you pain in your usage case.

**Comment by R4wizard** [comment]
+1

**Comment by LeoCavaille** [comment]
@gtaylor thanks again for this new feature, sorry that we didn't have time to review it sooner. Let's get to it and review that for 5.4. If we need to put more work on it, we can help you do that.

**Comment by Joeasaurus** [comment]
@yannmh It seems to me as though you lost my fix to use dogstreams.d exclusively?

https://github.com/Aclima/dd-agent/pull/1/files

**Comment by yannmh** [comment]
Hi @Joeasaurus,

Your fix is still on his way (https://github.com/DataDog/dd-agent/pull/1557) and should be reviewed shortly. Thanks again for your contribution :smiley:

This specific issue was solved with https://github.com/DataDog/dd-agent/pull/1550

**Comment by Joeasaurus** [comment]
Aaaah no worries, thanks :D
