### ISSUE TITLE
Debugging dogstreams is very tough

### ISSUE THREAD

**Issue by conorbranagan** [DataDog/dd-agent#795]
In our dogstream parsing we have quite a bit of error handling, some which actually logs out and others that doesn't. When you're creating a new dogstream it's hard to determine where things are going wrong.

An example of this case is [here](https://github.com/DataDog/dd-agent/blob/master/checks/datadog.py#L205) where we skip an event because it doesn't have a title but we don't put anything in the logs. Another example is [here](https://github.com/DataDog/dd-agent/blob/master/checks/datadog.py#L252) where we're only logging to debug when there's a parsing error.

We  should consider having something that tests a parser or adding something to the info page for dogstreams

**Comment by remh** [comment]
\We are currently evaluating new options to replace dogstream and we likely won't add new features to the current implementation unfortunately, so i'm going to close this issue.
