### ISSUE TITLE
check_freq is set to 15 seconds in more than one place

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#796]
Not really a bug, just clutter in the code.
https://github.com/DataDog/dd-agent/blob/7d6b6619b4d3b2a7f4efca81686c3670ca95cc53/config.py#L26
https://github.com/DataDog/dd-agent/blob/31a7cdbbb0add750cca32caf360b5ec02ad6b684/checks/datadog.py#L153

There's a lot of other places that use the `int(agentConfig.get('check_freq')` approach - it seems likely that agentConfig should ensure the return value is an `int` as well.

**Comment by remh** [comment]
We won't fix this, we'll work on a new scheduler instead.
