### ISSUE TITLE
[dogstasd] dogstatsd_normalize value and dogstatsd_interval are never picked up from config

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#805]
Unsure if this is a conscious choice or not.

Ref:
https://github.com/DataDog/dd-agent/blob/f122e1c0302ef3955a78a95330c13c5144278dfb/config.py#L318-L338
Also set here: https://github.com/DataDog/dd-agent/blob/f122e1c0302ef3955a78a95330c13c5144278dfb/config.py#L194

However, setting the conf directive to `no` or `false` will have no impact, since at no point to re read this value from the `agentConfig object.

This was added in #252 with a default value of "no".

Another commit referencing the conf change: daaa448416d55a0f97ccbaf660c6b542710038a0

@clutchski, @alq666 - do you recall this case, and what we need to do about this?

**Comment by remh** [comment]
Removing the options from the config files for now until we decide to properly implement it or not.

**Comment by remh** [comment]
https://github.com/DataDog/dd-agent/commit/adc1b59a10eb79acd8598162aa479616c39f68b7
