### ISSUE TITLE
pgbouncer check

### ISSUE THREAD

**Issue by clofresh** [DataDog/dd-agent#843]
Would be nice to have, they expose some good metrics: http://pgbouncer.projects.pgfoundry.org/doc/usage.html#_show_stats

**Comment by remh** [comment]
Should be fixed by https://github.com/DataDog/dd-agent/pull/1148

It should be part of our 5.2.0 release

**Comment by remh** [comment]
Will actually be released with 5.3

**Comment by remh** [comment]
Fixed with https://github.com/DataDog/dd-agent/pull/1391
