### ISSUE TITLE
Get metrics regarding opened file handlers

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#853]
Another common problem with systems is the number of opened files.
Data dog should provide metrics regarding their use and more important to present one metric that measure % use, allowing us to add alerts if usage is above, let's say 80%. 

The numeric value is not a big use by itself, but when measured agains the maximum value, which is configurable its value grows considerably.

http://www.cyberciti.biz/tips/linux-procfs-file-descriptors.html

**Comment by ssbarnea** [comment]
Please do try to install psutils when installing agent, otherwise you are just providing a bad user experience. It is ok to ignore if it fails but doing an `apt-get install psutils` would be a great UX improvement.

**Comment by remh** [comment]
Thanks for the feedback @ssbarnea 

As of Agent 5.0.0, psutil is bundled in the deb, rpm and msi packages of the agent, and is installed on the fly with source installs.

```bash
$ /opt/datadog-agent/embedded/bin/python -c "import psutil; print psutil.__version__"
2.2.1
```

We will work on this issue to implement the count of opened file handlers, as it's an important metric but feel free to open a pull request if you've already done so!

Thanks again for the feedback!

**Comment by ssbarnea** [comment]
I am quite busy fixing other broken things around but be sure that if I implement something in datadog I will make pull requests. I prefer not to run my owned patched versions.

I had an outage due to file handlers being ousted for one of the monitored processes (nginx) and it took me some time to find out the cause. 

So if Data dog can monitor the % of file handlers it would be perfect as we can have a single rule: if % open files (curr/max) is over 90% raise alarm.

I do like being able to have relative conditions as it is much easier to manage them and also you do not have to update the monitors when you tune the configurations on the server side.

**Comment by remh** [comment]
Looks like we could get that from /proc/sys/fs/file-nr 

@ssbarnea what do you think ?

**Comment by ssbarnea** [comment]
This doesn't seem to fix the issue, we need to be able to read the number of file descriptors per user and this seems to return the same result for any user.

**Comment by remh** [comment]
Thanks for the feedback @ssbarnea 

It's not possible to get the number of open FD per user without being root.
Getting the number of open FD per user can also potentially generates hundreds of different timeseries for a use case that's not pretty clear. It will also be way slower than just reading from /proc/sys/fs/file-nr as it will have to go through all running PIDs (that's basically what `lsof` does).

Reading the number of open FD and the limit in /proc/sys/fs/file-nr would be on the other hand pretty straightforward, fast to execute, doesn't require root access and will let you the visibility to detect FD leaks.

So it's likely the way we will go. What do you think ?

**Comment by ssbarnea** [comment]
We are running ~6 serious JVM applications on the same bare-metal machine, each o them under its own username, and they all have custom ulimits. We never went out of filehandlers for the system itself but every 3-4 months we have an issue releated to them, caused by either a bug or just normal usage increase.

If we would monitor only the global number of file handlers we would not be able to stop who is generating the problem. 

As an workaround I could setup the same limits for all applicaitions, having them at 90% of total system limits for each of them and monitor only the total values.

I do agree that under no circumstance we should count all FD for each PID. 

Needing root acees is not a problem from my point of view, doing a proper monitoring almost always required root access. There are way to secure this, allow datadog user to run a specific command that runs as root could be one option.

**Comment by ssbarnea** [comment]
I hope someone from DataDog will pull this https://github.com/DataDog/ansible-datadog/pull/13 which is needed for this bug.

**Comment by remh** [comment]
@ssbarnea thanks for the feedback
We closed https://github.com/DataDog/ansible-datadog/pull/13 as psutil is already included in the agent.

One way to do that would be for you to add lsof access to dd-agent in the sudoer file.

Then we could have the process check to call lsof on the pids found by the process check.
Would that work ?

**Comment by ssbarnea** [comment]
Yes it, in addition with the correct configuration of lsof via ansible this would work. Thanks!

**Comment by alexef** [comment]
Just for the record, and to save others the time searching for it, currently Datadog only supports open file handlers per process -for system, there is just a sum of the monitored processes open_fd(s).

**Comment by lalarsson** [comment]
@alexef Thanks for the information.

Is there any possibilty that the total open file handlers per system will be included in the future?

**Comment by tomstockton** [comment]
+1 - @remh what happened to monitoring the relevant values in `/proc/sys/fs/file-nr`?  This would be really useful.  I could write a custom check but I feel like it should be a core metric.

**Comment by jippi** [comment]
👍  the aggregate of /proc/sys/fs/file-nr would be super useful!

**Comment by remh** [comment]
Reopening we can indeed add the content of /proc/sys/fs/file-nr although it's not as precise.

**Comment by abeluck** [comment]
Any movement on this issue? This is quite an important metrics for us.

**Comment by pdecat** [comment]
@abeluck, I've got a PR at DataDog/integrations-core#715 but some changes were requested before it can be considered to be merged. I don't have time to implement them right now, though.

FWIW, we are using this patch as is since August.

**Comment by olivielpeau** [comment]
On Linux, the Agent now reports the total number of open file handles over the system limit (as the fraction `system.fs.file_handles.in_use`), by default. The value is collected from `/proc/sys/fs/file-nr`. 
So I'll go ahead and close this issue.

`root` permissions are needed to collect per-process values. @pdeca's PR here https://github.com/DataDog/integrations-core/pull/1235 implements a way to grab these metrics without making the whole agent run as `root`.
