### ISSUE TITLE
support for monitoring netscaler

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#854]
I am almost sure that we may not be able to install dd-agent on netscaler itself, or at least it wouldn't be recommended.

Still, netscaler does provide a good set of SNMP metrics, so all we need is to monitor it from another host using SNMP. 

Still we need a template with a basic configuration on it. If no-one can help with this, i will probably take care of this ticket.

**Comment by remh** [comment]
Thanks for the feedback @ssbarnea I'm closing this ticket as it's been pending for a while without real traction. 
I will reopen it if needed. 
Thanks again!
