### ISSUE TITLE
Document how to run agent in a Docker container

### ISSUE THREAD

**Issue by yawn** [DataDog/dd-agent#860]
Assumption:
- Dockers `privileged` mode is enough for the agent (I assume it is, otherwise this would probably be way too much work)

Task:
- supply an option to start the agent in foreground, logging to `stdout`; I've invested maybe 10m (knowing nothing about supervisord and/or python) to try to get it running like this:

```
FROM ubuntu

ENV DD_API_KEY mykey

RUN bash -c "$(wget -qO- http://dtdg.co/agent-install-ubuntu)"
RUN sed -i "s/nodaemon = false/nodaemon = true/" /etc/dd-agent/supervisor.conf

ENTRYPOINT [ "/usr/bin/supervisord", "-c", "/etc/dd-agent/supervisor.conf" ]
```

This fails with

```
Error: positional arguments are not supported
For help, use /usr/bin/supervisord -h
```

**Comment by 502155589** [comment]
looking
