### ISSUE TITLE
agent not compatible with .net framework 4.5: Exception: Missing data from Win32_PerfFormattedData_W3SVC_WebService

### ISSUE THREAD

**Issue by celenechang** [DataDog/dd-agent#895]

**Comment by jeremymv2** [comment]
I'm setting this up in Chef for my company and am also getting this same error.

Agent version 5.2.3
Platform Windows-2012Server-6.2.9200
Python version 2.7.8

  File "c:\Program Files (x86)\Datadog\Datadog Agent\files\..\checks.d\iis.py", line 68, in check
Exception: Missing data from Win32_PerfFormattedData_W3SVC_WebService
