### ISSUE TITLE
System disk check doesn't pick up line-wrapped devices

### ISSUE THREAD

**Issue by sethrosenblum** [DataDog/dd-agent#907]
When the output of `df` line-wraps, we don't pick up the correct name for the device.

For instance, this output won't work for a device:
```
/dev/sdb             412814512   1436340 390408396   1%
/really/long/mount/point/name
```

we should probably just use `df -P` for more consistent output.

**Comment by remh** [comment]
Disk check got rewritten and is now using psutil a while ago. Closing this issue
