### ISSUE TITLE
MySQL check fails on OSX looking for /proc/<pid>/stats

### ISSUE THREAD

**Issue by dcoleman17** [DataDog/dd-agent#984]
/proc does not exist on OSX, so we need to get the mysql process user time and kernel time a different way on OSX.

https://github.com/DataDog/dd-agent/blob/4.3.1/checks.d/mysql.py#L270

**Comment by truthbk** [comment]
@remh implemented with `psutil`, but we still won't get the cpu time if we're not  running as superuser.

**Comment by truthbk** [comment]
@remh you are right that psutil will provide some form of cpu usage stats even with limited privileges. This is already done in #2116 .
